<?php
if (!in_array($_SERVER['REMOTE_ADDR'] ?? '', ['127.0.0.1','::1'], true)) { http_response_code(403); exit; }
if(!isset($_GET['mode'])&&!isset($_GET['table'])){require __DIR__.'/menu.php';exit;}
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PokeSim · The Matcha Table</title><link rel="stylesheet" href="local.css?v=<?php echo filemtime(__DIR__.'/local.css'); ?>"><link rel="stylesheet" href="damage-stats.css?v=<?php echo filemtime(__DIR__.'/damage-stats.css'); ?>"></head>
<body>
<header class="topbar"><a class="brand" href="./"><span class="brand-mark">◒</span><span><strong>POKESIM</strong><small>THE MATCHA TABLE</small></span></a><span id="matchMode" class="match-label">LOCAL PLAY</span><nav><a class="menu-button" href="./">Main menu</a><button id="bot" class="primary">Play vs bot ↗</button><button id="settingsOpen">Match settings</button><button id="historyOpen" aria-expanded="false">History</button><button id="refresh" aria-label="Refresh game">↻</button></nav></header>
<div class="table-shell"><main><div class="table-heading"><div><span class="eyebrow">POKÉMON TCG / LOCAL MATCH</span><h1>A little strategy. A lot of matcha.</h1></div><a href="?mode=bot&amp;new=1">New bot match ↗</a></div><div id="board" class="playmat"></div><section class="hand-tray"><div class="section-heading"><h2>Your hand <span id="handCount"></span></h2><span id="handHint">Select a card to play it</span></div><div id="hand" class="hand-cards"></div></section><footer>Fan project · Card data and artwork by <a href="https://tcgdex.dev">TCGdex</a>. Pokémon belongs to its respective owners.</footer></main>
<aside><section class="panel turn-panel"><span id="round" class="eyebrow">WELCOME TO THE TABLE</span><h2 id="status" role="status"></h2><p id="turnHint"></p><p id="error" role="alert"></p></section><section class="panel"><div class="section-heading"><h2 id="actionTitle">Your moves</h2><button id="clearSelection" hidden>Clear</button></div><div id="actions"></div></section><section class="panel"><button id="statsOpen">Match stats</button></section><section class="panel inspector"><span class="eyebrow">CARD SPOTLIGHT</span><div id="inspect"><div class="empty-inspector">◒</div><p>Hover over a card to take a closer look.</p></div></section></aside></div>
<aside id="history" class="history-drawer" hidden><div class="section-heading"><h2>Match history</h2><button id="historyClose" aria-label="Close history">×</button></div><div id="log"></div></aside>
<dialog id="stats" aria-labelledby="statsTitle"><div class="section-heading"><h2 id="statsTitle">Match stats</h2><button id="statsClose" aria-label="Close match stats">×</button></div><section id="matchDamage" class="damage-stats"></section><details class="damage-stats"><summary>Damage averages · latest 200 completed matches in this browser</summary><div id="matchAverages"></div></details></dialog>
<dialog id="settings"><div class="section-heading"><h2>Match settings</h2><button id="settingsClose" aria-label="Close settings">×</button></div><label>View player<select id="seat"><option value="1">Player 1</option><option value="2">Player 2</option></select></label><label>Your deck<select id="deckKey1"><option value="sinistcha">Dhelmise / Sinistcha</option><option value="dhelmise-v2">dhelmise v2</option><option value="brisbane-lopunny">Brisbane Lopunny</option><option value="relicanth-fossils">Relicanth / Fossils</option><option value="relicanth-v2-draw">relicanth v2 - draw</option><option value="relicanth-v3-meta-tune">Relicanth-v3-meta-tune</option><option value="relicanth-v4-colress">Relicanth v4 - Colress</option><option value="relicanth-v5-bastiodon">Relicanth v5 - Bastiodon</option><option value="relicanth-v6-explorers-guidance">Relicanth v6 - Explorer's Guidance</option><option value="relicanth-v7-lanas-aid">Relicanth v7 - Lana's Aid</option></select></label><label>Opponent deck<select id="deckKey2"><option value="sinistcha">Dhelmise / Sinistcha</option><option value="dhelmise-v2">dhelmise v2</option><option value="brisbane-lopunny">Brisbane Lopunny</option><option value="relicanth-fossils">Relicanth / Fossils</option><option value="relicanth-v2-draw">relicanth v2 - draw</option><option value="relicanth-v3-meta-tune">Relicanth-v3-meta-tune</option><option value="relicanth-v4-colress">Relicanth v4 - Colress</option><option value="relicanth-v5-bastiodon">Relicanth v5 - Bastiodon</option><option value="relicanth-v6-explorers-guidance">Relicanth v6 - Explorer's Guidance</option><option value="relicanth-v7-lanas-aid">Relicanth v7 - Lana's Aid</option></select></label><label>Shuffle seed (optional)<input id="seed" type="number" min="1" max="2147483647" step="1" placeholder="Random each match"></label><p id="currentSeed" class="printing"></p><details><summary>Bring your own deck</summary><p>Paste a Limitless export. Leave empty to use the selected deck. The bot uses the selected opponent deck.</p><textarea id="deck1" aria-label="Player 1 deck" placeholder="Your deck"></textarea><textarea id="deck2" aria-label="Player 2 deck" placeholder="Player 2 hotseat deck"></textarea></details><button id="reset" class="primary">Start hotseat match</button></dialog>
<div id="decisionOverlay" class="decision-overlay" hidden><section id="decision" class="decision-dialog" role="dialog" aria-modal="true" aria-labelledby="decisionTitle"></section></div>
<script src="damage-stats.js?v=<?php echo filemtime(__DIR__.'/damage-stats.js'); ?>"></script><script src="interaction.js?v=<?php echo filemtime(__DIR__.'/interaction.js'); ?>"></script>
<script src="local.js?v=<?php echo filemtime(__DIR__.'/local.js'); ?>"></script></body></html>
