<?php
if (!in_array($_SERVER['REMOTE_ADDR'] ?? '', ['127.0.0.1','::1'], true)) { http_response_code(403); exit; }
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PokeSim · The Matcha Table</title><link rel="stylesheet" href="local.css?v=<?php echo filemtime(__DIR__.'/local.css'); ?>"></head>
<body>
<header class="topbar"><a class="brand" href="./"><span class="brand-mark">◒</span><span><strong>POKESIM</strong><small>THE MATCHA TABLE</small></span></a><span id="matchMode" class="match-label">LOCAL PLAY</span><nav><button id="bot" class="primary">Play vs bot ↗</button><button id="settingsOpen">Match settings</button><button id="historyOpen" aria-expanded="false">History</button><button id="refresh" aria-label="Refresh game">↻</button></nav></header>
<div class="table-shell"><main><div class="table-heading"><div><span class="eyebrow">POKÉMON TCG / SINISTCHA MIRROR</span><h1>A little strategy. A lot of matcha.</h1></div><a href="?mode=bot&amp;new=1">New bot match ↗</a></div><div id="board" class="playmat"></div><section class="hand-tray"><div class="section-heading"><h2>Your hand <span id="handCount"></span></h2><span id="handHint">Select a card to play it</span></div><div id="hand" class="hand-cards"></div></section><footer>Fan project · Card data and artwork by <a href="https://tcgdex.dev">TCGdex</a>. Pokémon belongs to its respective owners.</footer></main>
<aside><section class="panel turn-panel"><span id="round" class="eyebrow">WELCOME TO THE TABLE</span><h2 id="status" role="status"></h2><p id="turnHint"></p><p id="error" role="alert"></p></section><section class="panel"><div class="section-heading"><h2 id="actionTitle">Your moves</h2><button id="clearSelection" hidden>Clear</button></div><div id="actions"></div></section><section class="panel inspector"><span class="eyebrow">CARD SPOTLIGHT</span><div id="inspect"><div class="empty-inspector">◒</div><p>Hover over a card to take a closer look.</p></div></section></aside></div>
<aside id="history" class="history-drawer" hidden><div class="section-heading"><h2>Match history</h2><button id="historyClose" aria-label="Close history">×</button></div><div id="log"></div></aside>
<dialog id="settings"><div class="section-heading"><h2>Match settings</h2><button id="settingsClose" aria-label="Close settings">×</button></div><label>View player<select id="seat"><option value="1">Player 1</option><option value="2">Player 2</option></select></label><label>Shuffle seed<input id="seed" type="number" value="42"></label><details><summary>Bring your own deck</summary><p>Paste a Limitless export. Leave empty to use the Sinistcha deck. The bot always plays Sinistcha.</p><textarea id="deck1" aria-label="Player 1 deck" placeholder="Your deck"></textarea><textarea id="deck2" aria-label="Player 2 deck" placeholder="Player 2 hotseat deck"></textarea></details><button id="reset" class="primary">Start hotseat match</button></dialog>
<div id="decisionOverlay" class="decision-overlay" hidden><section id="decision" class="decision-dialog" role="dialog" aria-modal="true" aria-labelledby="decisionTitle"></section></div>
<script src="interaction.js?v=<?php echo filemtime(__DIR__.'/interaction.js'); ?>"></script>
<script src="local.js?v=<?php echo filemtime(__DIR__.'/local.js'); ?>"></script></body></html>
