let token, state, busy=false, selectedRef=null, statsShownFor=null;
const $=id=>document.getElementById(id);
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function allCards(){return state?Object.values(state.players).flatMap(p=>['Active','Bench','Hand','TempZone','Discard'].flatMap(z=>p[z]||[])):[];}
function findCard(ref){return state?.stadium?.ref===ref?state.stadium:allCards().find(c=>c.ref===ref);}
function back(taken=false){const e=el('div','◒','card-back'+(taken?' taken':''));e.setAttribute('aria-label','Face-down card');return e;}
function art(c){const img=el('img');img.src='WebpImages/'+encodeURIComponent(c.id)+'.webp';img.alt=c.name;img.loading='lazy';img.onerror=()=>img.replaceWith(el('div',c.name,'card-fallback'));return img;}
function inspect(c){const target=$('inspect');target.replaceChildren(art(c),el('h3',c.name),el('div',c.id.toUpperCase()+(c.hp?' · '+c.hp+' HP':''),'printing'));if(c.tool&&c.tool!=='-')target.append(el('div','Tool: '+(c.toolName||c.tool),'energy-summary'));if(Array.isArray(c.energy))target.append(el('div','◆ '+c.energy.length+' attached Energy card'+(c.energy.length===1?'':'s'),'energy-summary'));const rules=[...(c.abilities||[]),...(c.attacks||[])];if(c.effect)rules.unshift({name:'Card effect',effect:c.effect});for(const a of rules){const r=el('div',undefined,'rules');r.append(el('strong',a.name+(a.damage?' · '+a.damage:'')));if(a.cost?.length)r.append(el('p',a.cost.join(' / ')));if(a.effect)r.append(el('p',a.effect));target.append(r);}}
let energyPreview, energyPreviewHideTimer;
function hideEnergyPreview(){clearTimeout(energyPreviewHideTimer);if(energyPreview)energyPreview.hidden=true;}
function scheduleEnergyPreviewHide(){energyPreviewHideTimer=setTimeout(hideEnergyPreview,150);}
function showEnergyPreview(c,anchor){
    clearTimeout(energyPreviewHideTimer);
    if(!energyPreview){energyPreview=el('div',undefined,'energy-preview');energyPreview.id='attachedEnergyPreview';energyPreview.setAttribute('role','tooltip');energyPreview.onmouseenter=()=>clearTimeout(energyPreviewHideTimer);energyPreview.onmouseleave=hideEnergyPreview;document.body.append(energyPreview);}
    const energies=c.attachedEnergy||c.energy.map(id=>({id,name:id}));
    energyPreview.replaceChildren(el('strong',c.name+' · Attached Energy'));
    if(!energies.length)energyPreview.append(el('p','No Energy attached.'));
    else{const list=el('div',undefined,'energy-preview-cards');for(const energy of energies){const item=el('div',undefined,'energy-preview-card');item.append(art(energy),el('span',energy.name));list.append(item);}energyPreview.append(list);}
    energyPreview.style.width=(energies.length<=1?150:energies.length===2?240:320)+'px';energyPreview.style.setProperty('--energy-columns',Math.max(1,Math.min(3,energies.length)));
    energyPreview.hidden=false;
    const rect=anchor.getBoundingClientRect(),preview=energyPreview.getBoundingClientRect(),gap=12;
    let left,top;
    if(rect.right+gap+preview.width<=window.innerWidth-gap){left=rect.right+gap;top=Math.max(gap,Math.min(rect.top,window.innerHeight-preview.height-gap));}
    else if(rect.left-gap-preview.width>=gap){left=rect.left-gap-preview.width;top=Math.max(gap,Math.min(rect.top,window.innerHeight-preview.height-gap));}
    else{left=Math.max(gap,Math.min(rect.left+rect.width/2-preview.width/2,window.innerWidth-preview.width-gap));const above=rect.top-preview.height-gap;top=above>=gap?above:Math.min(rect.bottom+gap,window.innerHeight-preview.height-gap);}
    energyPreview.style.left=left+'px';energyPreview.style.top=top+'px';
}
function card(c,interactive=true,caption=false){
    const e=el(interactive?'button':'div',undefined,'game-card');e.dataset.ref=c.ref||'';
    if(interactive){e.setAttribute('aria-label',c.name);e.onclick=event=>{if(event.target.closest('.energy-count')||busy)return;const result=PokeInteraction.click(state,selectedRef,c.ref);if(result.action){request({action:result.action});return;}selectedRef=result.selected;inspect(c);renderActions();highlight();};}
    e.onmouseenter=()=>inspect(c);e.onfocus=()=>inspect(c);e.append(art(c));
    if(c.hp&&/Active|Bench/.test(c.ref)){
        const stats=el('div',undefined,'card-stats');stats.append(el('span',Math.max(0,c.hp-(c.damage||0))+'/'+c.hp));
        const energy=el('span','◆ '+(c.energy?.length||0),'energy-count'+(c.energy?.length?'':' empty-energy'));
        const names=(c.attachedEnergy||[]).map(v=>v.name).join(', ');
        energy.setAttribute('aria-label',(c.energy?.length||0)+' attached Energy cards'+(names?': '+names:''));
        energy.setAttribute('aria-describedby','attachedEnergyPreview');energy.tabIndex=0;
        energy.onmouseenter=()=>showEnergyPreview(c,energy);energy.onmouseleave=scheduleEnergyPreviewHide;
        energy.onfocus=()=>showEnergyPreview(c,energy);energy.onblur=hideEnergyPreview;
        energy.onclick=event=>{event.stopPropagation();showEnergyPreview(c,energy);};
        energy.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();event.stopPropagation();showEnergyPreview(c,energy);}if(event.key==='Escape'){event.stopPropagation();hideEnergyPreview();}};
        e.append(stats,energy);
        if(c.toolName){const tool=el('span','⌁','attached-tool');tool.title=c.toolName;tool.setAttribute('aria-label','Attached Tool: '+c.toolName);e.append(tool);}
        const hp=el('div',undefined,'hp-track'),fill=el('span');fill.style.width=Math.max(0,100*(c.hp-(c.damage||0))/c.hp)+'%';hp.append(fill);e.append(hp);
        if(Object.keys(c.conditions||{}).length)e.append(el('div',Object.keys(c.conditions).join(', '),'conditions'));
    }
    if(caption)e.append(el('span',c.name,'card-caption'));return e;
}
window.addEventListener('resize',hideEnergyPreview);
document.addEventListener('scroll',event=>{if(!energyPreview?.contains(event.target))hideEnergyPreview();},true);
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.energy-count')&&!energyPreview?.contains(event.target))hideEnergyPreview();});

function highlight(){
    const targets=PokeInteraction.targets(state,selectedRef);
    document.querySelectorAll('.game-card').forEach(e=>{
        const target=targets.find(a=>a.target===e.dataset.ref);
        e.classList.toggle('selected',!!selectedRef&&e.dataset.ref===selectedRef);
        e.classList.toggle('playable',!targets.length&&!!state?.actions.some(a=>a.source===e.dataset.ref));
        e.classList.toggle('targetable',!!target);
        if(target)e.setAttribute('aria-label',(target.type==='attach'?'Attach Energy to ':'Evolve ')+(findCard(e.dataset.ref)?.name||'Pokémon'));
        else if(findCard(e.dataset.ref))e.setAttribute('aria-label',findCard(e.dataset.ref).name);
    });
    $('handHint').textContent=targets.length?'Click a highlighted Pokémon on the field · Esc to cancel':'Click a card to play or choose a move';
}
function pile(label,count,cards=[]){const e=el('div',undefined,'pile');e.append(el('div',label,'zone-label'));const b=el('button');b.setAttribute('aria-label',label+' · '+count+' cards');b.append(cards.length?art(cards[cards.length-1]):back());if(label==='Discard')b.onclick=()=>showDiscard('Discard pile',cards);else b.disabled=true;e.append(b,el('span',count,'pile-count'));return e;}
function playerSide(seat,own){const p=state.players[seat],half=el('section',undefined,'player-half'),bar=el('div',undefined,'player-bar');const name=own?'You':state.mode==='bot'?state.botName:'Player '+seat;const identity=el('div');identity.append(el('span',name,'player-name'),el('span',own?p.deckName+' / DECK PILOT':state.mode==='bot'?'HEURISTIC OPPONENT':'LOCAL OPPONENT','player-tag'));bar.append(el('span',own?'◒':'✦','avatar'),identity,el('span',p.handCount+' in hand','hand-badge'));if(!own){half.append(bar);const hidden=el('div',undefined,'hidden-hand');for(let i=0;i<Math.min(p.handCount,15);i++)hidden.append(back());half.append(hidden);}const layout=el('div',undefined,'side-layout'),left=el('div');left.append(el('div','Prizes','zone-label'));const prizes=el('div',undefined,'prizes');for(let i=0;i<6;i++)prizes.append(back(i>=p.prizeCount));left.append(prizes);const field=el('div',undefined,'battle-zone'),bench=el('div',undefined,'bench-row');for(let i=0;i<5;i++){const slot=el('div',p.Bench[i]?undefined:String(i+1),'slot'+(p.Bench[i]?'':' empty'));if(p.Bench[i])slot.append(card(p.Bench[i]));bench.append(slot);}const active=el('div',undefined,'active-zone');active.append(el('div','Active','zone-label'));const slot=el('div',p.Active.length?undefined:'Active Pokémon','slot active-slot'+(p.Active.length?'':' empty'));if(p.Active.length)slot.append(card(p.Active[0]));active.append(slot);field.append(...(own?[active,bench]:[bench,active]));const right=el('div');right.append(pile('Deck',p.deckCount),pile('Discard',p.Discard.length,p.Discard));layout.append(left,field,right);half.append(layout);if(own){bar.style.marginTop='12px';half.append(bar);}return half;}
function setBusy(flag){busy=flag;document.querySelectorAll('button').forEach(b=>{b.disabled=flag||b.dataset.locked==='true'||b.getAttribute('aria-label')?.startsWith('Deck ·');});}
async function request(body){if(busy)return;setBusy(true);$('error').textContent='';try{const r=await fetch('api.php?player='+$('seat').value,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token,revision:state?.revision})}:{});const data=await r.json();if(!data.ok)throw Error(data.error);token=data.token;state=data.state;if(body?.action)selectedRef=null;render();return true;}catch(e){$('error').textContent=e.message;return false;}finally{setBusy(false);}}
function actionLabel(a){const c=findCard(a.source),t=findCard(a.target),target=t?' → '+t.name+' ('+(a.target.includes('Active')?'Active':'Bench '+(Number(a.target.split('-')[1])+1))+')':'';if(a.type==='attack'){const attack=(a.copySource?findCard(a.copySource):c)?.attacks[a.index];return (a.copySource?'Memory Helix · ':'')+(attack?.name||'Attack')+(attack?.damage?' · '+attack.damage:'');}const labels={'setup-active':'Set as Active',bench:'Play to Bench',ready:'Confirm setup',evolve:'Evolve',trainer:'Play Trainer',attach:'Attach Energy',retreat:'Retreat',end:'End turn',ability:a.source?.startsWith('Stadium-')?'Use Fossil Quarry':['me05-072','me05-073','sv10.5w-079','sv07-130','sv07-129'].includes(c?.id)?'Discard Fossil':'Use '+(c?.abilities[a.index]?.name||'ability')};return (labels[a.type]||a.type)+(a.source&&a.source!==selectedRef?' · '+(c?.name||'card'):'')+target+(a.payment?.length?' · '+a.payment.length+' Energy':'');}
function renderActions(){const selected=findCard(selectedRef);$('actionTitle').textContent=selected?.name||'Your moves';$('clearSelection').hidden=!selected;$('actions').replaceChildren();if(!state)return;const actions=state.actions.filter(a=>!a.source&&!a.target||a.source?.startsWith('Stadium-')||selectedRef&&PokeInteraction.actionsForCard(state,selectedRef).includes(a));if(!actions.length)$('actions').append(el('p',selected?'No available moves for this card.':'Select a glowing card to see its moves.'));else for(const a of actions){const b=el('button',actionLabel(a),a.type==='ready'?'primary':undefined);b.onclick=()=>request({action:a});$('actions').append(b);}if(!selected&&state.actions.some(a=>a.source))$('actions').append(el('p','Click a glowing card to play it or choose a move.'));}
function choiceFace(c){if(c.card)return card(findCard(c.value)||{id:c.card,name:c.label,ref:c.value},false,true);const e=el('div');e.append(back(),el('span',c.label,'card-caption'));return e;}
function decide(d,value){request({action:{type:'decision',player:d.player,value}});}
function renderDecision(d){$('decisionOverlay').hidden=!d;const box=$('decision');box.replaceChildren();if(!d)return;box.append(el('span','YOUR CHOICE','eyebrow'),el('h2',d.prompt||'Choose a card'));box.querySelector('h2').id='decisionTitle';const multi=d.type==='MZMULTICHOOSE';box.append(el('p',multi?'Choose '+d.min+'–'+d.max+' cards.':'Choose an option to continue.'));const preview=state.players[state.viewer].TempZone;if(preview?.length){const details=el('details',undefined,'preview');details.append(el('summary','Cards you looked at'));const cards=el('div',undefined,'choices');preview.forEach(c=>cards.append(card(c,false,true)));details.append(cards);box.append(details);}const list=el('div',undefined,'choices');let submit,countText;for(const c of d.choices||[]){if(multi){const label=el('label',undefined,'choice'),check=el('input');check.type='checkbox';check.value=c.value;check.setAttribute('aria-label',c.label);check.onchange=()=>{const n=list.querySelectorAll('input:checked').length;countText.textContent=n+' selected';submit.dataset.locked=String(n<d.min||n>d.max);submit.disabled=busy||submit.dataset.locked==='true';};label.append(check,choiceFace(c));list.append(label);}else{const b=el('button',undefined,'choice');b.setAttribute('aria-label',c.label);b.append(choiceFace(c));b.onclick=()=>decide(d,c.value);list.append(b);}}box.append(list);const footer=el('div',undefined,'decision-footer');if(multi){countText=el('span','0 selected');submit=el('button','Confirm selection','primary');submit.dataset.locked=String(d.min>0);submit.onclick=()=>decide(d,[...list.querySelectorAll('input:checked')].map(c=>c.value).join('&')||'-');footer.append(countText,submit);}else if(d.type==='NUMBERCHOOSE'){const input=el('input');input.type='number';input.min=d.min;input.max=d.max;input.value=d.min;input.setAttribute('aria-label',d.prompt);submit=el('button','Confirm','primary');submit.onclick=()=>decide(d,input.value);footer.append(input,submit);}else if(d.min===0){const skip=el('button','Skip');skip.onclick=()=>decide(d,'-');footer.append(skip);}box.append(footer);}
function showDiscard(title,cards){$('decisionOverlay').hidden=false;const box=$('decision');box.replaceChildren(el('span','PUBLIC ZONE','eyebrow'),el('h2',title));box.querySelector('h2').id='decisionTitle';const list=el('div',undefined,'choices');cards.forEach(c=>list.append(card(c,false,true)));box.append(list);if(!cards.length)box.append(el('p','No cards here yet.'));const close=el('button','Back to the table');close.style.marginTop='20px';close.onclick=()=>renderDecision(state.decision);box.append(close);}
function renderHistory(){$('log').replaceChildren();for(const event of [...state.log].reverse()){const e=el('div',undefined,'log-entry');e.append(el('small','TURN '+event.turn+(event.player?' · PLAYER '+event.player:'')),el('span',String(event.event).replaceAll('_',' ').replaceAll('-',' ')+(event.card?' · '+(allCards().find(c=>c.id===event.card)?.name||event.card):'')+(event.amount?' · '+event.amount:'')));$('log').append(e);}renderDamageStats();}
function renderDamageStats(){
    if(!state.winner&&!$('stats').open)return;
    PokeDamageStats.match($('matchDamage'),state.damageTurns||[]);
    let games=[];
    try{
        const saved=JSON.parse(localStorage.getItem('pokesimDamageGames:v1')||'[]');
        games=Array.isArray(saved)?saved:[];
        if(state.winner&&state.matchId&&state.damageTurns?.length&&!games.some(g=>g.id===state.matchId)){
            games.push({id:state.matchId,status:'complete',damageTurns:state.damageTurns});games=games.slice(-200);
            localStorage.setItem('pokesimDamageGames:v1',JSON.stringify(games));
        }
    }catch{$('matchAverages').textContent='Browser storage is unavailable; completed match averages cannot be saved.';return;}
    PokeDamageStats.averages($('matchAverages'),games);
}
function render(){hideEnergyPreview();$('currentSeed').textContent=state?.seed?'Current match seed: '+state.seed+' · Leave the field blank for a fresh shuffle.':'';const botMode=state?.mode==='bot';$('seat').disabled=botMode;$('deck2').disabled=botMode;if(botMode)$('seat').value='1';$('matchMode').textContent=botMode?'● BOT MATCH / LOCAL':'● HOTSEAT / LOCAL';$('board').replaceChildren();$('hand').replaceChildren();if(!state){$('status').textContent='Take a seat';$('turnHint').textContent='Choose a deck and opponent in Match settings, or play local hotseat.';return;}if(!findCard(selectedRef))selectedRef=null;const own=Number(state.viewer),opponent=own===1?2:1;$('board').append(playerSide(opponent,false));const center=el('div',undefined,'center-line');center.append(el('span',state.stadium?'Stadium · '+state.stadium.name:'MATCHA TABLE'),el('b','◒'),el('span',state.phase==='SETUP'?'SETTING UP':'TURN '+state.turn));$('board').append(center,playerSide(own,true));const p=state.players[own];$('handCount').textContent=p.handCount;$('handHint').textContent='Click a card to play or choose a move';p.Hand.forEach(c=>$('hand').append(card(c,true,true)));$('round').textContent=state.phase==='SETUP'?'PREPARE YOUR BOARD':'TURN '+state.turn+' / '+(state.turnPlayer===own?'YOUR MOVE':'OPPONENT');$('status').textContent=state.winner?(state.winner===own?'You win!':'Opponent wins'):state.decision?'Your choice':state.phase==='SETUP'?'Make yourself at home':state.turnPlayer===own?'Your turn':'Opponent’s turn';$('turnHint').textContent=state.winner?'Start another match from the top bar.':state.phase==='SETUP'?'Select a Basic Pokémon in your hand to make it Active. Add your Bench, then confirm setup.':'Select a card to play it, attach Energy, evolve, or attack. Glowing cards have available moves.';renderActions();renderDecision(state.decision);renderHistory();if(state.winner&&statsShownFor!==state.matchId){statsShownFor=state.matchId;if(!$('settings').open&&!$('stats').open)$('stats').showModal();}highlight();if(selectedRef)inspect(findCard(selectedRef));}
$('statsOpen').onclick=()=>{$('stats').showModal();renderDamageStats();};$('statsClose').onclick=()=>$('stats').close();
$('clearSelection').onclick=()=>{selectedRef=null;renderActions();highlight();};$('settingsOpen').onclick=()=>$('settings').showModal();$('settingsClose').onclick=()=>$('settings').close();$('historyOpen').onclick=()=>{$('history').hidden=!$('history').hidden;$('historyOpen').setAttribute('aria-expanded',String(!$('history').hidden));};$('historyClose').onclick=()=>{$('history').hidden=true;$('historyOpen').setAttribute('aria-expanded','false');};$('seat').onchange=()=>{selectedRef=null;request();};$('refresh').onclick=()=>request();
function reset(mode){if(!$('seed').reportValidity())return;history.replaceState(null,'',location.pathname+'?mode='+mode);selectedRef=null;statsShownFor=null;$('stats').close();$('settings').close();const body={command:'reset',mode,deckKey1:$('deckKey1').value,deckKey2:$('deckKey2').value};if($('seed').value.trim())body.seed=Number($('seed').value);if($('deck1').value.trim())body.deck1=$('deck1').value;if(mode!=='bot'&&$('deck2').value.trim())body.deck2=$('deck2').value;return request(body);}
$('reset').onclick=()=>reset('hotseat');$('bot').onclick=()=>reset('bot');document.addEventListener('keydown',e=>{if(e.key==='Escape'){hideEnergyPreview();$('history').hidden=true;selectedRef=null;renderActions();highlight();}});
async function start(){await request();const params=new URLSearchParams(location.search);const mode=params.get('mode');for(const seat of [1,2]){const key=params.get('deck'+seat);if(key&&['sinistcha','dhelmise-v2','brisbane-lopunny','relicanth-fossils','relicanth-v2-draw','relicanth-v3-meta-tune','relicanth-v4-colress','relicanth-v5-bastiodon','relicanth-v6-explorers-guidance','relicanth-v7-lanas-aid'].includes(key))$('deckKey'+seat).value=key;else if(state)$('deckKey'+seat).value=state.players[seat].deckKey;}if((mode==='bot'||mode==='hotseat')&&(params.get('new')==='1'||mode==='bot'&&state?.mode!=='bot'))await reset(mode);}start();
