  <div class="fab-combat-progress" tabindex="0" aria-label="Combat progress; drag or use arrow keys to move" data-fab-drag-handle>
    <div class="fab-combat-step" data-fab-step="LAYER" aria-label="layer phase" title="layer"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#layer"></use></svg><span class="fab-step-label">Layer</span></div>
    <div class="fab-combat-step" data-fab-step="ATTACK" aria-label="attack phase" title="attack"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#attack"></use></svg><span class="fab-step-label">Attack</span></div>
    <div class="fab-combat-step" data-fab-step="DEFEND" aria-label="defend phase" title="defend"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#defend"></use></svg><span class="fab-step-label">Defend</span></div>
    <div class="fab-combat-step" data-fab-step="REACTION" aria-label="reaction phase" title="reaction"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#reaction"></use></svg><span class="fab-step-label">React</span></div>
    <div class="fab-combat-step" data-fab-step="DAMAGE" aria-label="damage phase" title="damage"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#damage"></use></svg><span class="fab-step-label">Damage</span></div>
    <div class="fab-combat-step" data-fab-step="RESOLUTION" aria-label="resolution phase" title="resolution"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#resolution"></use></svg><span class="fab-step-label">Resolve</span></div>
    <div class="fab-combat-step" data-fab-step="CLOSE" aria-label="close phase" title="close"><svg class="fab-step-glyph" aria-hidden="true" focusable="false"><use href="./FaBSim/Assets/Icons/phases.svg#close"></use></svg><span class="fab-step-label">Close</span></div>
  </div>
