<?php
// Dynasty: explicit seats, persistent identities, and saved await macros for decisions.
function FaBDYNCount(int $p,string $k): int {return FaBARCEffect($p,'DYN_'.$k);}
function FaBDYNAdd(int $p,string $k,int $n=1): void {FaBWTRAddEffect($p,'DYN_'.$k,$n);}
function FaBDYNClear(int $p,string $k): void {FaBWTRSetEffects($p,array_values(array_filter(FaBWTREffects($p),fn($e)=>($e['type']??'')!=='DYN_'.$k)));}
function FaBDYNHeroTargets(int $p,bool $other=false,bool $all=false): string {$r=[];$seats=FaBSeatCount()>2&&!$all?FaBAdjacentOpponents($p):FaBLiveSeats();foreach($seats as $s)if(!$other||$s!==$p)$r=array_merge($r,FaBChoiceRefs($s,'Hero'));return implode('&',$r);}
function FaBDYNAnyTargets(int $p): string {$r=[FaBDYNHeroTargets($p)];foreach(FaBDYNSelectedSeats(FaBDYNHeroTargets($p)) as $s)$r=array_merge($r,FaBChoiceRefs($s,'Arena',['type'=>'Ally']));return implode('&',array_filter($r));}
function FaBDYNTag(string $r,string $tag): void {$f=FaBIdentityFromMZ($r);if($f)FaBTagUID(intval($f['object']->UniqueID),$tag);}
function FaBDYNCounter(string $r,string $k,int $n): void {$f=FaBIdentityFromMZ($r);if(!$f)return;$o=$f['object'];$v=intval(FaBObjectCounters($o)[$k]??0)+($k==='DEFENSE'?-$n:$n);FaBSetObjectCounter($o,$k,max(0,$v));}
function FaBDYNDestroyChoice(string $r): void {$f=FaBIdentityFromMZ($r);if($f)FaBMONDestroy(intval($f['object']->UniqueID));}
function FaBDYNDestroyUIDs(array $uids): void {foreach(array_unique($uids) as $uid)FaBMONDestroy(intval($uid));}
function FaBDYNMoveSelected(int $p,string $r,string $zone): void {foreach(FaBUPRUIDs($r) as $uid){$f=FaBFindUID($uid);if(!$f||$f['player']!==$p)continue;$o=FaBMoveUID($uid,$zone,$p);if($o&&$zone==='Arena'&&FaBHasType($o,'Item'))FaBARCEnterItem($p,$o);}}
function FaBDYNBottomRef(string $r): void {$f=FaBIdentityFromMZ($r);if($f)FaBARCToDeck($f['player'],intval($f['object']->UniqueID),false);}
function FaBDYNNext(int $p,string $kind,int $power=0,string $tags=''): void {FaBWTRAddEffect($p,'DYN_NEXT',$power,['kind'=>$kind,'tags'=>array_filter(explode(',',$tags))]);}
function FaBDYNMatch(object $o,string $kind): bool {return match($kind){'ANY'=>true,'SIX'=>intval(CardPower($o->CardID))>=6,'BRUTE'=>FaBHasType($o,'Brute'),'GUARDIAN'=>FaBHasType($o,'Guardian'),'WEAPON'=>FaBWTRIsWeapon($o),'AXE'=>FaBHasType($o,'Axe'),'DAGGER'=>FaBHasType($o,'Dagger'),'BLADE'=>FaBHasType($o,'Sword')||FaBHasType($o,'Dagger'),'ARROW'=>FaBHasType($o,'Arrow'),'RUNEAA'=>FaBWTRIsAttackAction($o)&&FaBHasType($o,'Runeblade'),'ASSASSIN'=>FaBWTRIsAttackAction($o)&&FaBHasType($o,'Assassin'),'CONTRACT'=>FaBDYNContract($o->CardID)!=='',default=>false};}
function FaBDYNAttacks(int $p,string $kind): string {$s=FaBGetState();$f=FaBFindUID(intval($s['attackUID']));return $f&&intval($s['attacker'])===$p&&FaBDYNMatch($f['object'],$kind)?$f['mzID']:'';}
function FaBDYNDefenders(int $p,string $kind): string {return FaBDYNAttacks($p,$kind)!==''?FaBDefendingChoices(intval(FaBGetState()['defender']), true):'';}
function FaBDYNEquipment(int $p,string $kind=''): string {$r=array_merge(FaBChoiceRefs($p,'Equipment'),FaBChoiceRefs($p,'CombatChain',['type'=>'Equipment']));return implode('&',array_filter($r,function($r)use($kind){$o=FaBIdentityFromMZ($r)['object'];if($kind==='DAMAGED')return intval(FaBObjectCounters($o)['DEFENSE']??0)>0;if($kind==='OFFHAND'||str_starts_with($kind,'REPAIR_'))return FaBHasType($o,'Guardian')&&FaBHasType($o,'Off-Hand')&&($kind==='OFFHAND'||(intval(CardDefense($o->CardID))<=intval(substr($kind,7))&&intval(FaBObjectCounters($o)['DEFENSE']??0)>0));return true;}));}
function FaBDYNDefendingEquipment(): string {$s=FaBGetState();return implode('&',array_filter(explode('&',FaBDYNEquipment(intval($s['defender']))),function($r)use($s){$f=FaBIdentityFromMZ($r);return $f&&$f['zone']==='CombatChain'&&intval($f['object']->ChainLink)===intval($s['chainLink']);}));}
function FaBDYNShieldDefending(int $p): bool {foreach(explode('&',FaBDYNEquipment($p,'OFFHAND')) as $r){$f=FaBIdentityFromMZ($r);if($f&&$f['zone']==='CombatChain'&&intval($f['object']->ChainLink)===intval(FaBGetState()['chainLink'])&&FaBCurrentDefense($f['object'],$p)>0)return true;}return false;}
function FaBDYNAimed(int $uid): bool {$f=FaBFindUID($uid);return $f&&intval(FaBObjectCounters($f['object'])['AIM']??0)>0;}
function FaBDYNAimTargets(int $p): string {return implode('&',array_filter(FaBChoiceRefs($p,'Arsenal',['type'=>'Arrow']),fn($r)=>empty(FaBIdentityFromMZ($r)['object']->FaceDown)));}
function FaBDYNEnergy(int $p): string {return implode('&',array_filter(array_merge(FaBChoiceRefs($p,'Arena'),FaBChoiceRefs($p,'Equipment'),FaBChoiceRefs($p,'Weapons')),fn($r)=>intval(FaBObjectCounters(FaBIdentityFromMZ($r)['object'])['ENERGY']??0)>0));}
function FaBDYNPitched(int $uid,string $kind): bool {return (bool)FaBARCCard($uid,'dynPitch'.$kind);}
function FaBDYNRecordPitch(int $p,string $id): void {$uid=intval(FaBGetState()['pendingPayment']['uid']??0);if(!$uid)return;if(FaBHasType($id,'Attack'))FaBARCSetCard($uid,'dynPitchAA',true);elseif(FaBHasType($id,'Action'))FaBARCSetCard($uid,'dynPitchNAA',true);}
function FaBDYNContract(string $id): string {return match(FaBWTRBase($id)){'already_dead'=>'NON_ACTION','annihilate_the_armed'=>'AA','fleece_the_frail'=>'DEFENSE','nix_the_nimble'=>'REACTION','plunder_the_poor'=>'CHEAP','rob_the_rich'=>'EXPENSIVE','sack_the_shifty'=>'AGAIN','slay_the_scholars'=>'NAA','eradicate'=>'YELLOW','leave_no_witnesses','excessive_bloodloss'=>'RED','surgical_extraction','mist_hunter'=>'BLUE',default=>''};}
function FaBDYNContractMatches(string $kind,string $id): bool {return match($kind){'NON_ACTION'=>!FaBHasType($id,'Action'),'AA'=>FaBHasType($id,'Attack')&&FaBHasType($id,'Action'),'NAA'=>FaBHasType($id,'Action')&&!FaBHasType($id,'Attack'),'DEFENSE'=>is_numeric(CardDefense($id))&&intval(CardDefense($id))<=2,'REACTION'=>FaBHasType($id,'Attack Reaction')||FaBHasType($id,'Defense Reaction'),'CHEAP'=>is_numeric(CardCost($id))&&intval(CardCost($id))<=1,'EXPENSIVE'=>is_numeric(CardCost($id))&&intval(CardCost($id))>=2,'AGAIN'=>FaBPrintedKeywordIsActive($id,'Go again'),'RED'=>intval(CardPitch($id))===1,'YELLOW'=>intval(CardPitch($id))===2,'BLUE'=>intval(CardPitch($id))===3,default=>false};}
function FaBDYNBanished(int $owner,object $o,int $p): void {FaBSUPContract($owner,$o,$p);if(!in_array($p,FaBOpponents($owner),true))return;foreach(FaBChoiceRefs($p,'CombatChain') as $r){$contract=FaBIdentityFromMZ($r)['object'];if(HasNoAbilities($contract)||($contract->Role??'')!=='ATTACK')continue;if(FaBDYNContractMatches(FaBDYNContract($contract->CardID),$o->CardID)){FaBWTRCreateArena($p,'silver');FaBDYNAdd($p,'CONTRACTS');}}}
function FaBDYNBanishTop(int $p,int $victim,int $n): void {if(!in_array($victim,FaBOpponents($p),true))return;for($i=0;$i<$n;++$i){$r=FaBChoiceRefs($victim,'Deck')[0]??'';if($r==='')break;FaBDYNBanishChoice($r,$p);}}
function FaBDYNBanishChoice(string $r,int $actor=0): void {$f=FaBDYNPrivateOriginal($r);if($f){$o=FaBMoveUID(intval($f['object']->UniqueID),'Banish',$f['player']);if($o)FaBDYNBanished($f['player'],$o,$actor);}}
function FaBDYNPeekTop(int $viewer,int $owner): array {$r=FaBChoiceRefs($owner,'Deck')[0]??'';$f=FaBIdentityFromMZ($r);if(!$f)return [];$uid=intval($f['object']->UniqueID);FaBMoveUID($uid,'Temp',$viewer);return [$uid];}
function FaBDYNFinishPeek(int $owner,array $uids,bool $bottom): void {foreach(array_reverse($uids) as $uid){$f=FaBFindUID($uid);if($f&&$f['zone']==='Temp'){FaBARCToDeck($owner,$uid,!$bottom);}}}
function FaBDYNFinishPeekOrder(int $owner,array $uids,string $result): void {
 $piles=[];foreach(explode(';',$result) as $pile){$pair=explode('=',$pile,2);if(count($pair)===2)$piles[$pair[0]]=explode(',',$pair[1]);}
 foreach($uids as $uid){$f=FaBFindUID(intval($uid));if($f&&$f['zone']==='Temp')FaBDYNFinishPeek($owner,[$uid],in_array($f['object']->CardID,$piles['Bottom']??[],true));}
}
function FaBDYNLoadTargets(int $p,array $uids): string {if(!FaBELEArsenalSpace($p))return '';return implode('&',array_merge(FaBChoiceRefs($p,'Hand',['type'=>'Arrow']),array_filter(explode('&',FaBEVRUIDRefs($uids)),fn($r)=>FaBHasType(FaBIdentityFromMZ($r)['object'],'Arrow'))));}
function FaBDYNTopArrow(int $p,bool $aim=false): void {$r=FaBChoiceRefs($p,'Deck')[0]??'';$f=FaBIdentityFromMZ($r);if(!$f)return;FaBRevealChoices($p,$r);if(FaBHasType($f['object'],'Arrow')&&FaBARCLoadArsenal($p,$r,true)&&$aim){$f=FaBFindUID(intval($f['object']->UniqueID));FaBSetObjectCounter($f['object'],'AIM',max(1,intval(FaBObjectCounters($f['object'])['AIM']??0)));}}
function FaBDYNRevealArrow(int $p,string $r): bool {$f=FaBIdentityFromMZ($r);if(!$f)return false;FaBRevealChoices($p,$r);return FaBHasType($f['object'],'Arrow');}
function FaBDYNAttackerUID(): int {$s=FaBGetState();$a=FaBFindUID(intval($s['attackUID']));return $a&&FaBHasType($a['object'],'Ally')?intval(FaBObjectCounters($a['object'])['MON_SOURCE_UID']??0):FaBUPRHeroUID(intval($s['attacker']));}
function FaBDYNMindWarp(int $uid): void {$f=FaBFindUID($uid);if(!$f||$f['zone']!=='Hero')return;$p=$f['player'];$n=FaBHandCount($p);foreach(FaBUPRUIDs(implode('&',FaBChoiceRefs($p,'Hand'))) as $u)FaBMoveUID($u,'Deck',$p);FaBShuffleDeck($p);DoDrawCard($p,max(0,$n-1));}
function FaBDYNSurgeAgain(int $p,int $uid): void {if(!FaBARCCard($uid,'dynSurgeAgain')&&FaBWTRMayGoAgain($p)){FaBARCSetCard($uid,'dynSurgeAgain',true);AddActionPoints($p,intval(GetActionPoints($p))+1);}}
function FaBDYNTigerCount(int $p,string $r): int {$f=FaBIdentityFromMZ($r);if(!$f||!in_array('IRA_TIGER_COMBO',(array)$f['object']->TurnEffects,true))return 0;return count(FaBChoiceRefs($p,'CombatChain',['base'=>'crouching_tiger']));}
function FaBDYNRoyal(int $p): bool {return FaBCRUEquipment($p,'crown_of_dominion')!==[]||FaBHasType(GetHero($p)[0]??'','Royal');}
function FaBDYNSetup(int $p): void {FaBMSTSetup($p);foreach(FaBChoiceRefs($p,'Equipment') as $r){$o=FaBIdentityFromMZ($r)['object'];if(in_array($o->CardID,['graven_cowl','graven_vestment','graven_gloves','graven_walkers'],true))FaBSetObjectCounter($o,'DEFENSE',1);}foreach(FaBChoiceRefs($p,'Equipment') as $r){$o=FaBIdentityFromMZ($r)['object'];FaBEVOEquipped($p,$o);if($o->CardID==='seasoned_saviour')FaBSetObjectCounter($o,'DEFENSE',2);if($o->CardID==='crown_of_dominion')FaBWTRCreateArena($p,'gold');}}
function FaBDYNNeverYield(int $p): void {if(FaBHandCount($p)===0)DoDrawCard($p,1);$less=true;foreach(FaBOpponents($p) as $s)if(!FaBPENLifeMore($s,$p))$less=false;if($less)FaBCRUGainLife($p,2);}
function FaBDYNFewestEquipment(int $p): bool {$n=count(array_filter(explode('&',FaBDYNEquipment($p))));foreach(FaBOpponents($p) as $s)if($n>=count(array_filter(explode('&',FaBDYNEquipment($s)))))return false;return true;}
function FaBDYNReequip(int $p,int $uid,string $refs): void {$f=FaBFindUID($uid);$uids=FaBUPRUIDs($refs);if(!$f||$f['zone']!=='Graveyard'||count($uids)!==2)return;foreach($uids as $u){$s=FaBFindUID($u);if(!$s||$s['player']!==$p||$s['zone']!=='Arena'||$s['object']->CardID!=='silver')return;}FaBDYNDestroyUIDs($uids);FaBMoveUID($uid,'Equipment',$p);}
function FaBDYNDrivers(int $p): string {return implode('&',array_merge(FaBChoiceRefs($p,'Graveyard',['base'=>'hyper_driver']),FaBChoiceRefs($p,'Banish',['base'=>'hyper_driver'])));}
function FaBDYNDriverSteam(string $r): void {$f=FaBIdentityFromMZ($r);if($f&&FaBWTRBase($f['object']->CardID)==='hyper_driver')FaBARCSteam($f['object'],1);}
function FaBDYNMainline(int $uid,int $target): void {$f=FaBFindUID($uid);$t=FaBFindUID($target);if(!$f||!$t||$f['zone']!=='Arena'||$t['zone']!=='Arena'||$t['player']!==$f['player']||intval(FaBObjectCounters($f['object'])['STEAM']??0)<1)return;FaBARCSteam($t['object'],1);FaBARCSteam($f['object'],-1);}
function FaBDYNHarpoonTargets(string $refs,int $n): string {return implode('&',array_filter(explode('&',$refs),function($r)use($n){$f=FaBIdentityFromMZ($r);return $f&&FaBHasType($f['object'],'Action')&&is_numeric(CardDefense($f['object']->CardID))&&intval(CardDefense($f['object']->CardID))<=$n;}));}
function FaBDYNHarpoon(int $p,string $r): void {$f=FaBIdentityFromMZ($r);if(!$f||$f['zone']!=='Hand'||$f['player']!==$p)return;$o=FaBMoveUID(intval($f['object']->UniqueID),'CombatChain',$p);$o->Role='DEFENSE';$o->FromZone='Hand';$o->ChainLink=intval(FaBGetState()['chainLink']);$s=FaBGetState();$s['handBlockUIDs'][]=intval($o->UniqueID);FaBSetState($s);OnDefended($p,FaBFindUID(intval($o->UniqueID))['mzID'],$p);}
function FaBDYNLantern(int $p,string $token,int $pitch): void {$r=FaBChoiceRefs($p,'Deck')[0]??'';$f=FaBIdentityFromMZ($r);if(!$f)return;FaBRevealChoices($p,$r);if(intval(CardPitch($f['object']->CardID))===$pitch)FaBWTRCreateArena($p,$token);}
function FaBDYNLoom(int $p,int $uid): void {$n=FaBARCRunechants($p);FaBDYNDestroyUIDs(FaBUPRUIDs(implode('&',FaBMONArena($p,'runechant'))));$f=FaBFindUID($uid);if($f)FaBSetObjectCounter($f['object'],'DOOM',$n);}
function FaBDYNTickDoom(int $uid): bool {$f=FaBFindUID($uid);if(!$f||$f['zone']!=='Arena')return false;$n=intval(FaBObjectCounters($f['object'])['DOOM']??0);if(!$n){FaBMONDestroy($uid);return false;}FaBSetObjectCounter($f['object'],'DOOM',$n-1);return true;}
function FaBDYNPermanents(int $p): string {return implode('&',array_filter(FaBChoiceRefs($p,'Arena'),fn($r)=>count(array_intersect(EffectiveCardType(FaBIdentityFromMZ($r)['object']),['Ally','Aura','Item','Landmark']))>0));}
function FaBDYNSelectedSeats(string $refs): array {$out=[];foreach(explode('&',$refs) as $r){$f=FaBIdentityFromMZ($r);if($f&&$f['zone']==='Hero')$out[]=$f['player'];}return array_values(array_unique($out));}
function FaBDYNRevealRoyalHands(int $p): void {if(FaBDYNRoyal($p))foreach(FaBOpponents($p) as $s)FaBRevealChoices($s,implode('&',FaBChoiceRefs($s,'Hand')));}
function FaBDYNProhibit(int $p,string $name): void {$s=FaBGetState();$s['dynEdicts'][]=['player'=>$p,'name'=>$name];FaBSetState($s);}
function FaBDYNNameIllusionist(string $name): void {$s=FaBGetState();$s['dynIllusionNames'][]=$name;FaBSetState($s);}
function FaBDYNProtect(int $p,string $r): void {$f=FaBIdentityFromMZ($r);if($f&&$f['zone']==='Hero'&&$f['player']!==$p){$s=FaBGetState();$s['dynYoji'][$f['player']][]=$p;FaBSetState($s);}}
function FaBDYNTranquilTargets(int $p,int $cost): string {$refs=[];foreach(FaBDYNSelectedSeats(FaBDYNHeroTargets($p,true)) as $s)foreach(FaBChoiceRefs($s,'Arena',['type'=>'Aura']) as $r){$o=FaBIdentityFromMZ($r)['object'];if(FaBHasType($o,'Token')||intval(CardCost($o->CardID))<=$cost)$refs[]=$r;}return implode('&',$refs);}
function FaBDYNTranquil(int $uid,string $r): void {$f=FaBIdentityFromMZ($r);if(!$f)return;$target=intval($f['object']->UniqueID);if(FaBHasType($f['object'],'Token')){$f['object']->removed=true;return;}FaBARCSetCard($uid,'dynExiled',['uid'=>$target,'player'=>$f['player'],'card'=>$f['object']->CardID]);FaBMoveUID($target,'Banish',$f['player']);}
function FaBDYNSuraya(int $p,int $uid): void {$f=FaBFindUID(intval(FaBARCCard($uid,'dynShield')));$source=FaBFindUID($uid);if(!$source)return;if(!$f||$f['player']!==$p||$f['zone']!=='Arena'||$f['object']->CardID!=='spectral_shield'){FaBMoveUID($uid,'Graveyard',$p);return;}$f['object']->removed=true;$o=FaBMoveUID($uid,'Arena',$p);if($o){$o->CardID='suraya_archangel_of_knowledge';FaBSetObjectCounter($o,'DYN_SURAYA',1);}}
function FaBDYNConstructTargets(int $p): string {return implode('&',array_merge(FaBChoiceRefs($p,'Equipment',['type'=>'Mechanologist']),FaBChoiceRefs($p,'Weapons',['type'=>'Mechanologist']),FaBChoiceRefs($p,'Arena',['base'=>'hyper_driver'])));}
function FaBDYNConstruct(int $p,int $uid,string $refs): void {
 $uids=array_unique(FaBUPRUIDs($refs));$slots=[];$drivers=0;$cards=[];$power=0;
 foreach($uids as $u){$f=FaBFindUID($u);if(!$f||$f['player']!==$p)return;$o=$f['object'];if(FaBWTRBase($o->CardID)==='hyper_driver'&&$f['zone']==='Arena')++$drivers;elseif(FaBHasType($o,'Mechanologist')&&in_array($f['zone'],['Weapons','Equipment'],true)){foreach(['Head','Chest','Arms','Legs','Weapon'] as $slot)if(FaBHasType($o,$slot))$slots[]=$slot;}else return;$cards=array_merge($cards,FaBEVOUnder($o),[$o->CardID]);if($o->CardID==='galvanic_bender')++$power;}
 if(count($uids)!==8||$drivers!==3||count(array_unique($slots))!==5){FaBMoveUID($uid,'Graveyard',$p);return;}
 foreach($uids as $u)FaBFindUID($u)['object']->removed=true;
 $o=FaBMoveUID($uid,'Equipment',$p);if(!$o)return;$o->CardID='nitro_mechanoid';$c=FaBObjectCounters($o);$c['DYN_MATERIAL']=$cards;$c['DYN_MATERIAL_POWER']=$power;$o->Counters=$c;if(FaBWTRMayGoAgain($p))AddActionPoints($p,intval(GetActionPoints($p))+1);
}
function FaBDYNEmperorTargets(int $p): string {return implode('&',array_map(fn($t)=>FaBAttackTargetChoiceMZ($t,$p),FaBLegalAttackTargets($p)));}
function FaBDYNEmperor(int $p,int $uid,string $r): void {$f=FaBFindUID($uid);$t=FaBIdentityFromMZ($r);if(!$f||!$t){FaBCloseCombatChain();return;}$target=FaBResolveAttackTarget(FaBAttackTargetDescriptor($t),$p);if(!$target)return;$o=AddStack(CardID:$f['object']->CardID,Controller:$p,Kind:'ATTACK',SourceZone:'Deck',Params:['attackTarget'=>$target],sourceObject:$f['object']);$f['object']->removed=true;}
function FaBDYNPrivateHand(int $viewer,int $owner): array {$uids=[];foreach(FaBChoiceRefs($owner,'Hand') as $r){$f=FaBIdentityFromMZ($r);$o=AddTemp($viewer,CardID:$f['object']->CardID);$uid=intval($o->UniqueID);$uids[]=$uid;FaBARCSetCard($uid,'dynOriginal',intval($f['object']->UniqueID));}return $uids;}
function FaBDYNPrivateOriginal(string $r): ?array {$f=FaBIdentityFromMZ($r);if($f&&$f['zone']==='Temp'){$uid=intval(FaBARCCard(intval($f['object']->UniqueID),'dynOriginal'));if($uid)return FaBFindUID($uid);}return $f;}
function FaBDYNDiscardPrivate(int $p,string $r): void {$f=FaBDYNPrivateOriginal($r);if($f&&$f['zone']==='Hand'&&$f['player']===$p)FaBMoveUID(intval($f['object']->UniqueID),'Graveyard',$p);}
function FaBDYNCleaveTargets(int $p): string {$target=intval(FaBGetState()['attackTarget']['uid']??0);return implode('&',array_filter(FaBChoiceRefs($p,'Arena',['type'=>'Ally']),fn($r)=>intval(FaBIdentityFromMZ($r)['object']->UniqueID)!==$target));}
function FaBDYNMaterialPhantasm(object $o): bool {$c=FaBObjectCounters($o);if(empty($c['UPR_ASH']))return false;$exception=['dust_from_the_fertile_fields_red'=>'ouvia','dust_from_stillwater_shrine_red'=>'miragai','dust_from_the_chrome_caverns_red'=>'cromai','dust_from_the_golden_plains_red'=>'themai','dust_from_the_red_desert_red'=>'vynserakai','dust_from_the_shadow_crypts_red'=>'nekria'][$c['DYN_ASH']??'']??'';return $exception===''||$o->CardID!==$exception;}
function FaBDYNYoji(int $source,int $target,int $amount,string $type,string $ref): ?int {$s=FaBGetState();$protectors=$s['dynYoji'][$target]??[];if(!$protectors)return null;$protector=intval(array_shift($protectors));$s['dynYoji'][$target]=$protectors;FaBSetState($s);if(!FaBSeatIsLive($protector))return FaBDYNYoji($source,$target,$amount,$type,$ref);$f=FaBIdentityFromMZ($ref);$unpreventable=($type==='ARCANE'&&FaBEVRUnpreventable($source,$protector))||($f&&in_array('UPR_UNPREVENTABLE',(array)$f['object']->TurnEffects,true));DoDamage($source,$ref,$protector,max(0,$amount-($unpreventable?0:1)),$type);return 0;}
function FaBDYNAimCounter($o=null): int {$o??=$GLOBALS['obj']??null;return is_object($o)?intval(FaBObjectCounters($o)['AIM']??0):0;}
function FaBDYNDoomCounter($o=null): int {$o??=$GLOBALS['obj']??null;return is_object($o)?intval(FaBObjectCounters($o)['DOOM']??0):0;}
function FaBDYNEquipmentStillPresent(int $uid): bool {$f=FaBFindUID($uid);return $f&&($f['zone']==='Equipment'||($f['zone']==='CombatChain'&&($f['object']->FromZone??'')==='Equipment'));}
function FaBDYNQuicksilver(int $p,object $attack): bool {if($attack->CardID!=='quicksilver_dagger')return false;$self=intval(FaBObjectCounters($attack)['WEAPON_UID']??$attack->UniqueID);foreach(['Weapons','CombatChain'] as $zone)foreach(FaBChoiceRefs($p,$zone) as $r){$o=FaBIdentityFromMZ($r)['object'];$uid=intval(FaBObjectCounters($o)['WEAPON_UID']??$o->UniqueID);if($uid!==$self&&FaBWTRIsWeapon($o)&&in_array('GO_AGAIN',(array)$o->TurnEffects,true))return true;}return false;}
