<?php
/** Rosetta rules. Choice flows remain in saved, resumable card macros. */
function FaBROSCount(int $p,string $k): int {return FaBARCEffect($p,'ROS_'.$k);}
function FaBROSAdd(int $p,string $k,int $n=1,array $data=[]): void {FaBWTRAddEffect($p,'ROS_'.$k,$n,$data);}
function FaBROSClear(int $p,string $k): void {FaBWTRSetEffects($p,array_values(array_filter(FaBWTREffects($p),fn($e)=>($e['type']??'')!=='ROS_'.$k)));}
function FaBROSEarth(int $p): int {return count(array_filter(FaBChoiceRefs($p,'Banish',['type'=>'Earth']),fn($r)=>empty(FaBIdentityFromMZ($r)['object']->FaceDown)));}
function FaBROSActive(int $p,string $hero): bool {foreach(FaBChoiceRefs($p,'Hero') as $r){$o=FaBIdentityFromMZ($r)['object'];if(($o->CardID===$hero||str_starts_with($o->CardID,$hero.'_'))&&!HasNoAbilities($o)&&FaBROSEarth($p)>=(FaBHasType($o,'Young')?4:8))return true;}return false;}
function FaBROSSigils(int $p,string $zone='Arena'): string {return implode('&',array_filter(FaBChoiceRefs($p,$zone,['type'=>'Aura']),fn($r)=>str_contains(CardName(FaBIdentityFromMZ($r)['object']->CardID),'Sigil')));}
function FaBROSRefs(int $p,string $zone,string $type='',int $exclude=0): string {return implode('&',array_filter(FaBChoiceRefs($p,$zone),function($r)use($type,$exclude){$o=FaBIdentityFromMZ($r)['object'];return intval($o->UniqueID)!==$exclude&&($type===''||($type==='NAA'?FaBHasType($o,'Action')&&!FaBHasType($o,'Attack'):FaBHasType($o,$type)));}));}
function FaBROSAllAuras(int $p,bool $tokens=true,int $max=999,bool $all=false): string {$out=[];foreach($all?FaBLiveSeats():array_merge([$p],FaBAdjacentOpponents($p)) as $v)foreach(FaBChoiceRefs($v,'Arena',['type'=>'Aura']) as $r){$o=FaBIdentityFromMZ($r)['object'];if((!$tokens&&FaBHasType($o,'Token'))||intval(CardCost($o->CardID))>$max)continue;$out[]=$r;}return implode('&',$out);}
function FaBROSDecomposeReady(int $p): bool {$earth=FaBChoiceRefs($p,'Graveyard',['type'=>'Earth']);$action=FaBChoiceRefs($p,'Graveyard',['type'=>'Action']);return count($earth)>=2&&count(array_unique(array_merge($earth,$action)))>=3&&count($action)>0;}
function FaBROSDecompose(int $p,string $earth,string $action): bool {$e=FaBUPRUIDs($earth);$a=FaBUPRUIDs($action);if(count($e)!==2||count($a)!==1||in_array($a[0],$e,true))return false;foreach(array_merge($e,$a) as $i=>$uid){$f=FaBFindUID($uid);if(!$f||$f['player']!==$p||$f['zone']!=='Graveyard'||!FaBHasType($f['object'],$i<2?'Earth':'Action'))return false;}foreach(array_merge($e,$a) as $uid)FaBMoveUID($uid,'Banish',$p);return true;}
function FaBROSActionExcept(int $p,string $earth): string {$ids=FaBUPRUIDs($earth);return implode('&',array_filter(FaBChoiceRefs($p,'Graveyard',['type'=>'Action']),fn($r)=>!in_array(intval(FaBIdentityFromMZ($r)['object']->UniqueID),$ids,true)));}
function FaBROSDecomposeEarth(int $p): string {return implode('&',array_filter(FaBChoiceRefs($p,'Graveyard',['type'=>'Earth']),function($r)use($p){$u=intval(FaBIdentityFromMZ($r)['object']->UniqueID);return count(array_filter(FaBChoiceRefs($p,'Graveyard',['type'=>'Action']),fn($a)=>intval(FaBIdentityFromMZ($a)['object']->UniqueID)!==$u))>0;}));}
function FaBROSReturn(string $refs,string $zone='Hand'): void {foreach(FaBUPRUIDs($refs) as $uid){$f=FaBFindUID($uid);if($f)FaBMoveUID($uid,$zone,intval($f['object']->Owner??$f['player'])?:$f['player']);}}
function FaBROSShuffle(int $p,string $refs): void {$seats=[];foreach(FaBUPRUIDs($refs) as $uid){$f=FaBFindUID($uid);if(!$f)continue;$v=intval($f['object']->Owner??$f['player'])?:$f['player'];FaBMoveUID($uid,'Deck',$v);$seats[$v]=true;}foreach(array_keys($seats) as $v)FaBShuffleDeck($v);}
function FaBROSMark(int $uid,string $key): void {FaBARCSetCard($uid,'ros'.$key,true);}
function FaBROSQueue(int $p,string $id,int $uid=0,array $extra=[]): void {if(!FaBSeatIsLive($p))return;AddStack(CardID:$id,Controller:$p,Kind:'ABILITY',SourceUniqueID:$uid,Params:['rosTrigger'=>true]+$extra);$s=FaBGetState();if($s['pendingPayment']===null)$s['window']='PRIORITY';FaBSetState($s);}
function FaBROSResolveTrigger(int $p,object $o): void {$source=FaBFindUID(intval($o->SourceUniqueID));FaBRunSourceMacro('ResolveAbility',$p,$o->CardID,['mzID'=>$source['mzID']??'','rosEvent'=>$o->Params['rosEvent']??'','rosTarget'=>intval($o->Params['rosTarget']??0),'rosSource'=>intval($o->SourceUniqueID)]);}
function FaBROSLife(int $p,int $n): void {FaBROSAdd($p,'LIFE',$n);if(intval(GetTurnPlayer())===$p&&FaBROSActive($p,'verdance')){foreach(FaBChoiceRefs($p,'Hero') as $r){$o=FaBIdentityFromMZ($r)['object'];FaBROSQueue($p,$o->CardID,intval($o->UniqueID));}}}
function FaBROSDamaged(int $p,int $v,int $n,string $type,bool $hero=true): void {if($n<=0)return;FaBROSAdd($p,'DAMAGE',$n);if($type==='ARCANE'){FaBROSAdd($p,'ARCANE',$n);if($hero)FaBROSAdd($v,'ARCANE_TAKEN',$n);if($hero&&$p!==$v)FaBROSAdd($p,'ARCANE_OPP',$n);}
 foreach(array_unique($hero?[$p,$v]:[$p]) as $s)foreach(FaBMONArena($s,'arcane_cussing') as $r)FaBMONDestroy(intval(FaBIdentityFromMZ($r)['object']->UniqueID));
 if($hero&&$p!==$v&&!FaBROSCount($p,'VALLEY_HIT')){FaBROSAdd($p,'VALLEY_HIT');foreach(FaBMONArena($p,'channel_lightning_valley') as $r)DoDrawCard($p,1);}
 if($type==='ARCANE'&&FaBROSCount($p,'STAFF_EARTH')){FaBROSClear($p,'STAFF_EARTH');FaBWTRCreateArena($p,'embodiment_of_earth');}
}
function FaBROSAfterMove(int $p,object $o,string $from,string $to): void {
 $uid=intval($o->UniqueID);$b=FaBWTRBase($o->CardID);if(in_array($to,['Hand','Deck','Pitch','Banish'],true)&&FaBROSMeld($o->CardID))FaBARCSetCard($uid,'rosMeld',-1);
 if($to==='Banish'&&FaBHasType($o,'Earth'))FaBROSAdd($p,'EARTH_BANISHED');
 if($to==='Arena'&&$from!=='Arena'){if(FaBHasType($o,'Aura'))FaBROSAdd($p,'AURA');if($b==='malefic_incantation')FaBSetObjectCounter($o,'VERSE',4-intval(CardPitch($o->CardID)));}
 if($from==='Arena'&&$to!=='Arena'){$p=intval($o->Controller??$p)?:$p;
  if(str_starts_with($b,'sigil_')&&str_contains(CardName($o->CardID),'Sigil')){if(FaBROSCount($p,'BINDINGS'))FaBMSTAdd($p,'AMP',FaBROSCount($p,'BINDINGS'));if(in_array($b,['sigil_of_aether','sigil_of_brilliance','sigil_of_conductivity','sigil_of_cycles','sigil_of_deadwood','sigil_of_earth','sigil_of_forethought','sigil_of_fyendal','sigil_of_lightning','sigil_of_sanctuary','sigil_of_temporal_manipulation','sigil_of_the_arknight'],true))FaBROSQueue($p,$o->CardID,$uid);}
  if($b==='arcane_cussing'&&$p===intval(GetTurnPlayer()))FaBROSQueue($p,$o->CardID,$uid);
 }
 if($b==='fluttersteps'&&in_array($from,['Equipment','CombatChain'],true)&&$to==='Graveyard')FaBMSTAdd($p,'AURA_INSTANT');
}
function FaBROSPrevent(int $p,int $n,string $type,int $source): int {
 $left=[];$created=[];foreach(FaBWTREffects($p) as $e){$k=$e['type']??'';if($k==='ROS_SHELTER'&&$type==='ARCANE'||$k==='ROS_PREVENT'||$k==='ROS_SOURCE'&&intval($e['source']??0)===$source){$v=min($n,intval($e['amount']));$n-=$v;$e['amount']-=$v;if($v&&!empty($e['token'])){$created[]=$e['token'];unset($e['token']);}if($e['amount']<=0)continue;}if($k==='ROS_BRUSH'&&$n<=intval($e['amount'])){$n=0;continue;}$left[]=$e;}FaBWTRSetEffects($p,$left);foreach($created as $t)FaBWTRCreateArena($p,$t);return $n;
}
function FaBROSShelters(int $p): array {return array_values(array_filter(FaBChoiceRefs($p,'Arena'),fn($r)=>FaBHasKeyword(FaBIdentityFromMZ($r)['object'],'Arcane Shelter')));}
function FaBROSArcanite(int $p): int {return count(array_filter(FaBChoiceRefs($p,'Equipment'),fn($r)=>str_contains(CardName(FaBIdentityFromMZ($r)['object']->CardID),'Arcanite')));}
function FaBROSMeld(string $id): bool {return str_contains((string)CardFunctional_text_plain($id),'Meld');}
function FaBROSMeldTypes(object $o,array $types): array {$mode=FaBARCCard(intval($o->UniqueID??0),'rosMeld',-1);if(!FaBROSMeld($o->CardID)||$mode<0||$mode===2)return $types;$parts=explode(' // ',(string)CardType_text($o->CardID));return preg_split('/[ -]+/',trim($parts[$mode]??''),-1,PREG_SPLIT_NO_EMPTY);}
function FaBROSMeldOptions(int $p,int $uid): string {$f=FaBFindUID($uid);if(!$f)return ''; $s=FaBGetState();$base=intval(CardCost($f['object']->CardID));$tax=max(0,FaBCardCost($f['object'],$p)-$base);$action=str_contains(explode(' // ',CardType_text($f['object']->CardID))[0],'Action');$window=$s['pendingPayment']['returnWindow']??$s['window'];$canAction=!$action||($p===intval(GetTurnPlayer())&&$window==='ACTION'&&intval(GetActionPoints($p))>0&&count(array_filter(GetStack(),fn($o)=>is_object($o)&&empty($o->removed)&&intval($o->UniqueID)!==$uid))===0);$m=[];if($canAction)$m[]='Left_half';$m[]='Right_half';if($canAction&&FaBAvailablePitch($p,$uid)>=$base*2+$tax)$m[]='Meld_both';FaBARCSetCard($uid,'rosMeldOptions',$m);return implode('&',$m);}
function FaBROSMeldChoose(int $p,int $uid,string $choice): void {$f=FaBFindUID($uid);if(!$f)return;$options=(array)FaBARCCard($uid,'rosMeldOptions',[]);$label=$options[intval($choice)]??'Right_half';$mode=['Left_half'=>0,'Right_half'=>1,'Meld_both'=>2][$label];FaBARCSetCard($uid,'rosMeld',$mode);FaBARCSetCard($uid,'rosSide',$mode===0?0:1);$s=FaBGetState();$f['object']->Kind=$mode!==1&&str_contains(explode(' // ',CardType_text($f['object']->CardID))[0],'Action')?'ACTION':'INSTANT';$s['pendingPayment']['kind']=$f['object']->Kind;$s['pendingPayment']['cost']=FaBCardCost($f['object'],$p)+($mode===2?intval(CardCost($f['object']->CardID)):0);FaBSetState($s);}
function FaBROSMeldFirst(int $p,object $o): bool {$uid=intval($o->UniqueID);if(!FaBROSMeld($o->CardID)||FaBARCCard($uid,'rosMeld',-1)!==2||FaBARCCard($uid,'rosSide')!==1)return false;FaBRunSourceMacro('ResolveCard',$p,$o->CardID,['mzID'=>FaBFindUID($uid)['mzID']]);return true;}
function FaBROSMeldResume(int $uid): void {if(FaBARCCard($uid,'rosMeld',-1)===2&&FaBARCCard($uid,'rosSide')===1){FaBARCSetCard($uid,'rosSide',0);SetPriorityPlayer(intval(GetTurnPlayer()));SetConsecutivePasses(0);$s=FaBGetState();$s['window']='PRIORITY';FaBSetState($s);}}
function FaBROSResurge(int $p,int $uid,string $dest): void {$f=FaBFindUID($uid);if(!$f)return;$o=FaBMoveUID($uid,$dest,intval($f['object']->Owner??$p)?:$p);if($o&&$dest==='Banish')$o->PlayableFromBanish=1;}
function FaBROSAnyOpposing(int $p): string {return implode('&',array_filter(explode('&',FaBUPRAnyTargets($p)),fn($r)=>intval(FaBIdentityFromMZ($r)['player']??0)!==$p));}
function FaBROSInstantStack(int $exclude=0): string {$r=[];foreach(GetStack() as $i=>$o)if(is_object($o)&&empty($o->removed)&&intval($o->UniqueID)!==$exclude&&$o->Kind!=='ABILITY'&&FaBHasType($o,'Instant'))$r[]='Stack-'.$i;return implode('&',$r);}
function FaBROSNull(int $p,int $uid): void {$f=FaBFindUID($uid);if(!$f||$f['zone']!=='Stack'||!FaBHasType($f['object'],'Instant')||intval(CardCost($f['object']->CardID))>=FaBROSCount($p,'ARCANE_OPP'))return;FaBMoveStackUID($uid,'Graveyard',intval($f['object']->Owner??$f['player'])?:$f['player']);}
function FaBROSRegrowth(int $p): string {return implode('&',FaBChoiceRefs($p,'Graveyard',['attackAction'=>true,'maxCost'=>FaBROSCount($p,'ARCANE_OPP')-1]));}
function FaBROSVaporize(int $p,bool $tokens): string {return implode('&',array_filter(array_filter(explode('&',FaBROSAllAuras($p,true,999,true))),function($r)use($p,$tokens){$o=FaBIdentityFromMZ($r)['object'];return FaBHasType($o,'Token')===$tokens&&($tokens||intval(CardCost($o->CardID))<=FaBROSCount($p,'ARCANE_OPP'));}));}
function FaBROSChainAttacks(int $minCost): string {$s=FaBGetState();$r=[];foreach(FaBLiveSeats() as $p)foreach(FaBChoiceRefs($p,'CombatChain',['attackAction'=>true]) as $ref){$o=FaBIdentityFromMZ($ref)['object'];if(intval($o->ChainLink)===intval($s['chainLink'])&&intval(CardCost($o->CardID))>=$minCost)$r[]=$ref;}return implode('&',$r);}
function FaBROSReturnLater(string $refs): void {foreach(FaBUPRUIDs($refs) as $uid)FaBARCSetCard($uid,'rosReturn',true);}
function FaBROSFaceUp(string $r): void {$f=FaBIdentityFromMZ($r);if($f&&$f['zone']==='Arsenal')$f['object']->FaceDown=0;}
function FaBROSArsenal(int $p,string $type): string {return FaBROSRefs($p,'Arsenal',$type);}
function FaBROSIntimidated(int $p): string {return implode('&',array_filter(FaBChoiceRefs($p,'Banish'),fn($r)=>!empty(FaBIdentityFromMZ($r)['object']->FaceDown)&&!empty(FaBIdentityFromMZ($r)['object']->ReturnAtEndTurn)));}
function FaBROSTenFoot(int $p): void {foreach(FaBChoiceRefs($p,'Hero') as $r){$o=FaBIdentityFromMZ($r)['object'];FaBSetObjectCounter($o,'ROS_INTELLECT',intval(FaBObjectCounters($o)['ROS_INTELLECT']??0)-2);}}
function FaBROSIntellect(int $p): int {$n=0;foreach(FaBChoiceRefs($p,'Hero') as $r)$n+=intval(FaBObjectCounters(FaBIdentityFromMZ($r)['object'])['ROS_INTELLECT']??0);return $n;}
function FaBROSFinishTurn(int $p): void {foreach(FaBChoiceRefs($p,'Hero') as $r)FaBSetObjectCounter(FaBIdentityFromMZ($r)['object'],'ROS_INTELLECT',0);}
function FaBROSTemporal(int $p): void {$r=FaBChoiceRefs($p,'Deck')[0]??'';$f=FaBIdentityFromMZ($r);if(!$f)return;$uid=intval($f['object']->UniqueID);$o=FaBMoveUID($uid,'Banish',$p);if($o&&FaBHasType($o,'Action')&&!FaBHasType($o,'Attack')){$o->PlayableFromBanish=1;FaBARCSetCard($uid,'rosTemporalTurn',intval(GetTurnNumber()));}}
function FaBROSArknight(int $p): void {$r=FaBChoiceRefs($p,'Deck')[0]??'';if(!$r)return;FaBRevealChoices($p,$r);$f=FaBIdentityFromMZ($r);if($f&&FaBWTRIsAttackAction($f['object']))FaBMoveUID(intval($f['object']->UniqueID),'Hand',$p);}
function FaBROSSetTruce(int $uid,string $r): void {$f=FaBFindUID($uid);$target=FaBIdentityFromMZ($r);if($f&&$target)FaBSetObjectCounter($f['object'],'ROS_OPP',$target['player']);}
function FaBROSAllSources(): string {$r=[];foreach(FaBLiveSeats() as $p)foreach(['Hero','Weapons','Equipment','Arena','CombatChain'] as $z)$r=array_merge($r,FaBChoiceRefs($p,$z));foreach(GetStack() as $i=>$o)if(is_object($o)&&empty($o->removed))$r[]='Stack-'.$i;return implode('&',$r);}
function FaBROSMarkSanctuary(int $uid): void {$f=FaBFindUID($uid);if($f)FaBSetObjectCounter($f['object'],'ROS_SANCTUARY',1);}
function FaBROSSlots(int $p,int $uid): string {$f=FaBFindUID($uid);$current=$f?FaBObjectCounters($f['object'])['EVO_SLOT']??'':'';$slots=[];foreach(['Head','Chest','Arms','Legs'] as $s)if($s!==$current&&!FaBChoiceRefs($p,'Equipment',['type'=>$s]))$slots[]=$s;return implode('&',$slots);}
function FaBROSSlot(int $p,int $uid,int $n): void {$slots=explode('&',FaBROSSlots($p,$uid));$f=FaBFindUID($uid);if($f&&!empty($slots[$n]))FaBEVOCounter($f['object'],'EVO_SLOT',$slots[$n]);}
function FaBROSPlan(int $p,int $v): string {if(!FaBSeatIsLive($v))return '';$uids=FaBDYNPrivateHand($p,$v);foreach(FaBChoiceRefs($v,'Arsenal') as $r){$o=FaBIdentityFromMZ($r)['object'];$temp=AddTemp($p,CardID:$o->CardID);$uids[]=intval($temp->UniqueID);}foreach(FaBChoiceRefs($v,'Hero') as $r)FaBSetObjectCounter(FaBIdentityFromMZ($r)['object'],'ROS_PLAN',1);return FaBEVRUIDRefs($uids);}
function FaBROSGrantGo(int $p,int $uid): void {if(!FaBARCCard($uid,'rosSurgeGo')&&FaBWTRMayGoAgain($p)){AddActionPoints($p,intval(GetActionPoints($p))+1);FaBROSGo($p,$uid);}FaBARCSetCard($uid,'rosSurgeGo',true);}
function FaBROSFinishBlocks(): void {$s=FaBGetState();foreach(FaBLiveSeats() as $p){$aa=false;$na=false;$face=null;foreach(FaBChoiceRefs($p,'CombatChain') as $r){$o=FaBIdentityFromMZ($r)['object'];if(intval($o->ChainLink)!==intval($s['chainLink'])||!in_array($o->Role,['DEFENSE','DEFENSE_REACTION'],true))continue;if($o->CardID==='face_purgatory')$face=$o;if(FaBWTRIsAttackAction($o))$aa=true;elseif(FaBHasType($o,'Action'))$na=true;}if($face&&$aa&&$na&&!FaBARCCard(intval($face->UniqueID),'rosFace'.$s['chainLink'])){FaBARCSetCard(intval($face->UniqueID),'rosFace'.$s['chainLink'],true);FaBROSQueue($p,'face_purgatory',intval($face->UniqueID),['rosTarget'=>intval($s['attacker'])]);}}}
function FaBROSChorus(int $p,int $uid): int {$f=FaBFindUID($uid);return $f&&(FaBHasType($f['object'],'Action')||FaBHasType($f['object'],'Instant'))&&!FaBHasType($f['object'],'Token')?FaBROSCount($p,'CHORUS'):0;}
function FaBROSStoredSource(int $p,string $key): int {foreach(FaBWTREffects($p) as $e)if(($e['type']??'')==='ROS_'.$key)return intval($e['source']??0);return 0;}
function FaBROSShelterFallback(int $p,int $n,bool $unpreventable): int {foreach(FaBROSShelters($p) as $r){if($n<=0)break;$f=FaBIdentityFromMZ($r);if(!$f)continue;FaBMONDestroy(intval($f['object']->UniqueID));if(!$unpreventable)$n=max(0,$n-1);}return $n;}
