<?php
function FaBROSAbilityRows(): array {
 $r=[];foreach(['aurora','aurora_shooting_star'] as $id)$r[$id]=[['INSTANT',2,false,false,true,0,'Create Embodiment of Lightning']];foreach(['oscilio','oscilio_constella_intelligence'] as $id)$r[$id]=[['INSTANT',0,false,false,true,0,'Discard instant to draw']];
 foreach(['aether_bindings_of_the_third_age','bruised_leather','four_finger_gloves','hood_of_second_thoughts','ink_lined_cloak','twinkle_toes','well_grounded'] as $id)$r[$id]=[['INSTANT',0,true,false,false,0,'Use equipment']];
 foreach(['calming_cloak','calming_gesture','lightning_greaves'] as $id)$r[$id]=[['INSTANT',1,true,false,false,0,'Use equipment']];
 foreach(['hold_focus','runehold_release','bloodtorn_bodice'] as $id)$r[$id]=[['ACTION',0,true,true,false,0,'Use equipment']];
 $r['staff_of_verdant_shoots']=[['ACTION',3,false,true,true,0,'Amp 1']];$r['volzar_the_lightning_rod']=[['INSTANT',1,false,false,true,0,'Amp Lightning count']];$r['sanctuary_of_aria']=[['INSTANT',2,false,false,false,0,'Prevent damage from a source']];$r['adaptive_dissolver']=[['ACTION',0,false,false,false,0,'Change equipment zone']];
 foreach(['arcane_twining','photon_splicing','chorus_of_the_amphitheater','fruits_of_the_forest','haunting_rendition','mental_block','trip_the_light_fantastic'] as $b)foreach(['red','yellow','blue'] as $c)$r[$b.'_'.$c]=[['INSTANT',0,false,false,false,0,'Discard to use instant ability']];return $r;
}
function FaBROSDiscardAbility(string $id): bool {return in_array(FaBWTRBase($id),['arcane_twining','photon_splicing','chorus_of_the_amphitheater','fruits_of_the_forest','haunting_rendition','mental_block','trip_the_light_fantastic'],true);}
function FaBROSAbilityLegal(int $p,array $f): bool {$id=$f['object']->CardID;if(FaBROSDiscardAbility($id))return $f['zone']==='Hand';if(in_array($id,['aurora','aurora_shooting_star'],true))return FaBROSCount($p,'LIGHTNING')>0;if(in_array($id,['oscilio','oscilio_constella_intelligence'],true))return FaBROSRefs($p,'Hand','Instant')!=='';if($id==='bloodtorn_bodice')return FaBROSRefs($p,'Arena','Aura')!=='';if(in_array($id,['bruised_leather','four_finger_gloves','hood_of_second_thoughts'],true))return FaBCRUCount($p,'DAMAGED')>0;if($id==='twinkle_toes')return FaBROSCount($p,'INSTANT')>0;if($id==='well_grounded')return FaBROSEarth($p)>=4;if($id==='ink_lined_cloak')return FaBROSSigils($p)!=='';return true;}
function FaBROSPaid(int $p,object $o): void {if(FaBROSDiscardAbility($o->CardID))FaBDiscardChoice($p,FaBFindUID(intval($o->UniqueID))['mzID']);}
function FaBROSPlayed(int $p,object $o,string $from): void {
 if($from==='Weapons'||!empty(FaBObjectCounters($o)['MON_ARENA_ATTACK'])){FaBROSWeaponEffects($p,$o);return;}$uid=intval($o->UniqueID);$b=FaBWTRBase($o->CardID);$action=FaBHasType($o,'Action');$instant=FaBHasType($o,'Instant');$aa=FaBWTRIsAttackAction($o);
 if(FaBHasType($o,'Lightning'))FaBROSAdd($p,'LIGHTNING');if(FaBHasType($o,'Aura')){FaBROSAdd($p,'AURA');FaBMSTClear($p,'AURA_INSTANT');FaBROSClear($p,'AURA_DISCOUNT');}
 if($action){FaBARCSetCard($uid,'rosLastLightning',FaBROSCount($p,'LAST_LIGHTNING')>0);FaBROSClear($p,'LAST_LIGHTNING');if(FaBHasType($o,'Lightning'))FaBROSAdd($p,'LAST_LIGHTNING');}
 if($instant){FaBROSAdd($p,'INSTANT');$s=FaBGetState();if(!empty($s['combatOpen'])){$attack=FaBFindUID(intval($s['attackUID']));if($attack){FaBARCSetCard(intval($attack['object']->UniqueID),'rosInstant',true);if(in_array(FaBWTRBase($attack['object']->CardID),['gone_in_a_flash','blast_to_oblivion'],true)&&!FaBARCCard(intval($attack['object']->UniqueID),'rosInstantTriggered')){FaBARCSetCard(intval($attack['object']->UniqueID),'rosInstantTriggered',true);FaBROSQueue(intval($s['attacker']),$attack['object']->CardID,intval($attack['object']->UniqueID));}}}if(FaBROSCount($p,'INSTANT_GO'))FaBWTRTag($o,'GO_AGAIN');}
 $effects=[];foreach(FaBWTREffects($p) as $e){$k=$e['type']??'';$match=$k==='ROS_NEXT_GO'&&$action||$k==='ROS_DISCHARGE'&&$aa&&intval(CardCost($o->CardID))<=intval($e['cost'])||$k==='ROS_DOMINION'&&$aa&&FaBHasType($o,'Runeblade')||$k==='ROS_RUNE_NEXT'&&FaBHasType($o,'Runeblade')&&($aa||FaBWTRIsWeapon($o))||$k==='ROS_UNSHEATHED'&&FaBHasType($o,'Sword');if(!$match){$effects[]=$e;continue;}if(in_array($k,['ROS_DISCHARGE','ROS_RUNE_NEXT','ROS_UNSHEATHED'],true))FaBWTRTag($o,'WTR_POWER:'.$e['amount']);if($k==='ROS_NEXT_GO')FaBWTRTag($o,'GO_AGAIN');if($k==='ROS_DOMINION'){FaBWTRTag($o,'OVERPOWER');FaBWTRTag($o,'ROS_AURA_GO');}if($k==='ROS_UNSHEATHED')FaBWTRTag($o,'ROS_UNSHEATHED');}FaBWTRSetEffects($p,$effects);
 if($aa)foreach(FaBMONArena($p,'malefic_incantation') as $r){$a=FaBIdentityFromMZ($r)['object'];$c=FaBObjectCounters($a);if(intval($c['ROS_VERSE_TURN']??-1)===intval(GetTurnNumber()))continue;FaBSetObjectCounter($a,'ROS_VERSE_TURN',intval(GetTurnNumber()));$n=intval($c['VERSE']??0);if($n>0){FaBSetObjectCounter($a,'VERSE',$n-1);FaBARCCreateRunes($p,1);if($n===1)FaBMONDestroy(intval($a->UniqueID));}}
 if(!$aa&&$action&&FaBROSAsInstant($p,$o)&&FaBROSCount($p,'MAGNETISM'))FaBROSClear($p,'MAGNETISM');
}
function FaBROSPower(int $p,object $o): int {$b=FaBWTRBase($o->CardID);$n=0;if(in_array($b,['strength_of_four_seasons','plow_under','felling_of_the_crown'],true)&&FaBROSEarth($p)>=4)$n+=4;if($b==='arcanic_spike'&&FaBROSCount($p,'ARCANE'))$n+=2;if(in_array($b,['rotwood_reaper','hit_the_high_notes'],true)&&FaBROSCount($p,'AURA'))$n+=2;if($b==='star_fall'&&FaBROSCount($p,'LIGHTNING'))++$n;return $n;}
function FaBROSDefense(int $p,object $o): int {if($o->CardID==='helm_of_lignum_vitae')return FaBROSEarth($p)>=4?1:0;if($o->CardID==='arcanite_fortress')return FaBROSArcanite($p)-intval(CardDefense($o->CardID));return 0;}
function FaBROSGoAgain(int $p,object $o): bool {$b=FaBWTRBase($o->CardID);return ($b==='star_fall'&&FaBROSCount($p,'LIGHTNING'))||($b==='flittering_charge'&&FaBARCCard(intval($o->UniqueID),'rosInstant'))||(($b==='runerager_swarm'||in_array('ROS_AURA_GO',(array)($o->TurnEffects??[]),true))&&FaBROSCount($p,'AURA'));}
function FaBROSAsInstant(int $p,object $o): bool {return (FaBWTRBase($o->CardID)==='succumb_to_temptation'&&FaBROSCount($p,'ARCANE'))||(FaBHasType($o,'Action')&&!FaBHasType($o,'Attack')&&FaBROSCount($p,'MAGNETISM')&& !empty(FaBGetState()['combatOpen']))||FaBARCCard(intval($o->UniqueID),'rosTemporalTurn',-1)===intval(GetTurnNumber());}
function FaBROSCost(int $p,object $o): int {return FaBHasType($o,'Aura')?-2*FaBROSCount($p,'AURA_DISCOUNT'):0;}
function FaBROSCanPlay(int $p,object $o): bool {return $o->CardID!=='seeds_of_tomorrow_blue'||count(FaBChoiceRefs($p,'Arsenal'))>0;}
function FaBROSDeclared(int $p,object $o): void {if(in_array('ROS_UNSHEATHED',(array)($o->TurnEffects??[]),true)&&FaBAttackPower(FaBGetState())>2*intval(CardPower($o->CardID)))FaBWTRTag($o,'GO_AGAIN');$s=FaBGetState();foreach(FaBLiveSeats() as $v)foreach(FaBMONArena($v,'truce') as $r){$a=FaBIdentityFromMZ($r)['object'];if(intval(FaBObjectCounters($a)['ROS_OPP']??0)===$p&&in_array($v,FaBMSTAttackVictims(),true)){FaBMONDestroy(intval($a->UniqueID));DoDrawCard($v,1);}}}
function FaBROSHit(int $p,object $o): void {if(!FaBFaiHeroHit())return;$v=intval(FaBGetState()['defender']);if(FaBROSCount($p,'BURN')){FaBROSQueue($p,'burn_up_shock_red',FaBROSStoredSource($p,'BURN'),['rosEvent'=>'hit','rosTarget'=>$v]);FaBROSClear($p,'BURN');}if(FaBHasType($o,'Runeblade')&&FaBWTRIsAttackAction($o)&&FaBROSCount($p,'TEMPTATION')){FaBROSClear($p,'TEMPTATION');FaBROSQueue($p,'succumb_to_temptation_yellow',intval($o->UniqueID),['rosTarget'=>$v]);}}
function FaBROSGo(int $p,int $source=0): void {if(FaBROSCount($p,'ARC_LIGHTNING'))for($i=0;$i<FaBROSCount($p,'ARC_LIGHTNING');++$i)FaBROSQueue($p,'arc_lightning_yellow',FaBROSStoredSource($p,'ARC_LIGHTNING'));}
function FaBROSChainEnd(): void {foreach(FaBLiveSeats() as $p){foreach(FaBChoiceRefs($p,'CombatChain') as $r){$o=FaBIdentityFromMZ($r)['object'];if(FaBARCCard(intval($o->UniqueID),'rosReturn')){FaBARCSetCard(intval($o->UniqueID),'rosReturn',false);FaBROSReturn($r);}}FaBROSClear($p,'MAGNETISM');}}
function FaBROSStart(int $p): void {foreach(FaBChoiceRefs($p,'Arena') as $r){$o=FaBIdentityFromMZ($r)['object'];$b=FaBWTRBase($o->CardID);if($b==='channel_the_millennium_tree')FaBMSTAdd($p,'AMP',3);if(in_array($b,['harvest_season','strong_yield','sigil_of_aether','sigil_of_brilliance','sigil_of_cycles','sigil_of_deadwood','sigil_of_earth','sigil_of_forethought','sigil_of_fyendal','sigil_of_lightning','sigil_of_temporal_manipulation','sigil_of_the_arknight'],true)){FaBMONDestroy(intval($o->UniqueID));if($b==='harvest_season')FaBCRUGainLife($p,4-intval(CardPitch($o->CardID)));if($b==='strong_yield')FaBMSTNext($p,4-intval(CardPitch($o->CardID)),'');}}}
function FaBROSEnd(int $p): void {foreach(FaBMONArena($p,'earths_embrace') as $r){FaBWTRCreateArena($p,'embodiment_of_earth');if(!FaBROSCount($p,'EARTH_BANISHED'))FaBMONDestroy(intval(FaBIdentityFromMZ($r)['object']->UniqueID));}foreach(FaBLiveSeats() as $v){foreach(FaBMONArena($v,'truce') as $r){$o=FaBIdentityFromMZ($r)['object'];if(intval(FaBObjectCounters($o)['ROS_OPP']??0)===$p){FaBMONDestroy(intval($o->UniqueID));FaBCRUGainLife($p,3);FaBCRUGainLife($v,3);}}foreach(FaBChoiceRefs($v,'Hero') as $r){$o=FaBIdentityFromMZ($r)['object'];if($v===$p&&!empty(FaBObjectCounters($o)['ROS_PLAN'])){FaBSetObjectCounter($o,'ROS_PLAN',0);foreach(FaBChoiceRefs($p,'Hand') as $h)FaBDiscardChoice($p,$h);foreach(FaBUPRUIDs(implode('&',FaBChoiceRefs($p,'Arsenal'))) as $u)FaBMONDestroy($u);}}foreach(FaBMONArena($v,'sanctuary_of_aria') as $r)if(!empty(FaBObjectCounters(FaBIdentityFromMZ($r)['object'])['ROS_SANCTUARY']))FaBMONDestroy(intval(FaBIdentityFromMZ($r)['object']->UniqueID));}}
function FaBROSWeaponEffects(int $p,object $o): void {$effects=[];foreach(FaBWTREffects($p) as $e){$k=$e['type']??'';if($k==='ROS_RUNE_NEXT'&&FaBHasType($o,'Runeblade')||$k==='ROS_UNSHEATHED'&&FaBHasType($o,'Sword')){FaBWTRTag($o,'WTR_POWER:'.$e['amount']);if($k==='ROS_UNSHEATHED')FaBWTRTag($o,'ROS_UNSHEATHED');}else $effects[]=$e;}FaBWTRSetEffects($p,$effects);}
