<?php
// Generates SWUSim/Rl/CardTags.generated.php — coarse effect tags read from each card's printed text, for
// the heuristic bot's scoring (layer 4) and the RL move keys (RL bots spec, Section 3 "Card tags").
// Re-run after any card-data regeneration:
//   docker exec -w /var/www/html/TCGEngine otmtcge-swusim-web-server-1 php -d xdebug.mode=off SWUSim/DevTools/rl/tag_cards.php
//
// Tags are COARSE on purpose. A wrong tag only weakens cross-deck transfer (the archetype layers correct
// it), so the patterns favour precision on the common phrasings over completeness. The owner reviews the
// output (spec Section 3); the run prints per-tag counts and samples to make that review quick.

chdir(dirname(__DIR__, 3));
require_once './SWUSim/GeneratedCode/GeneratedCardDictionaries.php';
global $textData;

// Order matters only for `wipe`: its matched clause is REMOVED before `damage` is tested, so "deal 5 damage to
// each unit" is a wipe and not also targeted damage — while "each ENEMY unit" never matches `wipe` at all.
const SWU_BOT_TAG_PATTERNS = [
    'wipe'    => '/(deal \d+ damage to each (unit|ground unit|space unit|non-leader unit)|defeat (each|all) (space |ground |non-leader )?units|defeat any number of (non-leader )?units)/i',
    // "Defeat another FRIENDLY unit" is a sacrifice, not removal (TWI_035, ASH_103) — excluded; same for exhaust.
    // Tags v2 (2026-09-14): also "take control … then defeat it", "-N/-N" on one unit (not "-N/-0"), the Tree
    // Remembers' conditional defeat, and Chimaera's "an enemy non-leader unit. If you do, defeat those units."
    'removal' => '/(\bdefeat (a|an|another|up to \d+|that) (?![^.]*?\bfriendly\b)[^.]*?\bunit|take control of (a|an) [^.]*?unit, then defeat it|give (a|an|another) (non-leader |enemy )?unit -\d+\/-[1-9]\d*|loses all abilities for this phase\. if it costs \d+ or less, defeat it|enemy (non-leader )?unit\. if you do, defeat those units)/i',
    'damage'  => '/(deal \d+ damage to (a|an|another|each enemy|each|up to)[^.]*?\b(unit|base)|deal damage (equal to|divided)[^.]*?\b(unit|units|base)|give each enemy unit[^.]*?-\d+\/-[1-9]\d*)/i',
    // Tags v2: indirect or base damage from a card — the reach burn decks win with.
    'burn'    => '/(indirect damage|deal \d+ damage to (a|an|each|that|each enemy|an opponent\'s|each opponent\'s) base)/i',
    'draw'    => '/\bdraw (a|\d+|two|three) cards?\b/i',
    'heal'    => '/\bheal \d+ damage\b/i',
    // A buff is an effect that GRANTS stats or a stat token to a unit — not a unit's own conditional stat
    // line ("this unit gets +2/+0 while…"), which is part of the body, not something playing it does.
    'buff'    => '/(give [^.]*?\+\d+\/\+\d+|gets? \+\d+\/\+\d+ for this (phase|attack|round)|give [^.]*?(experience|shield|advantage) tokens?)/i',
    'bounce'  => '/return [^.]*? to (its|their) owner\'?s hand/i',
    'exhaust' => '/\bexhaust (a|an|another|each|up to \d+|that) (?![^.]*?\bfriendly\b)[^.]*?\bunit/i',
];

function SWUBotTagText(string $text): array {
    $tags = [];
    // Drop parenthesised REMINDER text first. Keyword reminders describe the keyword, not the card's effect:
    // "Shielded (…give a Shield token to him.)", "Raid 1 (This unit gets +1/+0 while attacking.)",
    // "Restore 2 (…heal 2 damage from your base.)" would otherwise tag every such unit buff / heal.
    // Measured before this: `buff` hit 605 cards.
    $rest = preg_replace('/\([^)]*\)/', '', $text);
    if (preg_match(SWU_BOT_TAG_PATTERNS['wipe'], $rest)) {
        $tags[] = 'wipe';
        $rest = preg_replace(SWU_BOT_TAG_PATTERNS['wipe'], '', $rest);
    }
    foreach (SWU_BOT_TAG_PATTERNS as $tag => $re) {
        if ($tag === 'wipe') continue;
        if (preg_match($re, $rest)) $tags[] = $tag;
    }
    return $tags;
}

$table = [];
foreach ($textData as $cardID => $text) {
    $tags = SWUBotTagText(strval($text));
    if (!empty($tags)) $table[strval($cardID)] = $tags;
}
ksort($table, SORT_STRING);

$out = "<?php\n// GENERATED by SWUSim/DevTools/rl/tag_cards.php — do not edit by hand; re-run the generator.\n"
     . "// Coarse effect tags per CardID (removal, damage, draw, buff, bounce, exhaust, heal, wipe, burn).\n"
     . "\$GLOBALS['SWUBotCardTagTable'] = [\n";
foreach ($table as $id => $tags) {
    $out .= '    ' . var_export($id, true) . ' => [' . implode(', ', array_map(fn($t) => var_export($t, true), $tags)) . "],\n";
}
$out .= "];\n";
@mkdir('./SWUSim/Rl', 0775, true);
file_put_contents('./SWUSim/Rl/CardTags.generated.php', $out);

// Review aid: counts and samples per tag.
$counts = [];
foreach ($table as $id => $tags) foreach ($tags as $t) $counts[$t][] = $id;
ksort($counts);
echo 'Tagged ' . count($table) . " of " . count($textData) . " cards.\n";
foreach ($counts as $t => $ids) {
    echo sprintf("  %-8s %5d  e.g. %s\n", $t, count($ids), implode(' ', array_slice($ids, 0, 10)));
}
