<?php
echo("var myStatic = '';");
echo("var theirStatic = '';");
echo("var myRows = [];");
echo("var theirRows = [];");
echo("window.rootPath = './GrandArchiveDB';");
echo("window.myCardPanePanes = [];");
echo("window.theirCardPanePanes = [];");
echo("for(var i=0; i<1; ++i) { myRows[i] = \"\"; theirRows[i] = \"\"; }");
echo("window.myCommanderData = responseArr[1];");
echo("window.theirCommanderData = responseArr[13];");
echo("window.myReserveDeckData = responseArr[2];");
echo("window.theirReserveDeckData = responseArr[14];");
echo("window.myMainDeckData = responseArr[3];");
echo("window.theirMainDeckData = responseArr[15];");
echo("window.myCardPaneData = responseArr[4];");
echo("window.theirCardPaneData = responseArr[16];");
echo("window.myNumReserveData = responseArr[8];");
echo("window.theirNumReserveData = responseArr[20];");
echo("window.myCountsDisplayData = responseArr[9];");
echo("window.theirCountsDisplayData = responseArr[21];");
echo("window.mySortData = responseArr[10];");
echo("window.theirSortData = responseArr[22];");
echo("window.myCardNotesData = responseArr[11];");
echo("window.theirCardNotesData = responseArr[23];");
echo("window.myVersionsData = responseArr[12];");
echo("window.theirVersionsData = responseArr[24];");
echo("myStatic += '<div id=\\'myCommanderWrapper\\' onclick=\"ZoneClickHandler(\\'myCommander\\');\"  style=\"position: absolute; left:31%; top:40px; overflow-y:auto;\">' + PopulateZone('myCommander', responseArr[1], cardSize, './GrandArchiveDB/concat', '0', 'All') + '</div>';");
echo("myStatic += '<div id=\\'myReserveDeckWrapper\\' onclick=\"ZoneClickHandler(\\'myReserveDeck\\');\"  style=\"position: absolute; left:31%; top:82%; overflow-y:auto;\">' + PopulateZone('myReserveDeck', responseArr[2], cardSize, './GrandArchiveDB/concat', '0', 'Tile') + '</div>';");
echo("myStatic += '<div id=\\'myMainDeckWrapper\\' onclick=\"ZoneClickHandler(\\'myMainDeck\\');\"  style=\"position: absolute; left:31%; top:23%; overflow-y:auto;\">' + PopulateZone('myMainDeck', responseArr[3], cardSize, './GrandArchiveDB/concat', '0', 'Tile') + '</div>';");
echo("myStatic += '<div id=\\'myCardPaneWrapper\\' onclick=\"ZoneClickHandler(\\'myCardPane\\');\" onscroll=\"ZoneScrollHandler(\\'myCardPane\\');\" style=\"position: absolute; left:10px; top:10px; bottom:10px; width:30%; overflow-y:auto;\">' + PopulateZone('myCardPane', responseArr[4], cardSize, './GrandArchiveDB/concat', '0', 'Panel') + '</div>';");
echo("myCardPanePanes.push(responseArr[5]);");
echo("myCardPanePanes.push(responseArr[6]);");
echo("myCardPanePanes.push(responseArr[7]);");
echo("myStatic += '<div id=\\'myNumReserveWrapper\\' onclick=\"ZoneClickHandler(\\'myNumReserve\\');\"  style=\"position: absolute; left:31%; top:79%; overflow-y:auto;\">' + PopulateZone('myNumReserve', responseArr[8], cardSize, './GrandArchiveDB/concat', '0', 'Calculate') + '</div>';");
echo("myStatic += '<div id=\\'myCountsDisplayWrapper\\' onclick=\"ZoneClickHandler(\\'myCountsDisplay\\');\"  style=\"position: absolute; left:31%; top:10px; overflow-y:auto;\">' + PopulateZone('myCountsDisplay', responseArr[9], cardSize, './GrandArchiveDB/concat', '0', 'Calculate') + '</div>';");
echo("myStatic += '<div id=\\'mySortWrapper\\' onclick=\"ZoneClickHandler(\\'mySort\\');\"  style=\"position: absolute; left:63%; top:16%; overflow-y:auto;\">' + PopulateZone('mySort', responseArr[10], cardSize, './GrandArchiveDB/concat', '0', 'Radio') + '</div>';");
echo("theirStatic += '<div id=\\'theirCommanderWrapper\\' onclick=\"ZoneClickHandler(\\'theirCommander\\');\"  style=\"position: absolute; left:31%; bottom:40px; overflow-y:auto;\">' + PopulateZone('theirCommander', responseArr[13], cardSize, './GrandArchiveDB/concat', '0', 'All') + '</div>';");
echo("theirStatic += '<div id=\\'theirReserveDeckWrapper\\' onclick=\"ZoneClickHandler(\\'theirReserveDeck\\');\"  style=\"position: absolute; left:31%; bottom:82%; overflow-y:auto;\">' + PopulateZone('theirReserveDeck', responseArr[14], cardSize, './GrandArchiveDB/concat', '0', 'Tile') + '</div>';");
echo("theirStatic += '<div id=\\'theirMainDeckWrapper\\' onclick=\"ZoneClickHandler(\\'theirMainDeck\\');\"  style=\"position: absolute; left:31%; bottom:23%; overflow-y:auto;\">' + PopulateZone('theirMainDeck', responseArr[15], cardSize, './GrandArchiveDB/concat', '0', 'Tile') + '</div>';");
echo("theirStatic += '<div id=\\'theirCardPaneWrapper\\' onclick=\"ZoneClickHandler(\\'theirCardPane\\');\" onscroll=\"ZoneScrollHandler(\\'theirCardPane\\');\" style=\"position: absolute; left:10px; bottom:10px; top:10px; width:30%; overflow-y:auto;\">' + PopulateZone('theirCardPane', responseArr[16], cardSize, './GrandArchiveDB/concat', '0', 'Panel') + '</div>';");
echo("theirCardPanePanes.push(responseArr[17]);");
echo("theirCardPanePanes.push(responseArr[18]);");
echo("theirCardPanePanes.push(responseArr[19]);");
echo("theirStatic += '<div id=\\'theirNumReserveWrapper\\' onclick=\"ZoneClickHandler(\\'theirNumReserve\\');\"  style=\"position: absolute; left:31%; bottom:79%; overflow-y:auto;\">' + PopulateZone('theirNumReserve', responseArr[20], cardSize, './GrandArchiveDB/concat', '0', 'Calculate') + '</div>';");
echo("theirStatic += '<div id=\\'theirCountsDisplayWrapper\\' onclick=\"ZoneClickHandler(\\'theirCountsDisplay\\');\"  style=\"position: absolute; left:31%; bottom:10px; overflow-y:auto;\">' + PopulateZone('theirCountsDisplay', responseArr[21], cardSize, './GrandArchiveDB/concat', '0', 'Calculate') + '</div>';");
echo("theirStatic += '<div id=\\'theirSortWrapper\\' onclick=\"ZoneClickHandler(\\'theirSort\\');\"  style=\"position: absolute; left:63%; bottom:16%; overflow-y:auto;\">' + PopulateZone('theirSort', responseArr[22], cardSize, './GrandArchiveDB/concat', '0', 'Radio') + '</div>';");
echo("RenderRows(myRows, theirRows);");
echo("AppendStaticZones(myStatic, theirStatic);");
echo("RenderPanes('CardPane', window.myCardPanePanes, window.theirCardPanePanes);");

?>