#!/usr/bin/env bash
#
# harden-htaccess.sh - (re)write the docroot .htaccess declaratively.
#
# Every run OVERWRITES /opt/lampp/htdocs/.htaccess with the full rule set built from
# the config below, so this script is the single source of truth for docroot routing.
# To add/adjust an app, edit the APP_DOMAINS table and re-run — no hand-editing the
# .htaccess (it is regenerated and any manual edits are lost; a backup is kept).
#
# The generated .htaccess does four things:
#   1. Force HTTPS.
#   2. Per-domain: redirect the domain root (/ or /index.php) to that app's main menu.
#   3. Redirect bare app-dir URLs (/TCGEngine, /TCGEngine/SharedUI/) to the active
#      site's main menu, so they never 403 or show a listing.
#   4. Options -Indexes: never expose an Apache directory listing of the filesystem.
#
# Assumes: XAMPP at /opt/lampp, docroot /opt/lampp/htdocs, AllowOverride All (XAMPP
# default) so .htaccess Options/RewriteRule are honored. Run as root.
#
# Usage:
#   sudo ./harden-htaccess.sh          # (re)write the .htaccess
#   sudo ./harden-htaccess.sh --yes
#
set -euo pipefail

# ─── Config: one line per live app/domain — "<domain>|<target main-menu URL>" ───
# <domain> is matched with an optional "www." prefix (dots are escaped for you).
# <target> is the exact redirect Location. Use %{HTTP_HOST} to keep the requested
# host, or a literal host to force one (e.g. to canonicalize to www).
APP_DOMAINS=(
  "soulmastersdb.net|https://%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php"                # SoulMastersDB
  "clarent.net|https://%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php"                      # GrandArchiveSim
  "swustats.net|https://%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php"                     # SWUDeck
  "zendo.gg|https://%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php"                         # AzukiSim
  "petranaki.net|https://%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php"                    # SWUSim
  # Add a line per live app as new domains come online (e.g. SWUSim once it has one).
)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LAMPP_ROOT="${LAMPP_ROOT:-/opt/lampp}"
HTDOCS="${HTDOCS:-$LAMPP_ROOT/htdocs}"
HTACCESS="${HTACCESS:-$HTDOCS/.htaccess}"

ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    --yes|-y)  ASSUME_YES=1 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//' | sed '/^!/d'; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$SCRIPT_DIR/newhost-backups-$TS"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ok\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m  !!\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

backup() {
  local f="$1"; [ -f "$f" ] || return 0
  mkdir -p "$BACKUP_DIR"
  cp -p "$f" "$BACKUP_DIR/$(echo "$f" | sed 's#^/##; s#/#_#g')"
  ok "backed up existing .htaccess -> $BACKUP_DIR"
}

# --------------------------------------------------------------------------- #
[ "$(id -u)" -eq 0 ] || die "must run as root (sudo)."
[ -d "$HTDOCS" ] || die "docroot not found at $HTDOCS."
log "Rewriting $HTACCESS from ${#APP_DOMAINS[@]} app domain(s)  (backups -> $BACKUP_DIR)"

backup "$HTACCESS"

# Build the file into a temp, then move into place atomically.
tmp="$(mktemp)"
{
  echo "# GENERATED by newhost/harden-htaccess.sh — do not edit by hand."
  echo "# Edit the APP_DOMAINS table in that script and re-run; this file is overwritten."
  echo
  echo "<IfModule mod_rewrite.c>"
  echo "    RewriteEngine On"
  echo
  echo "    # 1. Force HTTPS."
  echo "    RewriteCond %{HTTPS} !=on"
  echo "    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]"
  echo
  echo "    # 2. Per-domain: root (/ or /index.php) -> that app's main menu."
  for entry in "${APP_DOMAINS[@]}"; do
    domain="${entry%%|*}"
    target="${entry#*|}"
    [ -n "$domain" ] && [ "$domain" != "$target" ] || die "bad APP_DOMAINS entry: '$entry' (expected '<domain>|<target>')."
    esc="$(printf '%s' "$domain" | sed 's/\./\\./g')"
    printf '    RewriteCond %%{HTTP_HOST} ^(www\\.)?%s$ [NC]\n' "$esc"
    printf '    RewriteCond %%{REQUEST_URI} ^/?$ [OR]\n'
    printf '    RewriteCond %%{REQUEST_URI} ^/index\\.php$ [NC]\n'
    printf '    RewriteRule ^ %s [L,R=302]\n\n' "$target"
  done
  echo "    # 3. Bare app-dir URLs -> the active site's main menu (never a 403/listing)."
  printf '    RewriteRule ^TCGEngine/?$          https://%%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php [L,R=302]\n'
  printf '    RewriteRule ^TCGEngine/SharedUI/?$ https://%%{HTTP_HOST}/TCGEngine/SharedUI/MainMenu.php [L,R=302]\n'
  echo
  echo "    # 3b. swustats.net friendly deck links: /deck/{12-letter code} -> resolver."
  printf '    RewriteCond %%{HTTP_HOST} ^(www\\.)?swustats\\.net$ [NC]\n'
  printf '    RewriteRule ^deck/([A-Za-z]{12})/?$ TCGEngine/APIs/GoToDeck.php?code=$1 [L,QSA]\n'
  echo "</IfModule>"
  echo
  echo "# 4. Never expose an Apache directory listing of the filesystem."
  echo "Options -Indexes"
} > "$tmp"

mv "$tmp" "$HTACCESS"
chmod 0644 "$HTACCESS"
ok "wrote $HTACCESS ($(wc -l < "$HTACCESS") lines, ${#APP_DOMAINS[@]} domain rule(s))"

echo
echo "Apply with:  $LAMPP_ROOT/lampp reload    (or: $LAMPP_ROOT/lampp restartapache)"
echo "Verify:      curl -sI https://YOURHOST/TCGEngine/SharedUI/   # expect 302 -> MainMenu.php"
echo "             curl -sI https://YOURHOST/TCGEngine/SomeDir/     # expect 403, not a listing"
