<?php
// Traits the upstream card API OMITS, supplied from tracked source.
//
// The API publishes no traits for bases (every one comes back empty) though each prints one —
// JTL_030 Mos Eisley is "Tatooine", SOR_024 Echo Base is "Hoth". Applied at generation time by
// SWUSim/DevTools/TraitSupplement.php, FILL-GAPS ONLY: official data always wins, so this file
// goes inert on its own if the API ever starts publishing them.
//
// Generated/extended by: php SWUSim/DevTools/backfill-base-traits.php [--dry]
// Hand-editing is fine — the backfill preserves entries it can't improve.
// SCAFFOLD-IGNORE: pure DATA, not a card implementation. Tools that infer "is this card
// implemented?" by grepping quoted CardIDs under SWUSim/Custom/ must skip this file, or every
// card listed here looks implemented and gets no stub / is dropped from gap reports.
return array (
  'ASH_019' => 'Peridea',
  'ASH_020' => 'Nevarro',
  'ASH_021' => 'Death Star',
  'ASH_022' => 'Kalevala',
  'ASH_023' => 'Seatos',
  'ASH_024' => 'Dagobah',
  'ASH_025' => 'Pillio',
  'ASH_026' => 'Tatooine',
  'IBH_002' => 'Hoth',
  'IBH_054' => 'Hoth',
  'JTL_019' => 'Cloud City',
  'JTL_020' => 'Endor',
  'JTL_021' => 'Castilon',
  'JTL_022' => 'D\'Qar',
  'JTL_023' => 'Naboo',
  'JTL_024' => 'Scarif',
  'JTL_025' => 'Starkiller Base',
  'JTL_026' => 'Yavin 4',
  'JTL_027' => 'Nadiri',
  'JTL_028' => 'Ryloth',
  'JTL_029' => 'Atollon',
  'JTL_030' => 'Tatooine',
  'JTL_031' => 'Naboo',
  'LAW_019' => 'Lowick',
  'LAW_020' => 'Tatooine',
  'LAW_021' => 'Kessel',
  'LAW_022' => 'Aldhani',
  'LAW_023' => 'Tatooine',
  'LAW_024' => 'Lothal',
  'LAW_025' => 'Quarzite',
  'LAW_026' => 'Bracca',
  'LAW_027' => 'Stygeon Prime',
  'LAW_028' => 'Cantonica',
  'LAW_029' => 'Scarif',
  'LAW_030' => 'Segra Milo',
  'LOF_019' => 'Lothal',
  'LOF_020' => 'Dathomir',
  'LOF_021' => 'Coruscant',
  'LOF_022' => 'Mortis',
  'LOF_023' => 'Coruscant',
  'LOF_024' => 'Starlight Beacon',
  'LOF_025' => 'Malachor',
  'LOF_026' => 'Mustafar',
  'LOF_027' => 'Dathomir',
  'LOF_028' => 'Zeffo',
  'LOF_029' => 'Ilum',
  'LOF_030' => 'Jedha',
  'SEC_019' => 'Ferrix',
  'SEC_020' => 'Coruscant',
  'SEC_021' => 'Hosnian Prime',
  'SEC_022' => 'Coruscant',
  'SEC_023' => 'Narkina 5',
  'SEC_024' => 'Coruscant',
  'SEC_025' => 'Coruscant',
  'SEC_026' => 'Wayland',
  'SHD_019' => 'Nevarro',
  'SHD_020' => 'Sorgan',
  'SHD_021' => 'Takodana',
  'SHD_022' => 'Nevarro',
  'SHD_023' => 'Concordia',
  'SHD_024' => 'Kessel',
  'SHD_025' => 'Corellia',
  'SHD_026' => 'Tatooine',
  'SOR_019' => 'Scarif',
  'SOR_020' => 'Lothal',
  'SOR_021' => 'Dagobah',
  'SOR_022' => 'Eadu',
  'SOR_023' => 'Death Star',
  'SOR_024' => 'Hoth',
  'SOR_025' => 'Lothal',
  'SOR_026' => 'Jedha',
  'SOR_027' => 'Vardos',
  'SOR_028' => 'Jedha',
  'SOR_029' => 'Cloud City',
  'SOR_030' => 'Atollon',
  'TS26_09' => 'Coruscant',
  'TS26_10' => 'Serenno',
  'TS26_11' => 'Geonosis',
  'TS26_12' => 'Mandalore',
  'TWI_019' => 'Utapau',
  'TWI_020' => 'Mandalore',
  'TWI_021' => 'Cristophsis',
  'TWI_022' => 'Geonosis',
  'TWI_023' => 'Vassek',
  'TWI_024' => 'Kamino',
  'TWI_025' => 'Zanbar',
  'TWI_026' => 'Mustafar',
  'TWI_027' => 'Onderon',
  'TWI_028' => 'Geonosis',
  'TWI_029' => 'Coruscant',
  'TWI_030' => 'Oba Diah',
);
