<?php
/** Authoring source for relicanth v2 - draw; saved and regenerated by setup. */
$cards=[];
$ability=static fn($macro,$name,$code,$prereq='')=>['macroName'=>$macro,'abilityName'=>$name,'abilityCode'=>$code,'prereqCode'=>$prereq,'isImplemented'=>true];
$cards['me01-125'][]=$ability('TrainerPlayed','Rare Candy', <<<'CODE'
$targets = PokeRareCandyTargets($player);
$target = await $player.MZChoose($targets, 'Rare_Candy:_choose_a_Basic');
$evolutions = PokeRareCandyEvolutions($player, $target);
$chosen = await $player.MZChoose($evolutions, 'Rare_Candy:_choose_a_Stage_2');
if (PokeRareCandyEligible($player, GetZoneObject($chosen)->CardID, GetZoneObject($target))) {
    PokeEvolve($player, $chosen, $target);
}
CODE, 'return PokeRareCandyTargets($player) !== "";');
$cards['me05-062'][]=$ability('BenchDamageProtection','Ancient Bulwark','return PokeAncientBulwark($player, $sourceObj);');
$cards['sv07-139'][]=$ability('TrainerPlayed','Lacey','PokeShuffleHandDraw($player, PokeCount(3 - $player, "Prizes") <= 3 ? 8 : 4);');
$cards['me02.5-190'][]=$ability('TrainerPlayed',"Iris's Fighting Spirit", <<<'CODE'
$targets = PokeCandidates($player, 'Hand');
$discard = await $player.MZChoose($targets, 'Iris:_discard_one_card');
PokeDiscardSelection($player, $discard);
PokeDraw($player, max(0, 6 - PokeCount($player, 'Hand')), false);
CODE, 'return PokeCount($player, "Hand") >= (GetZoneObject($mzID)->Location === "Hand" ? 2 : 1);');
$cards['me03-076'][]=$ability('TrainerPlayed','Judge','PokeShuffleHandDraw($player, 4); PokeShuffleHandDraw(3 - $player, 4);');
$cards['sv06-158'][]=$ability('TrainerPlayed','Lucky Helmet', <<<'CODE'
$targets = PokeToolTargets($player);
$chosen = await $player.MZChoose($targets, 'Lucky_Helmet:_attach_to_a_Pokémon');
PokeAttachTool($player, $mzID, $chosen);
CODE, 'return PokeToolTargets($player) !== "";');
$cards['sv06-158'][]=$ability('AttackDamageDraw','Lucky Helmet','return $subjectObj->Location === "Active" && $subjectObj->Controller !== $sourceObj->Controller ? 2 : 0;');
$cards['sv06-167'][]=$ability('EnergyAttached','Legacy Energy','return;');
$cards['sv06-167'][]=$ability('ProvidesAllEnergyTypes','Legacy Energy','return 1;');
$cards['sv06-167'][]=$ability('KnockoutPrizeModifier','Legacy Energy', <<<'CODE'
if (empty($subjectObj->Counters['opposingAttackKO']) || PokeVar('legacyEnergyUsed:' . $subjectObj->Controller, false)) return 0;
PokeSetVar('legacyEnergyUsed:' . $subjectObj->Controller, true);
return -1;
CODE);
return $cards;
