<?php
// Auto-generated by zzTurnGenerator.php
// Generated turn states and transitions

$turnStates = array();
$turnStates = array(
  'SETUP_LOCATION' => array(
    'Title' => 'ChooseLocations',
    'Code' => 'HellbreakSetupLocationPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'SETUP_LOCATION'),
      array('Input' => 'READY', 'Target' => 'SETUP_MULLIGAN'),
    ),
  ),
  'SETUP_MULLIGAN' => array(
    'Title' => 'Mulligan',
    'Code' => 'HellbreakSetupMulliganPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'SETUP_MULLIGAN'),
      array('Input' => 'READY', 'Target' => 'FEED_COLLECT'),
    ),
  ),
  'FEED_COLLECT' => array(
    'Title' => 'CollectResources',
    'Code' => 'HellbreakFeedingCollectPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'FEED_BID'),
    ),
  ),
  'FEED_BID' => array(
    'Title' => 'BidForInitiative',
    'Code' => 'HellbreakFeedingBidPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'FEED_BID'),
      array('Input' => 'READY', 'Target' => 'FEED_RESOLVE'),
    ),
  ),
  'FEED_RESOLVE' => array(
    'Title' => 'ResolveInitiative',
    'Code' => 'HellbreakFeedingResolvePhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'HORROR'),
    ),
  ),
  'HORROR' => array(
    'Title' => 'Horror',
    'Code' => 'HellbreakHorrorPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'HORROR'),
      array('Input' => 'PASS', 'Target' => 'REFRESH_READY'),
    ),
  ),
  'REFRESH_READY' => array(
    'Title' => 'ReadyCards',
    'Code' => 'HellbreakRefreshReadyPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'REFRESH_FLIP'),
    ),
  ),
  'REFRESH_FLIP' => array(
    'Title' => 'FlipMonsters',
    'Code' => 'HellbreakRefreshFlipPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'REFRESH_FLIP'),
      array('Input' => 'READY', 'Target' => 'REFRESH_HAND'),
    ),
  ),
  'REFRESH_HAND' => array(
    'Title' => 'CheckHandLimit',
    'Code' => 'HellbreakRefreshHandPhase',
    'Transitions' => array(
      array('Input' => 'AUTO', 'Target' => 'REFRESH_HAND'),
      array('Input' => 'READY', 'Target' => 'FEED_COLLECT'),
    ),
  ),
);

