<?php
require_once __DIR__.'/dyn_rules_test.php';
require_once __DIR__.'/../../FaBSim/BotDeck.php';
$failures=[];$deck=FaBBotDeck('arakni');
$check(count($deck['mainDeck'])===40&&!FaBUPFDeckErrors($deck),'Arakni deck is not legal.');
$check(FaBNormalizeDeckPayload(json_decode(file_get_contents(__DIR__.'/arakni_source.json'),true))===$deck,'Arakni deck differs from Fabrary source.');
$covered=[];foreach(glob(__DIR__.'/*_abilities.json') as $file)foreach(json_decode(file_get_contents($file),true) as $c)$covered[$c['cardId']]=true;
foreach(array_merge([$deck['hero']],$deck['weapons'],$deck['equipment'],$deck['mainDeck']) as $id)$check(isset($covered[$id]),'Unimplemented deck card '.$id);
foreach([2,4] as $p){
 $dynReset($p);$s=FaBGetState();$s['botProfiles']=[$p=>'arakni'];FaBSetState($s);$a=$attack($p,'annihilate_the_armed_red');FaBArakniAttack($p,$a);
 $h=AddArsenal($p,CardID:'the_hand_that_pulls_the_strings',FaceDown:1);$check(FaBWTRCanActivate($p,$ref($h)),'Face-down Strings cannot activate.');
 FaBWTRActivate($p,$ref($h));$top=FaBStackTop();if($top)DoResolveCard($p,$ref($top));$check(!intval($h->FaceDown)&&FaBAttackHasGoAgain(FaBGetState(),$a),'Strings did not give first contract go again after flipping.');
 AddEquipment(1,CardID:'crown_of_dominion',Owner:1,Controller:1);$check(FaBDYNPower($p,$a)===1,'Strings did not boost the first contract against Royal.');
 $b=$attack($p,'plunder_the_poor_red');FaBArakniAttack($p,$b);$check(!FaBAttackHasGoAgain(FaBGetState(),$b),'Strings gave a second contract go again.');
 FaBWTRCreateArena($p,'silver');FaBArakniEnd($p);$answer($p,GetDecisionQueue($p)[0]->Param);$check(FaBFindUID($h->UniqueID)['zone']==='Arsenal'&&!FaBMONArena($p,'silver'),'Strings did not consume Silver upkeep.');
 AddDeck($p,CardID:'shred_blue');FaBArakniEnd($p);$check(FaBFindUID($h->UniqueID)['zone']==='Deck'&&FaBHandCount($p)===1,'Unpaid Strings did not bottom and draw.');
 $dynReset($p);$a=$attack($p,'annihilate_the_armed_red');$e=AddEquipment($p,CardID:'starting_point',Owner:$p,Controller:$p);$check(!FaBWTRCanActivate($p,$ref($e)),'Starting Point legal before a prior reaction-step action.');FaBArakniReactionEvent($p,false);$check(FaBWTRCanActivate($p,$ref($e)),'Starting Point still illegal after a reaction-step action.');FaBWTRActivate($p,$ref($e));DoResolveCard($p,$ref(FaBStackTop()));$answer($p,$ref($a));$check(FaBAttackHasGoAgain(FaBGetState(),$a)&&FaBFindUID($e->UniqueID)['zone']==='Graveyard','Starting Point did not pay cost or give go again.');
 $dynReset($p);$a=$attack($p,'spiders_bite');$w=AddWeapons($p,CardID:'spiders_bite',Owner:$p,Controller:$p);$other=AddWeapons($p,CardID:'spiders_bite',Owner:$p,Controller:$p);FaBSetObjectCounter($a,'WEAPON_UID',$w->UniqueID);$check(FaBArakniDaggers($p)===$ref($other),'Danger Digits can throw the active dagger.');$before=intval(GetHealth(1));FaBArakniThrow($p,$ref($other));$check(GetHealth(1)===$before-1&&FaBDYNCount(1,'SPIDER')===1&&FaBFindUID($other->UniqueID)['zone']==='Graveyard','Danger Digits failed damage, hit, or destruction.');
 $dynReset($p);$a=$attack($p,'spiders_bite');$uid=$macro($p,'incision_blue');$answer($p,$ref($a));$check(in_array('WTR_POWER:1',$a->TurnEffects,true),'Incision did not boost the dagger.');
 $dynReset($p);$a=$attack(1,'annihilate_the_armed_red',$p);$e=AddEquipment($p,CardID:'leap_frog_slime_skin',Owner:$p,Controller:$p);FaBArakniReactionEvent(1,true);$answer($p,'1');$check(FaBFindUID($e->UniqueID)['zone']==='CombatChain'&&FaBDefenseValue(FaBGetState(),$p)===1,'Leap Frog failed to defend from its trigger.');$before=intval(GetHealth(1));$d=AddCombatChain($p,CardID:'hunted_or_hunter_red',Role:'DEFENSE_REACTION',ChainLink:1,Owner:$p,Controller:$p);OnDefended($p,$ref($d),$p);$check(GetHealth(1)===$before-1,'Hunted or Hunter failed conditional life loss.');FaBCleanupResolvedLink(FaBGetState());FaBCloseCombatChain();$check(FaBFindUID($e->UniqueID)['zone']==='Graveyard','Leap Frog ignored Blade Break.');
 $dynReset($p);AddResources($p,0);$w=AddGraveyard($p,CardID:'spiders_bite');$pitch=AddHand($p,CardID:'incision_blue');$uid=$macro($p,'up_sticks_and_run_blue');$answer($p,$ref($w));$check(GetDecisionQueue($p)[0]->Tooltip==='Pitch_to_retrieve','Retrieve failed to prompt for its resource.');$answer($p,$ref($pitch));$check(FaBFindUID($w->UniqueID)['zone']==='Weapons'&&GetResources($p)===2,'Retrieve did not equip or pay exactly one.');
 $dynReset($p);AddWeapons($p,CardID:'spiders_bite');AddWeapons($p,CardID:'spiders_bite');AddGraveyard($p,CardID:'spiders_bite');$check(FaBArakniRetrieveTargets($p)==='','Retrieve allows a third equipped dagger.');
 $dynReset($p);$s=FaBGetState();$s['botProfiles']=[$p=>'arakni'];FaBSetState($s);$red=AddHand($p,CardID:'annihilate_the_armed_red');$blue=AddHand($p,CardID:'incision_blue');$check(FaBArakniKeepValue($red,$p)>FaBArakniKeepValue($blue,$p),'Bot fails to preserve a red contract over blue reaction.');
 $d=(object)['Type'=>'MZCHOOSE','Tooltip'=>'Pitch_to_retrieve','Param'=>$ref($red).'&'.$ref($blue)];$check(FaBBotChoice($p,$d)===$ref($blue),'Bot fails to pitch blue efficiently.');
 $dagger=AddWeapons($p,CardID:'spiders_bite',Owner:$p,Controller:$p);AddResources($p,1);$blue->removed=true;$check(FaBArakniAbilityScore($p,$dagger)<0,'Bot would pitch its only contract for a setup dagger attack.');
 $d=(object)['Type'=>'MZCHOOSE','Tooltip'=>'Choose_attack_target','Param'=>FaBARCHeroTargets($p)];$first=FaBBotChoice($p,$d);AddHand(1,CardID:'command_and_conquer_red');$check(FaBBotChoice($p,$d)===$first,'Bot uses hidden opponent hand.');
 if($p===4){$dynReset($p);$a=$attack(1,'annihilate_the_armed_red',2);$e=AddEquipment(3,CardID:'leap_frog_slime_skin',Owner:3,Controller:3);FaBArakniReactionEvent(1,true);$answer(3,'1');$check(FaBDefenseValue(FaBGetState(),2)===1,'UPF Leap Frog did not defend another hero.');}
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "Arakni deck, card outcomes, and heuristics passed in duels and UPF.\n";
