<?php
require_once __DIR__.'/dtd_test.php';
$failures=[];
$dtdReset=function(int $n)use($dynReset){$dynReset($n);foreach(FaBSeatOrder() as $seat)foreach(['Inventory','Soul','Temp'] as $zone){$get='Get'.$zone;$z=&$get($seat);$z=[];}SetTurnNumber(10);};
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
foreach([2,4] as $p){
 // Rune gate bypasses printed cost, not taxes, and consumes only our own runes.
 $dtdReset($p);$b=AddBanish($p,CardID:'vantom_wraith_red',Owner:$p);$cost=intval(CardCost($b->CardID));FaBARCCreateRunes($p,max(0,$cost-1));
 $check(!FaBDTDRuneGate($p,$b),'Rune gate accepted insufficient runes.');FaBARCCreateRunes(1,5);$check(!FaBDTDRuneGate($p,$b),'Rune gate borrowed opponent runes.');FaBARCCreateRunes($p,1);
 $check(FaBDTDRuneGate($p,$b)&&FaBCardCost($b,$p)===0,'Rune gate did not waive base cost.');FaBWTRCreateArena($p,'frostbite');$check(FaBCardCost($b,$p)===1,'Rune gate erased Frostbite tax.');$b->FaceDown=1;$check(!FaBDTDBanishPlayable($p,$b),'Face-down Rune Gate allowed.');
 $dtdReset($p);$o=AddHand($p,CardID:'numbskull_red');FaBWTRTag($o,'WTR_DEFENSE:7');FaBWTRCreateArena($p,'frostbite');$check(FaBCurrentDefense($o,$p)===3&&FaBCardCost($o,$p)===2,'Numbskull stats or cost changed.');$a=$attack($p,'numbskull_red');FaBWTRTag($a,'WTR_POWER:6');$check(FaBAttackPower(FaBGetState())===6,'Numbskull power changed.');
 // Charge and soul entry are distinct; the other heroes do not receive Solflare.
 $dtdReset($p);$c=AddHand($p,CardID:'banneret_of_courage_yellow');FaBMoveUID(intval($c->UniqueID),'Soul',$p);$check(!FaBMONArena($p,'courage'),'Solflare triggered on normal soul entry.');$c=AddHand($p,CardID:'banneret_of_courage_yellow');FaBMONCharge($p,$ref($c));$check(count(FaBMONArena($p,'courage'))===1&&!FaBMONArena(1,'courage'),'Solflare wrong player.');
 $c=AddHand($p,CardID:'banneret_of_resilience_yellow');FaBMONCharge($p,$ref($c));$block=AddCombatChain($p,CardID:'wounding_blow_red',Role:'DEFENSE',FromZone:'Hand',ChainLink:1);FaBWTRApplyNextDefense($p,$block);$check(FaBCurrentDefense($block,$p)===4,'Resilience defense not applied.');
 // Prism searches into play and awakens a permanent while retaining its UID.
 $dtdReset($p);GetHero($p)[0]->CardID='prism_advent_of_thrones';$fig=AddDeck($p,CardID:'figment_of_protection_yellow',Owner:$p);$c=AddHand($p,CardID:'wartune_herald_yellow');FaBMoveUID(intval($c->UniqueID),'Soul',$p);
 $check((GetDecisionQueue($p)[0]->Tooltip??'')==='Search_for_figment','Prism soul trigger missing.');$answer($p,'1');$answer($p,$ref($fig));$check(FaBFindUID(intval($fig->UniqueID))['zone']==='Arena'&&count(FaBMONArena($p,'spectral_shield'))===1,'Prism failed to enter Figment or trigger it.');
 $check(FaBWTRActivate($p,$ref(GetHero($p)[0])),'Prism activation illegal.');$answer($p,FaBMONSoul($p));$answer($p,$ref($fig));$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$angel=FaBFindUID(intval($fig->UniqueID));$check($angel['object']->CardID==='aegis_archangel_of_protection','Awaken failed or searched again.');$check(FaBMONArenaAttackSpec($p,$angel)['cost']===2,'Angel attack cost wrong.');
 FaBMoveUID(intval($fig->UniqueID),'Graveyard',$p);$check(FaBFindUID(intval($fig->UniqueID))['object']->CardID==='figment_of_protection_yellow','Angel did not reset its front face on leaving.');
 // Unity considers exactly the simultaneous declaration, not prior defenders.
 $dtdReset($p);$a=$attack(1,'death_touch_red',$p);$u=AddCombatChain($p,CardID:'anthem_of_spring_blue',Role:'DEFENSE',FromZone:'Hand',ChainLink:1,Owner:$p);$d=AddCombatChain($p,CardID:'wounding_blow_red',Role:'DEFENSE',FromZone:'Hand',ChainLink:1,Owner:$p);
 FaBDTDDefendGroup($p,[$u->UniqueID]);$check(!FaBHasPendingDecision(),'Unity used an earlier defender.');FaBDTDDefendGroup($p,[$u->UniqueID,$d->UniqueID]);$choices=FaBDYNHeroTargets($p);$all=implode('&',array_slice(explode('&',$choices),0,2));$answer($p,$all);foreach(explode('&',$all) as $r)$check(count(FaBMONArena(FaBIdentityFromMZ($r)['player'],'embodiment_of_earth'))===1,'Unity failed selected hero.');
 $dtdReset($p);GetHero($p)[0]->CardID='boltyn';GetHero(1)[0]->CardID='prism';FaBDTDParty($p);$check(count(FaBMONArena($p,'courage'))===1&&!FaBMONArena(1,'spectral_shield'),'United We Stand treated an opposing hero as a party member.');
 // Life loss includes non-damage and counts distinct heroes, including self.
 $dtdReset($p);FaBARCLoseLife($p,1,$p);FaBARCLoseLife(1,2,$p);FaBARCLoseLife(1,1,$p);$before=GetHealth($p);$macro($p,'deathly_delight_red','CombatChainClosed');$check(GetHealth($p)===$before+2,'Deathly Delight counted loss events instead of heroes.');$macro($p,'deathly_wail_blue','CombatChainClosed');$check(FaBARCRunechants($p)===2,'Deathly Wail missing self or another hero.');
 $h=AddHand(1,CardID:'zap_blue');$own=AddHand($p,CardID:'zap_red');$macro($p,'widespread_annihilation_blue','CombatChainClosed');$answer(1,$ref($h));$answer($p,$ref($own));$check(FaBFindUID(intval($h->UniqueID))['zone']==='Banish'&&FaBFindUID(intval($own->UniqueID))['zone']==='Banish','Widespread choices not handled by every affected hero.');
 // Every hero chooses independently; restrictions start on their own next turn.
 $dtdReset($p);$macro($p,'warmongers_diplomacy_blue');$order=FaBDTDUnitedOrder($p);foreach($order as $i=>$seat){$check((GetDecisionQueue($seat)[0]->Tooltip??'')==='Choose_war_or_peace','Diplomacy chooser/order wrong.');$answer($seat,$i%2?'1':'0');}
 $s=FaBGetState();$check(count($s['nextTurnEffects'])===count($order),'Diplomacy omitted a hero.');$s['turnEffects'][(string)$p]=$s['nextTurnEffects'][(string)$p];FaBSetState($s);$aa=(object)['CardID'=>'wounding_blow_red'];$naa=(object)['CardID'=>'nimblism_red'];$peace=(count($order)-1)%2===1;$check(FaBDTDRestrictions($p,$aa,true,true)===!$peace&&FaBDTDRestrictions($p,$naa,true,false)===$peace,'War/peace actions wrong.');
 // Forcefield applies once per aura per packet; cloak affects only that packet.
 $dtdReset($p);$a=$attack(1,'wounding_blow_red',$p);$soulCard=AddSoul($p,CardID:'wartune_herald_yellow');$extra=AddSoul($p,CardID:'zap_blue');$force=FaBWTRCreateArena($p,'radiant_forcefield_yellow');$before=GetHealth($p);FaBBeginDamageStep();$check((GetDecisionQueue($p)[0]->Tooltip??'')==='Choose_damage_prevention','Missing Forcefield damage prompt.');$answer($p,$ref($soulCard));$check(GetHealth($p)===$before-3&&FaBFindUID(intval($extra->UniqueID))['zone']==='Soul','Forcefield prevented more than once per packet.');
 $dtdReset($p);$a=$attack(1,'wounding_blow_red',$p);$cloak=AddEquipment($p,CardID:'cloak_of_darkness',Owner:$p,Controller:$p);$before=GetHealth($p);FaBBeginDamageStep();$answer($p,$ref($cloak));$check(GetHealth($p)===$before-2&&FaBFindUID(intval($cloak->UniqueID))['zone']==='Banish','Cloak did not banish and prevent 2.');$before=GetHealth($p);DoDamage(1,'',$p,1);$check(GetHealth($p)===$before-1,'Cloak prevention leaked into next damage.');
 // The common generated damage path also offers prevention for earlier-set spells.
 $dtdReset($p);$cloak=AddEquipment($p,CardID:'cloak_of_darkness',Owner:$p,Controller:$p);$o=AddGraveyard(1,CardID:'zap_red');FaBARCSetCard(intval($o->UniqueID),'target',$p);$before=GetHealth($p);FaBRunSourceMacro('ResolveCard',1,'zap_red',['mzID'=>$ref($o)]);$answer($p,$ref($cloak));$check(GetHealth($p)===$before-1,'Earlier-set arcane spell skipped DTD prevention.');
 $dtdReset($p);$a=$attack(1,'malign_red',$p);$soulCard=AddSoul($p,CardID:'zap_red');FaBWTRCreateArena($p,'radiant_forcefield_yellow');$before=GetHealth($p);FaBBeginDamageStep();$answer($p,$ref($soulCard));$check(GetHealth($p)===$before-intval(CardPower('malign_red'))&&!FaBMONArena($p,'radiant_forcefield'),'Unpreventable damage skipped mandatory soul cost or was prevented.');
 // Levia's two faces share one inventory card; old hero enters soul, life resets.
 $dtdReset($p);GetHero($p)[0]->CardID='levia';$old=intval(GetHero($p)[0]->UniqueID);AddInventory($p,CardID:'levia_redeemed',Owner:$p,Controller:$p);FaBDTDTransform($p,'blasmophet_levia_consumed');$check(GetHero($p)[0]->CardID==='blasmophet_levia_consumed'&&FaBFindUID($old)['zone']==='Soul'&&GetHealth($p)===intval(CardHealth('blasmophet_levia_consumed')),'Demi-hero transformation incorrect.');
 $c=AddHand($p,CardID:'ram_raider_red');FaBMoveUID(intval($c->UniqueID),'Banish',$p);$check(FaBMONCount($p,'BANISHED_SIX')>0&&FaBFindUID(intval($c->UniqueID))['object']->FaceDown,'Blasmophet lost face-up banish event.');
 $dtdReset($p);GetHero($p)[0]->CardID='levia';AddInventory($p,CardID:'blasmophet_levia_consumed',Owner:$p,Controller:$p);FaBDTDTransform($p,'levia_redeemed');$c=AddBanish($p,CardID:'ram_raider_red',Owner:$p);$check(!FaBHasKeyword($c,'Blood Debt')&&FaBMONBloodDebt($p)===0,'Redeemed cards retain blood debt.');
 // Rune Gate really pays zero, uses next-rune buffs, and consumes its own Runechants.
 $dtdReset($p);AddResources($p,0);$b=AddBanish($p,CardID:'vantom_wraith_red',Owner:$p);FaBARCCreateRunes($p,2);FaBDTDAdd($p,'NEXT_RUNE',3);$s=FaBGetState();$s['pendingAttackTarget']=['player'=>$p,'sourceUID'=>intval($b->UniqueID),'sourceKind'=>'PLAY','target'=>FaBLegalAttackTargets($p)[0]];FaBSetState($s);
 PlayCard($p,$ref($b));if((GetDecisionQueue($p)[0]->Tooltip??'')==='Choose_attack_target')$answer($p,explode('&',GetDecisionQueue($p)[0]->Param)[0]);
 $check(FaBARCCard(intval($b->UniqueID),'dtdRuneGate')&&in_array('WTR_POWER:3',(array)FaBFindUID(intval($b->UniqueID))['object']->TurnEffects,true)&&FaBARCRunechants($p)===0,'Rune Gate payment or next-gate buff failed.');
 // Chosen unpreventability applies to just the next Runechant effect.
 $dtdReset($p);$macro($p,'vynnset','ResolveAbility');$answer($p,'1');$r=AddGraveyard($p,CardID:'runechant');FaBARCSetCard(intval($r->UniqueID),'target',1);AddEquipment(1,CardID:'dyadic_carapace',Owner:1,Controller:1);$before=GetHealth(1);FaBRunSourceMacro('ResolveCard',$p,'runechant',['mzID'=>$ref($r)]);$check(GetHealth(1)===$before-1&&!FaBHasPendingDecision()&&!FaBDTDCount($p,'UNPREVENTABLE_RUNE'),'Vynnset rune allowed prevention or did not consume effect.');
 // Chains replaces draws for every hero during the action phase, not the refill.
 $dtdReset($p);FaBWTRCreateArena($p,'chains_of_mephetis_blue');$c=AddDeck(1,CardID:'wounding_blow_red',Owner:1);DoDrawCard(1,1);$ban=FaBFindUID(intval($c->UniqueID));$check($ban['zone']==='Banish'&&FaBDTDPermission(1,$ban['object']),'Chains did not replace another hero draw or grant permission.');$s=FaBGetState();$s['uprRefill']=true;FaBSetState($s);$c=AddDeck(1,CardID:'zap_blue');DoDrawCard(1,1);$check(FaBFindUID(intval($c->UniqueID))['zone']==='Hand','Chains replaced end-turn refill.');
 // Additional random banish is paid after pitching, so it cannot strand payment.
 $dtdReset($p);AddResources($p,0);$c=AddHand($p,CardID:'ram_raider_red');$blue=AddHand($p,CardID:'zap_blue');$payload=AddHand($p,CardID:'wall_breaker_red');PlayCard($p,$ref($c));if((GetDecisionQueue($p)[0]->Tooltip??'')==='Choose_attack_target')$answer($p,explode('&',GetDecisionQueue($p)[0]->Param)[0]);$check((GetDecisionQueue($p)[0]->Tooltip??'')==='Pitch_before_banish_cost','Random additional cost did not reserve payment.');$answer($p,$ref($blue));$check(FaBFindUID(intval($payload->UniqueID))['zone']==='Banish'&&FaBGetState()['pendingPayment']===null,'Random banish stranded resource payment.');
 // Blasmophet triggers at exactly 13, then remaining blood debt banishes cards.
 $dtdReset($p);GetHero($p)[0]->CardID='levia';AddHealth($p,14);AddInventory($p,CardID:'levia_redeemed',Owner:$p,Controller:$p);AddBanish($p,CardID:'vantom_wraith_red',Owner:$p);AddBanish($p,CardID:'vantom_wraith_blue',Owner:$p);$top=AddDeck($p,CardID:'zap_blue');$check(FaBDTDBloodDebt($p),'Blood debt did not queue transformation.');$answer($p,'1');$check(GetHealth($p)===13&&GetHero($p)[0]->CardID==='blasmophet_levia_consumed'&&FaBFindUID(intval($top->UniqueID))['zone']==='Banish','Blood-debt transformation timing incorrect.');
 // Late reactions also trigger Call Down the Lightning; mirage sees changed power.
 $dtdReset($p);$a=$attack(1,'wounding_blow_red',$p);FaBDTDAdd(1,'LIGHTNING');$d=AddCombatChain($p,CardID:'flicker_trick_red',Role:'DEFENSE_REACTION',FromZone:'Hand',ChainLink:1);$before=GetHealth($p);OnDefended($p,$ref($d),$p);$check(GetHealth($p)===$before-1,'Lightning ignored defense reaction from hand.');FaBWTRTag($a,'WTR_POWER:2');GameAfterEngineAction([],[]);$check(FaBFindUID(intval($d->UniqueID))['zone']==='Graveyard','Mirage did not recheck changed attack power.');
 // Copy effects change the active identity but not the physical card after combat.
 $dtdReset($p);$a=$attack($p,'alluring_inducement_yellow');$h=AddHand(1,CardID:'death_touch_red');FaBRunSourceMacro('AttackDeclared',$p,$a->CardID,['mzID'=>$ref($a)]);$answer($p,FaBDTDRefs($p,'Temp','aa'));$check($a->CardID==='death_touch_red'&&FaBFindUID(intval($h->UniqueID))['zone']==='Hand','Alluring Inducement did not copy or stole card.');FaBMoveUID(intval($a->UniqueID),'Graveyard',$p);$check(FaBFindUID(intval($a->UniqueID))['object']->CardID==='alluring_inducement_yellow','Copied identity leaked into graveyard.');
 // Charging must leave enough resources to pay the activation.
 $dtdReset($p);AddResources($p,0);$valor=AddArena($p,CardID:'v_for_valor_red',Owner:$p);AddHand($p,CardID:'zap_blue');$valorSpec=['timing'=>'REACTION','cost'=>1,'cardID'=>'v_for_valor_red'];$check(!FaBDTDAbilityLegal($p,FaBFindUID(intval($valor->UniqueID)),$valorSpec),'Valor allowed charging its only pitch card.');AddHand($p,CardID:'zap_red');$check(FaBDTDAbilityLegal($p,FaBFindUID(intval($valor->UniqueID)),$valorSpec),'Valor rejected affordable charge.');
 $dtdReset($p);GetHero($p)[0]->CardID='levia_redeemed';$debt=AddBanish($p,CardID:'ram_raider_red');$check(!FaBHasKeyword($debt,'Blood Debt'),'Redeemed failed ownerless zone object.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "DTD rule outcomes passed in duels and four-seat UPF.\n";

