<?php
require_once __DIR__.'/dyn_test.php';
$failures=[];
$dynReset=function(int $p)use($arcReset){$arcReset($p);SetTurnPlayer($p);SetPriorityPlayer($p);SetTurnNumber(10);SetCurrentPhase('MAIN');foreach(FaBLiveSeats() as $s){foreach(['Equipment','Weapons','Arena','Hand','Deck','Graveyard','Banish','Soul','Arsenal','CombatChain'] as $z){$get='Get'.$z;$v=&$get($s);$v=[];}GetHero($s)[0]->CardID='ira_crimson_haze';AddHealth($s,30);}AddResources($p,20);};
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBFindUID($uid)['mzID']],$params));return $uid;};
$attack=function(int $p,string $id,int $target=1){$o=AddCombatChain($p,CardID:$id,Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:1);$s=FaBGetState();$s['attacker']=$p;$s['defender']=$target;$s['attackUID']=intval($o->UniqueID);$s['chainLink']=1;$s['combatOpen']=true;$s['combatStep']='REACTION';$s['window']='REACTION';$s['attackTarget']=['type'=>'HERO','player'=>$target,'uid'=>FaBUPRHeroUID($target),'zone'=>'Hero'];FaBSetState($s);return $o;};
$ref=fn($o)=>FaBFindUID(intval($o->UniqueID))['mzID'];
foreach([2,4] as $p){
 $dynReset($p);$a=$attack($p,'annihilate_the_armed_red');$b=AddCombatChain($p,CardID:'plunder_the_poor_red',Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:2);AddDeck(1,CardID:'ravenous_rabble_red');FaBDYNBanishTop($p,1,1);$check(count(FaBMONArena($p,'silver'))===2,'Concurrent contracts did not both reward their controller.');
 AddDeck(1,CardID:'ravenous_rabble_red');FaBMoveUID(intval(GetDeck(1)[0]->UniqueID),'Banish',1);$check(count(FaBMONArena($p,'silver'))===2,'Opponent banishing their own card completed a contract.');
 if($p===4){$c=AddCombatChain(3,CardID:'plunder_the_poor_red',Owner:3,Controller:3,Role:'ATTACK',ChainLink:1);AddDeck(1,CardID:'ravenous_rabble_red');FaBDYNBanishTop($p,1,1);$check(count(FaBMONArena(3,'silver'))===0,'Another Assassin received the banishing player contract reward.');}
 $dynReset($p);$a=$attack($p,'surgical_extraction_blue');$h=AddHand(1,CardID:'zap_blue');AddDeck(1,CardID:'zap_blue');FaBRunSourceMacro('Hit',$p,$a->CardID,['mzID'=>$ref($a),'amount'=>4]);$d=GetDecisionQueue($p)[0];$check(str_contains($d->Param,'p'.$p.'Temp-'),'Surgical Extraction exposed the private hand in the wrong seat.');$answer($p,explode('&',$d->Param)[0]);$check(FaBFindUID(intval($h->UniqueID))['zone']==='Banish'&&count(FaBMONArena($p,'silver'))===2,'Surgical Extraction banished a preview copy instead of the original card.');
 $dynReset($p);$hero=&GetHero($p);$hero=[];AddHero($p,CardID:'arakni',Owner:$p,Controller:$p);$d1=AddDeck(1,CardID:'zap_red');$d2=AddDeck(1,CardID:'zap_blue');$uid=$macro($p,'arakni','ResolveAbility','Hero');$answer($p,$ref(GetHero(1)[0]));$q=GetDecisionQueue($p)[0];$check($q->Type==='MZREARRANGE'&&$q->Param==='Top=zap_red;Bottom=','Arakni did not show the inspected card.');$answer($p,'Top=;Bottom=zap_red');$check(array_map(fn($r)=>FaBIdentityFromMZ($r)['object']->CardID,FaBChoiceRefs(1,'Deck'))===['zap_blue','zap_red'],'Arakni did not bottom the selected opponent top card.');
 foreach(['arakni','arakni_huntsman'] as $heroID)foreach(['top','bottom','pass','empty'] as $mode){
  $dynReset($p);if($mode!=='empty'){AddDeck(1,CardID:'zap_red');AddDeck(1,CardID:'zap_blue');}
  $macro($p,$heroID,'ResolveAbility','Hero');$answer($p,$mode==='pass'?'PASS':$ref(GetHero(1)[0]));
  if(in_array($mode,['top','bottom'],true)){$q=GetDecisionQueue($p)[0];$check($q->Type==='MZREARRANGE'&&$q->Param==='Top=zap_red;Bottom=','Peek must expose only the selected top card.');$check(count(FaBChoiceRefs($p,'Temp'))===1&&count(FaBChoiceRefs(1,'Temp'))===0,'Peek card must stay private to its viewer.');$answer($p,$mode==='bottom'?'Top=;Bottom=zap_red':'Top=zap_red;Bottom=');}
  $expected=$mode==='empty'?[]:($mode==='bottom'?['zap_blue','zap_red']:['zap_red','zap_blue']);
  $check(array_map(fn($r)=>FaBIdentityFromMZ($r)['object']->CardID,FaBChoiceRefs(1,'Deck'))===$expected&&!GetDecisionQueue($p)&&!FaBChoiceRefs($p,'Temp'),'Arakni peek failed '.$heroID.' '.$mode);
 }
 $dynReset($p);$a=$attack($p,'annihilate_the_armed_red');$eq=AddCombatChain(1,CardID:'ironrot_helm',Owner:1,Controller:1,Role:'DEFENSE',ChainLink:1,FromZone:'Equipment');$uid=$macro($p,'shred_red');$answer($p,$ref($eq));$check(FaBCurrentDefense($eq,1)===0,'Shred did not reduce equipment defense.');
 $dynReset($p);$e=AddEquipment($p,CardID:'seasoned_saviour',Owner:$p,Controller:$p);FaBDYNSetup($p);$check(FaBCurrentDefense($e,$p)===1,'Seasoned Saviour must start with two negative defense counters.');$uid=$macro($p,'reinforce_steel_red');$answer($p,$ref($e));$check(FaBCurrentDefense($e,$p)===2,'Reinforce Steel did not remove a negative defense counter.');
 $dynReset($p);$e=AddEquipment(1,CardID:'ironrot_helm',Owner:1,Controller:1);$a=$attack($p,'drill_shot_red');FaBRunSourceMacro('Hit',$p,$a->CardID,['mzID'=>$ref($a),'amount'=>1]);$answer($p,$ref($e));$check(FaBCurrentDefense($e,1)===0,'Drill Shot counter had the wrong sign.');
 $dynReset($p);$weapons=&GetWeapons($p);$weapons=[];AddWeapons($p,CardID:'sandscour_greatbow',Owner:$p,Controller:$p);$d=AddDeck($p,CardID:'long_shot_red');FaBDYNTopArrow($p,true);$ar=GetArsenal($p)[0];$check(intval(FaBObjectCounters($ar)['AIM'])===1&&$ar->FaceDown===0,'Deck-loaded arrow lacks one aim counter.');$a=FaBMoveUID(intval($d->UniqueID),'CombatChain',$p);$a->Role='ATTACK';$a->ChainLink=1;$s=FaBGetState();$s['attacker']=$p;$s['defender']=1;$s['attackUID']=$a->UniqueID;$s['chainLink']=1;FaBSetState($s);$check(FaBDYNPower($p,$a)===2,'Aim counter did not survive playing Long Shot.');
 $dynReset($p);$a=$attack($p,'spiders_bite');$e=AddCombatChain(1,CardID:'ironrot_helm',Owner:1,Controller:1,Role:'DEFENSE',ChainLink:1,FromZone:'Equipment');$check(FaBDYNPower($p,$a)===1,'Piercing failed against defending equipment.');FaBDYNHit($p,$a,1);$h=AddCombatChain(1,CardID:'ravenous_rabble_red',Owner:1,Controller:1,Role:'DEFENSE',ChainLink:1,FromZone:'Hand');$s=FaBGetState();$s['declaredBlockUIDs']=[$h->UniqueID];FaBSetState($s);FaBDYNDefendGroup(1);$check(FaBDYNDefense(1,$h)===-1&&FaBDYNCount(1,'SPIDER')===0,'Spider Bite did not consume on the defending group.');
 $dynReset($p);$a=$attack($p,'nitro_mechanoid');$h=AddCombatChain(1,CardID:'ravenous_rabble_red',Owner:1,Controller:1,Role:'DEFENSE',ChainLink:1,FromZone:'Hand');$other=AddHand(1,CardID:'zap_blue');$check(!FaBDYNBlockLegal(1,FaBFindUID($other->UniqueID)),'Overpower allowed two action cards to defend.');
 $dynReset($p);$a=$attack($p,'regicide_blue');AddBanish(1,CardID:'ravenous_rabble_blue');$h=AddHand(1,CardID:'ravenous_rabble_red');$check(!FaBDYNBlockLegal(1,FaBFindUID($h->UniqueID)),'Regicide compared pitch identities instead of names.');FaBDYNAttack($p,$a);FaBCloseCombatChain();$check(!FaBSeatIsLive($p),'Regicide attacker survived closing the chain.');
 $dynReset($p);$a=$attack($p,'regicide_blue');AddEquipment(1,CardID:'crown_of_dominion',Owner:1,Controller:1);FaBRunSourceMacro('Hit',$p,$a->CardID,['mzID'=>$ref($a),'amount'=>1]);$check(!FaBSeatIsLive(1)&&($p===2?intval(GetWinner())===$p:intval(GetWinner())===0),'Regicide did not eliminate only the Royal victim.');
 $dynReset($p);$a=AddGraveyard($p,CardID:'aether_quickening_red');FaBTagUID($a->UniqueID,'DYN_ARCANE:1');FaBARCSetCard($a->UniqueID,'uprTargetUID',FaBUPRHeroUID(1));$ap=intval(GetActionPoints($p));FaBRunSourceMacro('ResolveCard',$p,$a->CardID,['mzID'=>$ref($a)]);$check(intval(GetHealth(1))===25&&intval(GetActionPoints($p))===$ap+1,'Surge failed to use actual boosted damage.');
 $dynReset($p);$uid=$macro($p,'blessing_of_aether_red','StartTurn','Arena');$spell=AddStack(CardID:'sap_red',Controller:$p,Kind:'ACTION');FaBDYNPlayed($p,$spell,'Hand');$check(FaBDYNArcaneBonus($spell->UniqueID)===3&&FaBDYNCount($p,'BLESS_AETHER')===0,'Blessing of Aether did not apply to the next card.');
 $dynReset($p);$a=AddArena($p,CardID:'surgent_aethertide',Owner:$p,Controller:$p);FaBDYNDamaged($p,2,$ref($a));$spell=AddStack(CardID:'zap_red',Controller:$p,Kind:'ACTION');FaBDYNPlayed($p,$spell,'Hand');$next=AddStack(CardID:'zap_red',Controller:$p,Kind:'ACTION');FaBDYNPlayed($p,$next,'Hand');$check(FaBDYNArcaneBonus($spell->UniqueID)===2&&FaBDYNArcaneBonus($next->UniqueID)===0,'Surgent bonus was not limited to the first qualifying card.');
 $dynReset($p);$e=AddEquipment($p,CardID:'wave_of_reality',Owner:$p,Controller:$p);$before=intval(GetHealth($p));DoDamage(1,'',$p,2);$check(intval(GetHealth($p))===$before&&FaBFindUID($e->UniqueID)['zone']==='Graveyard'&&!FaBMONArena($p,'spectral_shield'),'Ward destruction did not create and consume Wave of Reality shield.');
 $dynReset($p);$k=AddEquipment($p,CardID:'celestial_kimono',Owner:$p,Controller:$p);$a=FaBWTRCreateArena($p,'tome_of_aeo_blue');$before=intval(GetResources($p));FaBMONDestroy($a->UniqueID);FaBMONDestroy($k->UniqueID);$check(intval(GetResources($p))===$before+1,'Celestial Kimono triggered more than once in a turn.');
 $dynReset($p);FaBWTRCreateArena($p,'runechant');FaBDYNAdd($p,'TIARA');$r=FaBMONSpellvoidRefs($p);$check($r!==''&&FaBMONSpellvoid($p,$r)===1&&!FaBMONArena($p,'runechant'),'Amethyst Tiara did not grant functional spellvoid.');
 $dynReset($p);$shield=FaBWTRCreateArena($p,'spectral_shield');$invoke=AddArena($p,CardID:'invoke_suraya_yellow',Owner:$p,Controller:$p);FaBARCSetCard($invoke->UniqueID,'dynShield',$shield->UniqueID);FaBDYNSuraya($p,$invoke->UniqueID);$f=FaBFindUID($invoke->UniqueID);$check($f['object']->CardID==='suraya_archangel_of_knowledge'&&FaBMONArenaAttackSpec($p,$f)['cost']===2,'Suraya transformation or attack cost failed.');FaBDYNDamaged($p,3,$f['mzID']);$check(intval(GetHealth($p))===33,'Suraya did not gain life for damage.');
 $dynReset($p);$targets=[];foreach(['hyper_driver_red','hyper_driver_yellow','hyper_driver_blue'] as $id){$o=FaBWTRCreateArena($p,$id);FaBARCEnterItem($p,$o);$targets[]=$ref($o);$check(intval(FaBObjectCounters($o)['STEAM'])===4-intval(CardPitch($id)),'Hyper Driver color steam count incorrect.');}
 foreach(['viziertronic_model_i','teklo_foundry_heart','galvanic_bender','achilles_accelerator'] as $id){$o=AddEquipment($p,CardID:$id,Owner:$p,Controller:$p);$targets[]=$ref($o);}$o=AddWeapons($p,CardID:'teklo_plasma_pistol',Owner:$p,Controller:$p);$targets[]=$ref($o);$construct=AddArena($p,CardID:'construct_nitro_mechanoid_yellow',Owner:$p,Controller:$p);FaBDYNConstruct($p,$construct->UniqueID,implode('&',$targets));$f=FaBFindUID($construct->UniqueID);$check($f['object']->CardID==='nitro_mechanoid'&&$f['zone']==='Equipment'&&count(FaBObjectCounters($f['object'])['DYN_MATERIAL'])===8,'Nitro failed to transform all eight selected materials.');$s=FaBGetState();$s['window']='ACTION';FaBSetState($s);$check(FaBDYNWeaponCanAttack($p,$f),'Nitro cannot attack with material.');
 $dynReset($p);$a=$attack($p,'crankshaft_red');$driver=AddDeck($p,CardID:'hyper_driver_blue');FaBDYNAdd($p,'BIOS_POWER');FaBDYNAdd($p,'BIOS_ITEM');FaBARCBoost($p,$a->UniqueID);$f=FaBFindUID($driver->UniqueID);$check($f['zone']==='Arena'&&intval(FaBObjectCounters($f['object'])['STEAM'])===1&&in_array('WTR_POWER:3',$a->TurnEffects,true),'Bios Update did not deploy boosted item and empower attack.');
 $dynReset($p);$h=AddHand($p,CardID:'reincarnate_red');FaBDiscardRandom($p);$check(FaBFindUID($h->UniqueID)['zone']==='Deck','Reincarnate random discard did not bottom itself.');$h=AddHand($p,CardID:'skull_crack_red');$before=intval(GetResources($p));FaBDiscardRandom($p);$check(intval(GetResources($p))===$before+1,'Skull Crack did not grant a resource.');
 $dynReset($p);$a=FaBWTRCreateArena(1,'passing_mirage_blue');$t=FaBWTRCreateArena($p,'tranquil_passing_red');FaBDYNTranquil($t->UniqueID,$ref($a));$check(FaBFindUID($a->UniqueID)['zone']==='Banish','Tranquil did not banish opposing aura.');FaBMONDestroy($t->UniqueID);$check(FaBFindUID($a->UniqueID)['zone']==='Arena'&&FaBFindUID($a->UniqueID)['player']===1,'Tranquil failed to return aura to its controller.');
 $dynReset($p);$victim=$p===4?3:1;$before=intval(GetHealth($victim));$life=intval(GetHealth($p));FaBDYNProtect($p,$ref(GetHero($victim)[0]));DoDamage(1,'',$victim,4);$check(intval(GetHealth($victim))===$before&&intval(GetHealth($p))===$life-3,'Yoji did not redirect and prevent one damage.');DoDamage(1,'',$victim,2);$check(intval(GetHealth($victim))===$before-2,'Yoji replacement applied more than once.');
 $dynReset($p);$h=AddHand(1,CardID:'ravenous_rabble_red');FaBDYNProhibit($p,'Ravenous Rabble');$check(!FaBDYNCanPlay(1,FaBFindUID($h->UniqueID)),'Imperial Edict did not prohibit named card.');FaBDYNStart(1);$check(!FaBDYNCanPlay(1,FaBFindUID($h->UniqueID)),'Edict expired on the wrong player turn.');FaBDYNStart($p);$check(FaBDYNCanPlay(1,FaBFindUID($h->UniqueID)),'Edict did not expire on its owner next turn.');
 $dynReset($p);$cc=AddTemp($p,CardID:'command_and_conquer_red');FaBDYNEmperor($p,$cc->UniqueID,$ref(GetHero(1)[0]));$check(FaBStackTop()!==null&&FaBStackTop()->CardID==='command_and_conquer_red','Emperor did not create a Command and Conquer attack.');
 $dynReset($p);$h=AddHand($p,CardID:'reincarnate_red');AddDeck($p,CardID:'skull_crack_red');FaBDYNAdd($p,'BERSERK');FaBDiscardRandom($p);$check(FaBHasPendingDecision(),'Berserk/Reincarnate did not offer trigger ordering.');$answer($p,'0');$check(FaBFindUID($h->UniqueID)['zone']==='Banish'&&count(FaBChoiceRefs($p,'Hand'))===1,'Berserk-first failed to banish and draw.');
 $dynReset($p);$h=AddHand($p,CardID:'reincarnate_red');FaBDYNAdd($p,'BERSERK');FaBDiscardRandom($p);$answer($p,'1');$check(FaBFindUID($h->UniqueID)['zone']==='Deck','Reincarnate-first failed to bottom the card.');
 $dynReset($p);$a=$attack($p,'deathly_duet_blue');FaBARCSetCard($a->UniqueID,'dynPitchNAA',true);FaBRunSourceMacro('AttackDeclared',$p,$a->CardID,['mzID'=>$ref($a)]);$check(count(FaBMONArena($p,'runechant'))===2,'Blue Deathly Duet must create two Runechants.');
 $dynReset($p);$shield=FaBWTRCreateArena(1,'spectral_shield');$a=FaBWTRCreateArena($p,'tranquil_passing_red');FaBDYNTranquil($a->UniqueID,$ref($shield));FaBMONDestroy($a->UniqueID);$check(!FaBFindUID($shield->UniqueID),'Banished aura token returned after Tranquil Passing left.');
 $dynReset($p);$shield=FaBWTRCreateArena($p,'spectral_shield');$invoke=AddArena($p,CardID:'invoke_suraya_yellow',Owner:$p,Controller:$p);FaBARCSetCard($invoke->UniqueID,'dynShield',$shield->UniqueID);FaBDYNSuraya($p,$invoke->UniqueID);AddEquipment($p,CardID:'celestial_kimono',Owner:$p,Controller:$p);$before=intval(GetResources($p));FaBMONDestroy($invoke->UniqueID);$check(intval(GetResources($p))===$before+1&&FaBFindUID($invoke->UniqueID)['object']->CardID==='invoke_suraya_yellow','Destroyed Suraya lost its Ward trigger or failed to revert.');
 $dynReset($p);AddEquipment($p,CardID:'wave_of_reality',Owner:$p,Controller:$p);$a=AddArena(1,CardID:'zap_red',Owner:1,Controller:1);$a->TurnEffects[]='UPR_UNPREVENTABLE';DoDamage(1,$ref($a),$p,3,'ARCANE');$check(intval(GetHealth($p))===27&&!FaBChoiceRefs($p,'Equipment')&&!FaBMONArena($p,'spectral_shield'),'Unpreventable damage must destroy Ward permanents without preventing damage.');
 if($p===4){$dynReset($p);$seats=FaBDYNSelectedSeats(FaBDYNHeroTargets($p,true));$check($seats===[1,3],'UPF Dynasty target list includes a nonadjacent opponent.');FaBEliminateSeat(1);$seats=FaBDYNSelectedSeats(FaBDYNHeroTargets($p,true));$check(in_array(2,$seats,true),'UPF adjacency did not update after elimination.');}

 $dynReset($p);$n=AddEquipment($p,CardID:'nitro_mechanoid',Owner:$p,Controller:$p);$n->Counters=['DYN_MATERIAL'=>['hyper_driver_blue','galvanic_bender']];$nUID=intval($n->UniqueID);$check(FaBDYNWeaponAttack($p,FaBFindUID($nUID)),'Nitro attack activation failed.');for($i=0;$i<4&&GetDecisionQueue($p);++$i){$d=GetDecisionQueue($p)[0];$answer($p,$d->Type==='MZMODAL'?'0':explode('&',$d->Param)[0]);}$check(count(FaBObjectCounters(FaBFindUID($nUID)['object'])['DYN_MATERIAL'])===1,'Nitro attack did not pay exactly one material.');$top=FaBStackTop();$check($top&&$top->Kind==='ATTACK','Nitro attack failed to enter stack.');if($top)DoResolveCard($p,$ref($top));FaBCloseCombatChain();$check(FaBFindUID($nUID)['zone']==='Equipment'&&count(FaBChoiceRefs($p,'Graveyard',['base'=>'nitro_mechanoid']))===0,'Closing Nitro attack moved or duplicated its equipment.');
 $dynReset($p);$h=GetHero($p)[0];$h->CardID='emperor_dracai_of_aesir';AddDeck($p,CardID:'command_and_conquer_red');$check(FaBARCActivate($p,FaBFindUID($h->UniqueID),0),'Emperor activation failed.');if(GetDecisionQueue($p))$answer($p,explode('&',GetDecisionQueue($p)[0]->Param)[0]);$top=FaBStackTop();$check($top&&$top->Kind==='ABILITY','Emperor target choice did not resume activation.');if($top)DoResolveCard($p,$ref($top));if(GetDecisionQueue($p))$answer($p,explode('&',GetDecisionQueue($p)[0]->Param)[0]);$top=FaBStackTop();$check($top&&$top->CardID==='command_and_conquer_red'&&!FaBHasPendingDecision(),'Emperor did not reuse its chosen attack target.');

}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "Dynasty mechanic outcomes passed in duels and UPF.\n";
