<?php
require_once __DIR__.'/evo_test.php';
$failures=[];
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=$zone==='Stack'?AddStack(CardID:$id,Controller:$p,Kind:'ACTION',SourceZone:'Hand'):FaBAddToZone($zone,$p,(object)['CardID'=>$id]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
$evoReset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $seat)foreach(['Inventory','Temp','Soul'] as $zone){$get='Get'.$zone;$zr=&$get($seat);$zr=[];}};
foreach([2,4] as $p){
 // A defending base transforms into a fresh equipped object; its material stays underneath.
 $evoReset($p);$base=AddCombatChain($p,CardID:'evo_sentry_base_head_red',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Equipment',ChainLink:1);FaBEVOCounter($base,'DEFENSE',1);FaBEVOCounter($base,'SUBCARDS',['proto_base_head']);$e=AddGraveyard($p,CardID:'evo_steel_soul_memory_blue',Owner:$p);$uid=intval($e->UniqueID);$check(FaBEVOTransform($p,$ref($e)),'Evo transformation failed.');$f=FaBFindUID($uid);$check($f['zone']==='Equipment'&&FaBEVOUnder($f['object'])===['proto_base_head','evo_sentry_base_head_red']&&empty(FaBObjectCounters($f['object'])['DEFENSE']),'Evo transformation lost materials or inherited counters.');$check(FaBEVOEffect($p,'INTELLECT')===1,'Steel Soul did not trigger from an Evo.');
 $handEvo=AddHand($p,CardID:'evo_sentry_base_arms_red');$check(FaBEvoCount($p)===1,'Hand Evo counted as equipped.');$previews=FaBEVOUnderPreview($p,$uid);$check(FaBEVODestroyUnder($p,$uid,explode('&',$previews)[1],$previews)&&count(FaBEVOUnder($f['object']))===1,'Material choice removed wrong cards.');FaBMONDestroy($uid);$check(count(FaBChoiceRefs($p,'Graveyard',['base'=>'proto_base_head']))===1,'Material did not reach graveyard when Evo left.');
 // Crank grants an action point only during the controller action phase.
 $evoReset($p);GetHero($p)[0]->CardID='maxx_nitro';AddActionPoints($p,0);FaBEVOCreateDriver($p);$answer($p,'0');$driver=FaBIdentityFromMZ(FaBMONArena($p,'hyper_driver')[0])['object'];$check(intval(FaBObjectCounters($driver)['STEAM'])===1&&GetActionPoints($p)===1&&FaBEVOEffect($p,'CRANKED')===1,'Maxx token steam/crank incorrect.');$banksy=AddWeapons($p,CardID:'banksy',Owner:$p,Controller:$p);$check(FaBDYNWeaponCanAttack($p,FaBFindUID(intval($banksy->UniqueID))),'Banksy unavailable after crank.');
 $evoReset($p);SetTurnPlayer(1);AddActionPoints($p,0);$itemObj=AddArena($p,CardID:'boom_grenade_red',Owner:$p,Controller:$p);FaBARCEnterItem($p,$itemObj);$answer($p,'0');$check(GetActionPoints($p)===0&&intval((FaBObjectCounters($itemObj)['STEAM']??0))===0,'Off-turn crank granted action point.');FaBEVOStart($p);$check(!FaBMONArena($p,'boom_grenade'),'Zero-steam item survived start trigger.');
 // Master Cog counters on the stack are added to printed entry counters.
 $evoReset($p);$itemObj=AddArena($p,CardID:'mini_forcefield_red',Owner:$p,Controller:$p);FaBEVOCounter($itemObj,'STEAM',1);FaBARCEnterItem($p,$itemObj);$answer($p,'1');$check(intval((FaBObjectCounters($itemObj)['STEAM']??0))===5,'Entry replaced existing steam.');$before=GetHealth($p);DoDamage(1,'',$p,6,'PHYSICAL');$check(GetHealth($p)===$before-1&&!FaBMONArena($p,'mini_forcefield'),'Ward X prevention incorrect.');
 // Twin Drive boosts twice; each Hyper Driver produces once for the turn.
 $evoReset($p);AddResources($p,0);$driver=AddArena($p,CardID:'hyper_driver_red',Owner:$p,Controller:$p);FaBARCEnterItem($p,$driver);AddDeck($p,CardID:'full_tilt_red',Owner:$p);AddDeck($p,CardID:'gas_guzzler_red',Owner:$p);$twin=AddStack(CardID:'twin_drive_red',Controller:$p,Kind:'ATTACK',SourceZone:'Hand');$s=FaBGetState();$s['pendingPayment']=['player'=>$p,'uid'=>intval($twin->UniqueID),'cost'=>0,'kind'=>'ATTACK','fromZone'=>'Hand','returnWindow'=>'ACTION','returnCombatStep'=>'NONE'];FaBSetState($s);FaBRunSourceMacro('PrepareCard',$p,'twin_drive_red',['mzID'=>$ref($twin)]);$answer($p,'2');$check(FaBARCEffect($p,'ARC_BOOSTED')===2&&GetResources($p)===1&&intval(FaBObjectCounters($driver)['STEAM'])===2,'Twin boost repeated Hyper Driver or missed boost.');
 // Scrap costs only use our own graveyard and record distinct cards.
 $evoReset($p);$scrap=AddGraveyard($p,CardID:'fuel_injector_blue',Owner:$p);$enemy=AddGraveyard(1,CardID:'proto_base_head',Owner:1);$uid=$macro($p,'scrap_prospector_red','PrepareCard','Stack');$answer($p,$ref($scrap));$check(FaBFindUID(intval($scrap->UniqueID))['zone']==='Banish'&&FaBFindUID(intval($enemy->UniqueID))['zone']==='Graveyard'&&FaBARCCard($uid,'evoScrap')===1,'Scrap ownership or count incorrect.');
 // Dash sees only her own top card and pays the extra resource even off turn.
 $evoReset($p);GetHero($p)[0]->CardID='dash_database';$top=AddDeck($p,CardID:'fuel_injector_blue',Owner:$p);$next=AddDeck($p,CardID:'medkit_blue',Owner:$p);$check(FaBEVODeckView($p,true)->CardID==='fuel_injector_blue'&&FaBEVODeckView($p,false)===null&&FaBEVODeckView(1,true)===null,'Dash deck view leaked or omitted top.');SetTurnPlayer(1);$check(CanPlayCard($p,$ref($top))&&!CanPlayCard($p,$ref($next)),'Dash accepted a non-top card.');$before=GetResources($p);$check(DoPlayCard($p,$ref($top)),'Dash top play failed.');$check(GetResources($p)===$before-1&&FaBEVOEffect($p,'DASH_PLAY')===1&&!CanPlayCard($p,$ref($next)),'Dash surcharge or once-turn limit incorrect.');
 // Evo Upgrade follows equipped count live and never borrows opponents equipment.
 $evoReset($p);$a=$attack($p,'terminator_tank_red');foreach(['head','chest','arms','legs'] as $slot)AddEquipment(1,CardID:'evo_sentry_base_'.$slot.'_red',Owner:1,Controller:1);$check(FaBEVOPower($p,$a)===0,'Upgrade borrowed opposing equipment.');foreach(['head','chest','arms','legs'] as $slot)AddEquipment($p,CardID:'evo_sentry_base_'.$slot.'_red',Owner:$p,Controller:$p);$check(FaBCardCost($a,$p)===3&&FaBAttackPower(FaBGetState())===9&&FaBDYNOverpower($a,FaBGetState()),'Four-Evo upgrade incorrect.');FaBMONDestroy(intval(GetEquipment($p)[0]->UniqueID));$check(FaBAttackPower(FaBGetState())===6,'Upgrade power did not update after equipment left.');
 // Singularity preserves life, moves old components and materials into soul, and doubles Steel Soul.
 $evoReset($p);GetHero($p)[0]->CardID='teklovossen';AddHealth($p,11);AddWeapons($p,CardID:'teklo_leveler',Owner:$p,Controller:$p);foreach(['memory','processor','controller','tower'] as $part){$o=AddEquipment($p,CardID:'evo_steel_soul_'.$part.'_blue',Owner:$p,Controller:$p);FaBEVOCounter($o,'SUBCARDS',['proto_base_head']);}$uid=$macro($p,'singularity_red');$check(GetHero($p)[0]->CardID==='teklovossen_the_mechropotent'&&GetHealth($p)===11&&FaBEvoCount($p)===4&&count(FaBChoiceRefs($p,'Soul'))===10,'Singularity transformation incorrect.');$check(FaBEVOEffect($p,'INTELLECT')===2,'Mechropotent failed doubled Steel Soul.');$mh=GetHero($p)[0];$check(FaBDYNWeaponCanAttack($p,FaBFindUID(intval($mh->UniqueID))),'Mechropotent cannot attack.');
 // Its equipment defense must leave the actual hero available as a target.
 $s=FaBGetState();$s['window']='DEFEND_DECLARE';$s['defender']=$p;$s['attacker']=1;$s['attackTarget']=['type'=>'HERO','player'=>$p,'uid'=>intval($mh->UniqueID)];$s['chainLink']=1;$s['combatOpen']=true;FaBSetState($s);$check(FaBDeclareBlock($p,$ref($mh))&&count(FaBChoiceRefs($p,'Hero'))===1&&!FaBCanBlock($p,$ref($mh)),'Mechropotent defense removed or duplicated hero.');FaBCleanupResolvedLink(FaBGetState());FaBCloseCombatChain();$check(intval((FaBObjectCounters(GetHero($p)[0])['DEFENSE']??0))===1,'Mechropotent lost Battleworn counter.');
 // Multiplayer targeting and mandatory equipment remain tied to the selected hero.
 $evoReset($p);$target=AddEquipment(1,CardID:'teklo_base_head',Owner:1,Controller:1);$other=AddEquipment($p,CardID:'teklo_base_head',Owner:$p,Controller:$p);FaBEVOStasis($ref($target));$check(FaBEVOLocked(1,intval($target->UniqueID),'NO_ACTIVATE')&&!FaBEVOLocked($p,intval($other->UniqueID),'NO_ACTIVATE'),'Stasis affected another hero.');
 $evoReset($p);$a=$attack($p,'heavy_artillery_red');AddEquipment($p,CardID:'evo_sentry_base_head_red',Owner:$p,Controller:$p);$block=AddHand(1,CardID:'zero_to_sixty_red',Owner:1);$s=FaBGetState();$s['window']='DEFEND_DECLARE';FaBSetState($s);$check(!FaBCanBlock(1,$ref($block)),'Heavy Artillery accepted cheap attack block.');
 // A normal Stasis play fires item-entry events exactly once; leaving only fires its lock.
 $evoReset($p);$shot=AddWeapons($p,CardID:'symbiosis_shot',Owner:$p,Controller:$p);FaBEVOCounter($shot,'STEAM',5);$target=AddEquipment(1,CardID:'teklo_base_head',Owner:1,Controller:1);$cell=AddArena($p,CardID:'stasis_cell_blue',Owner:$p,Controller:$p);FaBResolveRules($p,$cell,$cell);
 for($i=0;$i<8&&GetDecisionQueue($p);++$i){$q=GetDecisionQueue($p)[0];$answer($p,$q->Type==='MZMODAL'?'0':$ref($target));}
 $check(!FaBHasPendingDecision()&&intval(FaBObjectCounters($shot)['STEAM'])===6&&FaBEVOLocked(1,intval($target->UniqueID),'NO_ACTIVATE'),'Played Stasis missed entry event or lock.');FaBMONDestroy(intval($cell->UniqueID));if(GetDecisionQueue($p))$answer($p,$ref($target));$check(intval(FaBObjectCounters($shot)['STEAM'])===6,'Leaving Stasis fired another item-entry event.');FaBEVOExpire(1);$check(FaBEVOLocked(1,intval($target->UniqueID),'NO_ACTIVATE'),'Stasis expired during its application turn.');SetTurnNumber(intval(GetTurnNumber())+1);FaBEVOExpire(1);$check(!FaBEVOLocked(1,intval($target->UniqueID),'NO_ACTIVATE'),'Stasis survived the target next turn.');
 // Activated Evo abilities pay the selected material before their effect resolves.
 $evoReset($p);$eq=AddEquipment($p,CardID:'evo_engine_room_yellow',Owner:$p,Controller:$p);FaBEVOCounter($eq,'SUBCARDS',['proto_base_chest']);$check(FaBARCActivate($p,FaBFindUID(intval($eq->UniqueID)),0),'Evo activation failed.');if(GetDecisionQueue($p))$answer($p,explode('&',GetDecisionQueue($p)[0]->Param)[0]);$check(FaBEVOUnder($eq)===[]&&count(FaBChoiceRefs($p,'Graveyard',['base'=>'proto_base_chest']))===1,'Evo ability did not pay its material.');$top=FaBStackTop();if($top)DoResolveCard($p,$ref($top));$check(FaBEVOEffect($p,'WEAPON_DISCOUNT')===1,'Paid Evo ability failed to resolve.');
 // Nitro Mechanoid inherits cards beneath transformed components, including Hyper-X3.
 $evoReset($p);$targets=[];for($i=0;$i<3;++$i){$o=AddArena($p,CardID:'hyper_driver_red',Owner:$p,Controller:$p);$targets[]=$ref($o);}foreach(['hyper_x3','teklo_foundry_heart','galvanic_bender','achilles_accelerator'] as $id){$o=AddEquipment($p,CardID:$id,Owner:$p,Controller:$p);if($id==='hyper_x3')FaBEVOCounter($o,'SUBCARDS',['hyper_driver_blue']);$targets[]=$ref($o);}$o=AddWeapons($p,CardID:'teklo_plasma_pistol',Owner:$p,Controller:$p);$targets[]=$ref($o);$construct=AddArena($p,CardID:'construct_nitro_mechanoid_yellow',Owner:$p,Controller:$p);FaBDYNConstruct($p,intval($construct->UniqueID),implode('&',$targets));$f=FaBFindUID(intval($construct->UniqueID));$check($f['object']->CardID==='nitro_mechanoid'&&count(FaBObjectCounters($f['object'])['DYN_MATERIAL']??[])===9,'Nitro discarded material beneath Hyper-X3.');
 // Explicit variable costs scale XXX/XX/X instead of treating X as zero.
 $evoReset($p);AddResources($p,10);$xcard=AddStack(CardID:'meganetic_lockwave_blue',Controller:$p,Kind:'ACTION');$s=FaBGetState();$s['pendingPayment']=['player'=>$p,'uid'=>intval($xcard->UniqueID),'cost'=>0];FaBSetState($s);FaBEVOSetX(intval($xcard->UniqueID),3);$check(FaBGetState()['pendingPayment']['cost']===9,'Triple-X payment incorrect.');$s=FaBGetState();$s['pendingPayment']['cost']=2;FaBSetState($s);$check(FaBEVOMaxVariableCost($p,intval($xcard->UniqueID))===2,'Variable-cost maximum ignored a fixed tax.');FaBEVOSetX(intval($xcard->UniqueID),3);$check(FaBGetState()['pendingPayment']['cost']===8,'Variable payment exceeded available resources after a tax.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "EVO rule outcomes passed in duels and four-seat UPF.\n";

