<?php
require_once __DIR__.'/hnt_test.php';
$failures=[];
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id,'Owner'=>$p,'Controller'=>$p]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $seat){foreach(['Temp','Inventory'] as $z){$get='Get'.$z;$a=&$get($seat);$a=[];}}};
foreach([2,4] as $p){
 $reset($p);GetHero($p)[0]->CardID='cindra';$a=$attack($p,'tag_the_target_red');FaBHNTMark(1);$before=GetHealth(1);DoDamage($p,$ref($a),1,1);$check(FaBHNTMarked(1),'Damage without a hit removed marked.');OnHit($p,$ref($a),1);$check(FaBHNTMarked(1)&&count(FaBMONArena($p,'fealty'))===1,'Hit must remove old mark, reward Cindra, then mark again.');
 $reset($p);GetHero($p)[0]->CardID='arakni_marionette';$a=$attack($p,'plunge_the_prospect_red');FaBHNTMark(1);$power=FaBAttackPower(FaBGetState());OnHit($p,$ref($a),1);$check(!FaBHNTMarked(1)&&FaBAttackPower(FaBGetState())===$power-2&&FaBAttackHasGoAgain(FaBGetState(),$a),'Arakni hit must keep triggered go again but lose both marked power bonuses.');
 $reset($p);GetHero($p)[0]->CardID='fang';$w=AddWeapons($p,CardID:'obsidian_fire_vein',Owner:$p,Controller:$p);$a=$attack($p,'mark_the_prey_red');FaBHNTMark(1);FaBHNTMark($p);if($p===4)FaBHNTMark(3);FaBHNTPseudoHit($p,intval($w->UniqueID),1,1);$check(!FaBHNTMarked(1)&&FaBHNTMarked($p)&&($p!==4||FaBHNTMarked(3))&&count(FaBMONArena($p,'fealty'))===1,'Flick removed another hero mark or failed to trigger Fang.');FaBHNTPseudoHit($p,intval($w->UniqueID),1,0);$check(count(FaBMONArena($p,'fealty'))===1,'Prevented flick counted as a hit.');
 $reset($p);GetHero($p)[0]->CardID='cindra';$w=AddWeapons($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$a=$attack($p,'bite_red');FaBHNTMark(1);FaBRunSourceMacro('AttackDeclared',$p,$a->CardID,['mzID'=>$ref($a)]);$answer($p,$ref($w));$check(FaBFindUID(intval($w->UniqueID))['zone']==='Graveyard'&&!FaBHNTMarked(1)&&count(FaBMONArena($p,'fealty'))===1,'Bite did not finish flick damage, marked removal, Fealty, and dagger destruction.');
 $reset($p);FaBHNTAdd($p,'FEALTY_NEXT');$o=AddHand($p,CardID:'dragon_power_red',Owner:$p,Controller:$p);FaBHNTAdd($p,'ONLY_DRACONIC');$check(FaBHNTCanPlay($p,$o),'Fealty must make a prospective card legal under Draconic restriction.');FaBHNTPlayed($p,$o,'Hand');$check(FaBHasType($o,'Draconic')&&!FaBHNTCount($p,'FEALTY_NEXT'),'Fealty did not apply to precisely the next played card.');$next=AddHand($p,CardID:'dragon_power_blue');$check(!FaBHNTCanPlay($p,$next),'Draconic-only restriction allowed next non-Draconic card.');
 $reset($p);GetHero($p)[0]->CardID='fang';$w=AddWeapons($p,CardID:'obsidian_fire_vein',Owner:$p,Controller:$p);$spec=['cardID'=>$w->CardID,'sourceUID'=>intval($w->UniqueID),'cost'=>1,'timing'=>'ACTION'];$check(FaBWTRAbilityCost($p,$spec)===1,'Fang discounted below three Fealty.');FaBHVYToken($p,'fealty',3);$check(FaBWTRAbilityCost($p,$spec)===0,'Fang missed three-Fealty discount.');
 $reset($p);$t=FaBWTRCreateArena($p,'fealty');FaBHNTEnd($p);$check(FaBFindUID(intval($t->UniqueID))['zone']==='Arena','New Fealty destroyed at end phase.');FaBHNTClear($p,'FEALTY');FaBHNTEnd($p);$check(FaBFindUID(intval($t->UniqueID))['zone']==='Graveyard','Old Fealty survived without qualifying event.');
 $reset($p);GetHero($p)[0]->CardID='arakni_web_of_deceit';FaBHNTMark(1);FaBHNTMark($p);$hp=GetHealth($p);FaBHNTEnd($p);$check(in_array(GetHero($p)[0]->CardID,FaBHNTAgents(),true)&&FaBHNTMarked($p)&&GetHealth($p)===$hp,'Random Agent transition reset life or mark.');$stack=&GetStack();$stack=[];FaBHNTEnd($p);$check(GetHero($p)[0]->CardID==='arakni_web_of_deceit','Agent did not return to base hero.');
 $reset($p);$g=AddGraveyard($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$kiss=AddGraveyard($p,CardID:'kiss_of_death_red');$check(str_contains(FaBArakniRetrieveTargets($p),$ref($g))&&!str_contains(FaBArakniRetrieveTargets($p),$ref($kiss)),'Retrieve offered an attack action with Dagger subtype.');FaBHNTEquip($p,$ref($g));$check(FaBFindUID(intval($g->UniqueID))['zone']==='Weapons','Dagger did not equip from graveyard.');
 $reset($p);$w=AddWeapons($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$a=$attack($p,'kunai_of_retribution');FaBSetObjectCounter($a,'WEAPON_UID',intval($w->UniqueID));FaBHNTPlayed($p,$a,'Weapons');$check(FaBAttackHasGoAgain(FaBGetState(),$a),'Kunai weapon attack missing go again.');FaBHNTClose();$check(FaBFindUID(intval($w->UniqueID))['zone']==='Graveyard','Kunai was not destroyed on close.');
 $reset($p);$w=AddWeapons($p,CardID:'obsidian_fire_vein',Owner:$p,Controller:$p);FaBCRUUseWeapon($w);FaBHNTExtra(intval($w->UniqueID));FaBHNTExtra(intval($w->UniqueID));FaBCRUUseWeapon($w);$check(FaBCRUWeaponReady($w),'Repeated additional attacks collapsed into one.');FaBCRUUseWeapon($w);$check(!FaBCRUWeaponReady($w),'Additional dagger attacks were not consumed.');
 $reset($p);$a=$attack($p,'mark_the_prey_red');FaBHNTMark(1);$g=AddGraveyard($p,CardID:'kiss_of_death_red',Owner:$p,Controller:$p);$macro($p,'take_up_the_mantle_yellow');$answer($p,$ref($a));$answer($p,$ref($g));$live=FaBFindUID(intval($a->UniqueID))['object'];$check($live->CardID==='kiss_of_death_red'&&in_array('WTR_POWER:3',(array)$live->TurnEffects,true),'Mantle copy lost its resolved power bonus.');FaBMoveUID(intval($a->UniqueID),'Graveyard',$p);$check(FaBFindUID(intval($a->UniqueID))['object']->CardID==='mark_the_prey_red','Copy effect changed physical card identity in graveyard.');
 $reset($p);$o=AddArena($p,CardID:'null_time_zone_blue',Owner:$p,Controller:$p);FaBARCSetCard(intval($o->UniqueID),'hntName','Zap');$h=AddHand(1,CardID:'zap_red');$check(FaBHNTNamed('zap_red')&&!FaBHNTCanPlay(1,$h),'Null Time Zone failed to prohibit named card.');FaBMONDestroy(intval($o->UniqueID));$check(!FaBHNTNamed('zap_red'),'Null Time Zone restriction outlived the item.');
 $reset($p);$macro($p,'calming_breeze_red');$a=AddGraveyard(1,CardID:'zap_red');$hp=GetHealth($p);for($i=0;$i<4;++$i)DoDamage(1,$ref($a),$p,2,'PHYSICAL');$check(GetHealth($p)===$hp-5,'Calming Breeze prevented wrong number of damage events.');
 $reset($p);$ring=FaBWTRCreateArena($p,'ring_of_roses_yellow');$spell=AddGraveyard($p,CardID:'zap_red');$hp=GetHealth($p);DoDamage($p,$ref($spell),1,1,'ARCANE');DoDamage($p,$ref($spell),1,1,'ARCANE');$check(GetHealth($p)===$hp+1,'Ring of Roses did not trigger exactly once.');
 $reset($p);$a=$attack($p,'plunge_the_prospect_red');$e=AddEquipment(1,CardID:'red_alert_vest',Owner:1,Controller:1);$before=FaBCurrentDefense($e,1);FaBArakniReactionEvent($p,true);$check(FaBCurrentDefense($e,1)===$before+1,'Red Alert failed to see attack reaction.');
 $reset($p);GetHero($p)[0]->CardID='cindra';$g1=AddGraveyard($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$g2=AddGraveyard($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$before=GetResources($p);$hntHero=GetHero($p)[0];$check(FaBARCActivate($p,FaBFindUID(intval($hntHero->UniqueID)),0),'Cindra activation rejected.');DoResolveCard($p,$ref(FaBStackTop()));$answer($p,$ref($g1).'&'.$ref($g2));$check(count(FaBChoiceRefs($p,'Weapons'))===2&&GetResources($p)===$before-3,'Cindra did not pay and equip two chosen daggers.');
 $reset($p);$a=$attack($p,'obsidian_fire_vein');$a->FromZone='Weapons';FaBHNTAdd($p,'DRACONIC_LINK');AddActionPoints($p,0);FaBBeginResolutionStep();$check(GetActionPoints($p)===1,'Obsidian lost go again before the resolution step granted its action point.');
 $reset($p);$a=$attack($p,'grow_wings_red');AddActionPoints($p,0);FaBBeginResolutionStep();$check(GetActionPoints($p)===0,'Grow Wings counted itself as the previous Draconic attack.');
 $reset($p);GetHero($p)[0]->CardID='arakni_web_of_deceit';$trap=AddDeck($p,CardID:'frailty_trap_red',Owner:$p,Controller:$p);FaBHNTBecome($p,5);DoResolveCard($p,$ref(FaBStackTop()));$q=GetDecisionQueue($p)[0];$answer($p,explode('&',explode('|',$q->Param,3)[2])[0]);$f=FaBFindUID(intval($trap->UniqueID));$check($f['zone']==='Banish'&&!empty($f['object']->FaceDown)&&!empty($f['object']->PlayableFromBanish),'Trap-door failed to hide and authorize searched trap.');FaBHNTStart($p);$check(empty($f['object']->PlayableFromBanish),'Trap-door permission survived next start phase.');
 $reset($p);$a=$attack(1,'obsidian_fire_vein',$p);$w=AddWeapons(1,CardID:'obsidian_fire_vein',Owner:1,Controller:1);FaBSetObjectCounter($a,'WEAPON_UID',intval($w->UniqueID));FaBHNTAdd($p,'BELLONA',2,['uid'=>intval($w->UniqueID)]);FaBHNTAdd(1,'CALM',3);$hp=GetHealth(1);DoDamage(1,$ref($a),$p,2);DoResolveCard($p,$ref(FaBStackTop()));$check(GetHealth(1)===$hp-2&&FaBHNTCount(1,'CALM')===3,'Bellona reflection was prevented or consumed a prevention event.');
 $reset($p);$a=$attack($p,'mark_the_prey_red');FaBARCRecordAction($p);$o=AddHand($p,CardID:'oath_of_loyalty_red');$check(!FaBHNTCanPlay($p,$o),'Oath was allowed after an attack action.');
 $reset($p);GetHero(1)[0]->CardID='arakni_5lp3d_7hru_7h3_cr4x';$a=$attack($p,'mark_the_prey_red');FaBHNTPlayed($p,$a,'Hand');$check(in_array('GO_AGAIN',(array)$a->TurnEffects,true),'Chaos Arakni did not grant the first Stealth attack made by another hero go again.');
 $reset($p);$macro($p,'spur_locked_blue');$choices=[];foreach(FaBLiveSeats() as $v){$choices[$v]=$v===$p?6:1;AddDeck($v,CardID:'zap_blue');}$hp=GetHealth($p);foreach($choices as $v=>$n){if($v!==$p)$check(empty(FaBGetState()['hntRevealedNumbers']),'Spur revealed choices before all heroes chose.');$answer($v,strval($n));}$q=GetDecisionQueue($p)[0];$answer($p,explode('&',$q->Param)[0]);$check(GetHealth($p)===$hp-6&&FaBHandCount($p)===1&&FaBGetState()['hntRevealedNumbers']===$choices,'Spur did not reveal choices and reward the unique highest chooser.');
 $check(FaBHNTSpurWinner([1=>3,$p=>6])===$p&&FaBHNTSpurWinner([1=>6,$p=>6])===0,'Spur Locked unique highest/tie handling is wrong.');
 $reset($p);$w=AddWeapons($p,CardID:'obsidian_fire_vein',Owner:$p,Controller:$p);FaBHNTWrath($p);$later=AddWeapons($p,CardID:'kunai_of_retribution',Owner:$p,Controller:$p);$check(FaBHNTWrathAmount(intval($w->UniqueID))===1&&FaBHNTWrathAmount(intval($later->UniqueID))===0,'Wrath incorrectly affected a dagger equipped after resolution.');FaBHNTClose();$check(FaBHNTWrathAmount(intval($w->UniqueID))===0,'Wrath discount outlived the combat chain.');
 $reset($p);$a=$attack($p,'obsidian_fire_vein');$s=FaBGetState();$s['window']='PRIORITY';FaBSetState($s);$r1=AddStack(CardID:'incision_red',Controller:$p,Kind:'ATTACK_REACTION',SourceZone:'Hand');$r2=AddStack(CardID:'affirm_loyalty_red',Controller:$p,Kind:'ATTACK_REACTION',SourceZone:'Hand');DoResolveCard($p,$ref($r2));$answer($p,$ref($a));DoResolveCard($p,$ref($r1));$answer($p,$ref($a));$check(FaBGetState()['window']==='REACTION'&&FaBStackCount()===0,'Resolving stacked reactions left an empty generic priority window.');
 $reset($p);$kiss=AddCombatChain($p,CardID:'kiss_of_death_red',Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:1);$a=$attack($p,'bite_red');$check(str_contains(FaBHNTDaggers($p),$ref($kiss)),'Kiss of Death was excluded from daggers in play.');$hp=GetHealth(1);FaBRunSourceMacro('AttackDeclared',$p,$a->CardID,['mzID'=>$ref($a)]);$answer($p,$ref($kiss));$check(GetHealth(1)===$hp-2&&FaBFindUID(intval($kiss->UniqueID))['zone']==='Graveyard','Flicking Kiss of Death missed its hit ability or destruction.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "The Hunted mechanic outcomes passed in duels and UPF.\n";
