<?php
require_once __DIR__.'/hvy_test.php';
$failures=[];
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $s)foreach(['Temp','Inventory'] as $z){$get='Get'.$z;$a=&$get($s);$a=[];}DecisionQueueController::StoreVariable('mzID','');};
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id,'Owner'=>$p,'Controller'=>$p]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
foreach([2,4] as $p){
 $reset($p);GetHero($p)[0]->CardID='kayo';$h=AddHand($p,CardID:'clash_of_might_yellow',Owner:$p);$base=intval(CardPower($h->CardID));$check(FaBHVYOwnedPower($p,$h)===$base+1,'Kayo hand power missing.');$a=$attack($p,$h->CardID);$check(FaBHVYOwnedPower($p,$a)===$base,'Kayo buff leaked onto combat chain.');FaBDiscardChoice($p,$ref($h));$check(count(FaBMONArena($p,'might'))===1,'Kayo missed first five-base-power discard.');AddHand($p,CardID:'clash_of_might_yellow',Owner:$p);FaBDiscardRandom($p);$check(count(FaBMONArena($p,'might'))===1,'Kayo triggered twice in action phase.');
 $reset($p);GetHero($p)[0]->CardID='kayo';AddDeck($p,CardID:'clash_of_might_blue',Owner:$p);AddDeck(1,CardID:'clash_of_might_blue',Owner:1);$c=FaBHVYClash($p,1);$check($c['winner']===$p&&count(FaBChoiceRefs($p,'Deck'))===1,'Clash missed Kayo bonus or moved revealed cards.');
 $reset($p);AddDeck($p,CardID:'zap_blue');AddDeck(1,CardID:'zap_blue');$check(FaBHVYClash($p,1)['winner']===0,'No-power clash did not tie.');
 $reset($p);GetHero($p)[0]->CardID='victor_goldmane';$d=AddDeck($p,CardID:'zap_blue');AddDeck($p,CardID:'thunk_red');AddDeck(1,CardID:'clash_of_might_blue');$g=FaBWTRCreateArena($p,'gold',true);$a=$attack(1,'wage_gold_red',$p);$uid=$macro($p,'test_of_strength_red','Defended','CombatChain');$check(!empty(GetDecisionQueue($p)),'Victor failed-clash replacement was not offered.');$answer($p,$ref($g));$q=GetDecisionQueue($p)[0]??null;$check($q&&$q->Type==='MZCHOOSE','Victor missing revealed-card choice.');if($q)$answer($p,explode('&',$q->Param)[0]);$check(!FaBHasPendingDecision()&&count(FaBChoiceRefs($p,'Temp'))===0&&count(FaBMONArena($p,'might'))===1&&count(FaBChoiceRefs($p,'Hand'))===1,'Victor re-clash/reward/preview cleanup failed.');
 $reset($p);GetHero($p)[0]->CardID='victor_goldmane';AddDeck($p,CardID:'thunk_red');FaBHVYToken($p,'gold',1,1,true);$check(FaBHandCount($p)===0,'Victor drew for opponent-controlled Gold creation.');FaBHVYToken($p,'gold',1,$p,true);$check(FaBHandCount($p)===1,'Victor did not draw for own Gold creation.');
 $reset($p);GetHero($p)[0]->CardID='olympia';$a=$attack($p,'wage_gold_red');$uid=intval($a->UniqueID);FaBHVYWager($p,$uid,1,['gold']);FaBHVYWager($p,$uid,1,['might','vigor']);$s=FaBGetState();$s['attackHit']=true;FaBSetState($s);FaBHVYResolveWagers($p,$uid);$check(count(FaBMONArena($p,'gold'))===2&&count(FaBMONArena($p,'might'))===1&&count(FaBMONArena(1,'gold'))===0,'Olympia wager rewards wrong or repeated extra Gold.');FaBHVYResolveWagers($p,$uid);$check(count(FaBMONArena($p,'gold'))===2,'Wager paid twice.');
 $reset($p);$a=$attack($p,'wage_gold_red');FaBHVYWager($p,intval($a->UniqueID),1,['gold']);FaBHVYAdd($p,'DOUBLE_DOWN');FaBHVYResolveWagers($p,intval($a->UniqueID));$check(count(FaBMONArena(1,'gold'))===2&&!FaBMONArena($p,'gold'),'Missed wager or Double Down rewarded wrong hero.');
 if($p===4){$reset($p);$a=$attack($p,'wage_gold_red');$uid=intval($a->UniqueID);FaBHVYWager($p,$uid,1,['gold']);FaBHVYWager($p,$uid,2,['might']);$s=FaBGetState();$s['targetDamage']=['1'=>['damage'=>0],'2'=>['damage'=>3]];$s['attackHit']=true;FaBSetState($s);FaBHVYResolveWagers($p,$uid);$check(count(FaBMONArena(1,'gold'))===1&&count(FaBMONArena($p,'might'))===1&&!FaBMONArena(2,'might')&&!FaBMONArena(3,'gold'),'UPF wager used aggregate hit instead of wagered hero damage.');}
 $reset($p);FaBHVYAdd(1,'RIPPLE');FaBHVYToken($p,'might',3,$p,true);FaBHVYToken($p,'vigor',1,$p,true);FaBHVYToken($p,'agility',1,$p,false);$check(count(FaBMONArena($p,'might'))===2&&!FaBMONArena($p,'vigor')&&count(FaBMONArena($p,'agility'))===1,'Ripple must reduce each action batch, not each token or activated ability.');
 $reset($p);FaBHVYToken($p,'might',1,$p,false);FaBHVYToken($p,'vigor',1,$p,false);AddResources($p,0);FaBHVYStart($p);$check(GetResources($p)===1&&!FaBMONArena($p,'vigor')&&!FaBMONArena($p,'might')&&FaBHVYControlled($p,'vigor'),'Vigor/start effects or controlled-this-turn tracking failed.');
 $reset($p);GetHero($p)[0]->CardID='kassai';$red=[];$yellow=[];foreach([1,2] as $i){$red[]=AddGraveyard($p,CardID:'wage_gold_red');$yellow[]=AddGraveyard($p,CardID:'wage_gold_yellow');}FaBDTDAdd($p,'DRAWN');$w=AddWeapons($p,CardID:'cintari_saber',Owner:$p,Controller:$p);$check(FaBHVYAbilityCost($p,['cardID'=>'cintari_saber'])===-1,'Kassai sword discount missing.');$hvyHero=GetHero($p)[0];$check(FaBARCActivate($p,FaBFindUID(intval($hvyHero->UniqueID)),0),'Kassai ability could not activate.');$answer($p,implode('&',array_map($ref,$red)));$answer($p,implode('&',array_map($ref,$yellow)));$check(count(FaBChoiceRefs($p,'Banish'))===4,'Kassai did not pay red/yellow cost.');$stack=FaBStackTop();if($stack)DoResolveCard($p,$ref($stack));$check(FaBHVYCount($p,'KASSAI_GOLD')===1,'Kassai paid ability did not resolve.');
 $reset($p);$card=AddHand($p,CardID:'agile_windup_red');$uid=intval($card->UniqueID);$check(FaBARCActivate($p,FaBFindUID($uid),0),'Windup could not activate from hand.');$check(FaBFindUID($uid)['zone']==='Graveyard','Windup discard was not paid before resolution.');$stack=FaBStackTop();if($stack)DoResolveCard($p,$ref($stack));$check(count(FaBMONArena($p,'agility'))===1,'Windup failed to create Agility.');
 $reset($p);$a=$attack(1,'wage_gold_red',$p);$w=AddWeapons($p,CardID:'parry_blade',Owner:$p,Controller:$p);$s=FaBGetState();$s['window']='DEFEND_DECLARE';FaBSetState($s);$check(FaBDeclareBlock($p,$ref($w)),'Parry Blade could not defend from weapon zone.');FaBCleanupResolvedLink(FaBGetState());FaBCloseCombatChain();$check(!FaBChoiceRefs($p,'Weapons')&&count(FaBChoiceRefs($p,'Graveyard',['base'=>'parry_blade']))===1,'Parry Blade did not blade-break.');
 $reset($p);$a=$attack(1,'wage_gold_red',$p);$eq=AddCombatChain($p,CardID:'balance_of_justice',Owner:$p,Controller:$p,FromZone:'Equipment',Role:'DEFENSE',ChainLink:1);FaBHVYClose($p,$eq);$check(FaBCurrentDefense($eq,$p)===0,'Guardwell did not reduce defense to zero.');
 $reset($p);$a=$attack(1,'wage_gold_red',$p);$eq=AddCombatChain($p,CardID:'gauntlets_of_iron_will',Owner:$p,Controller:$p,FromZone:'Equipment',Role:'DEFENSE',ChainLink:1);FaBHVYDefended($eq);FaBWTRTag($a,'WTR_POWER:3');FaBWTRTag($a,'WTR_POWER:2');$check(in_array('WTR_POWER:2',$a->TurnEffects,true)&&!in_array('WTR_POWER:3',$a->TurnEffects,true),'Iron Will did not reduce the next gain once.');
 $reset($p);$macro($p,'battered_not_broken_red');$source=AddGraveyard(1,CardID:'zap_red');$check(DoDamage(1,$ref($source),$p,1)===0&&count(FaBMONArena($p,'might'))===1,'Prevention failed to create token.');DoDamage(1,$ref($source),$p,2);$check(count(FaBMONArena($p,'might'))===1,'Prevention token triggered twice.');
 $reset($p);$a=$attack($p,'send_packing_yellow');$ar=AddArsenal(1,CardID:'zap_blue');FaBHVYSendPacking($p,intval($a->UniqueID));FaBHVYReturnPacking(intval($a->UniqueID));$check(FaBFindUID(intval($ar->UniqueID))['zone']==='Hand','Missed Send Packing failed to return arsenaled card.');
 $reset($p);$a=$attack($p,'wage_agility_red');FaBHVYNext($p,3,'Warrior','HVY_WAGER:agility');FaBHVYPlayed($p,$a,'Hand');$check(in_array('HVY_WAGER:agility',$a->TurnEffects,true),'Next Warrior wager effect was lost.');FaBHVYAttackDeclared($p,$a);$answer($p,'0');$check(count(FaBARCCard(intval($a->UniqueID),'hvyWagers',[]))===1,'Granted wager did not resolve.');
 $reset($p);GetHero($p)[0]->CardID='betsy';$a=$attack($p,'bet_big_red');FaBHVYWager($p,intval($a->UniqueID),1,['gold','might','vigor']);$before=GetResources($p);$answer($p,'1');$check(GetResources($p)===$before-2&&in_array('WTR_POWER:1',$a->TurnEffects,true)&&FaBDYNOverpower($a,FaBGetState()),'Betsy payment or bonuses missing.');
 $reset($p);$d=AddDeck(1,CardID:'zap_blue');$h=AddHand(1,CardID:'zap_red');DecisionQueueController::StoreVariable('fabSourceZone','Arsenal');AddDeck($p,CardID:'thunk_red');$uid=$macro($p,'seduce_secrets_yellow');$answer($p,$ref(GetHero(1)[0]));$q=GetDecisionQueue($p)[0];$check($q->Type==='MZREARRANGE'&&count(FaBChoiceRefs($p,'Temp'))===2&&!FaBChoiceRefs(1,'Temp'),'Seduce Secrets did not use private viewer zone.');$answer($p,$q->Param);$check(FaBFindUID(intval($d->UniqueID))['zone']==='Deck'&&FaBFindUID(intval($h->UniqueID))['zone']==='Hand'&&!FaBChoiceRefs($p,'Temp')&&FaBHandCount($p)===1,'Seduce Secrets changed inspected cards or missed arsenal draw.');
 $reset($p);FaBHVYToken($p,'deathmatch_arena',1,$p,false);AddHealth(1,1);$source=AddGraveyard($p,CardID:'zap_red');DoDamage($p,$ref($source),1,1);$check(count(FaBMONArena($p,'gold'))===$p,'Deathmatch Arena reward did not use starting hero count.');
 $reset($p);$a=$attack(1,'concuss_red',$p);FaBWTRTag($a,'WTR_POWER:1');$nasty=AddHand($p,CardID:'nasty_surprise_blue');FaBRunSourceMacro('Hit',1,'concuss_red',['mzID'=>$ref($a)]);$answer($p,$ref($nasty));$check(count(FaBMONArena($p,'agility'))===1&&count(FaBMONArena($p,'might'))===1&&count(FaBMONArena($p,'vigor'))===1,'Nasty Surprise missed opponent-controlled discard across a choice.');GameAfterEngineAction([],[]);$other=AddHand($p,CardID:'nasty_surprise_blue');FaBDiscardChoice($p,$ref($other));$check(count(FaBMONArena($p,'might'))===1,'Nasty Surprise triggered on a self discard using stale source context.');
 $reset($p);AddResources($p,0);$gold=FaBWTRCreateArena($p,'gold',true);$dd=AddHand($p,CardID:'double_down_red');$check(CanPlayCard($p,$ref($dd)),'Double Down Gold alternative was unavailable without pitch.');DoPlayCard($p,$ref($dd));$q=GetDecisionQueue($p)[0];$check(str_starts_with($q->Param,'1|1|'),'Unpayable resource alternative allowed skipping Gold.');$answer($p,$ref($gold));$check(FaBGetState()['pendingPayment']===null,'Double Down alternative left payment pending.');
 $reset($p);AddResources($p,0);for($i=0;$i<4;++$i)FaBWTRCreateArena($p,'runechant');$sonata=AddStack(CardID:'sonata_galaxia_red',Controller:$p,Kind:'ACTION',SourceZone:'Hand');$uid=intval($sonata->UniqueID);$s=FaBGetState();$s['pendingPayment']=['player'=>$p,'uid'=>$uid,'cost'=>1];FaBSetState($s);$check(FaBHVYMaxX($p,$uid)===1,'Sonata XX ignored the fixed tax.');FaBHVYSetX($uid,1);$check(FaBGetState()['pendingPayment']['cost']===0,'Sonata did not discount the chosen XX cost.');
 $reset($p);AddWeapons($p,CardID:'luminaris_angels_glow',Owner:$p,Controller:$p);$a=$attack($p,'herald_of_ravages_red');FaBHVYPlayed($p,$a,'Hand');$check(!FaBHVYGoAgain($p,$a),'Luminaris granted go again without yellow pitch.');AddPitch($p,CardID:'wage_gold_yellow');$check(FaBHVYGoAgain($p,$a),'Luminaris failed to update after a yellow pitch.');$b=AddCombatChain($p,CardID:'herald_of_ravages_red',Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:2);FaBHVYPlayed($p,$b,'Hand');$check(!FaBHVYGoAgain($p,$b),'Luminaris granted go again to the second Herald.');
 $reset($p);$a=$attack($p,'down_but_not_out_red');AddHealth($p,5);AddEquipment(1,CardID:'glory_seeker',Owner:1,Controller:1);$g=FaBWTRCreateArena(1,'gold',true);FaBHVYAttackDeclared($p,$a);FaBMONDestroy(intval($g->UniqueID));$check(FaBARCCard(intval($a->UniqueID),'hvyDown')&&FaBAttackPower(FaBGetState())===intval(CardPower($a->CardID))+3,'Down But Not Out did not retain its attack-trigger bonuses.');
 $reset($p);$a=$attack($p,'wage_gold_red');$uid=intval($a->UniqueID);FaBHVYAnte($p,$uid,1,'0,1,2,3');$check(count(FaBARCCard($uid,'hvyWagers',[]))===3&&in_array('WTR_POWER:3',$a->TurnEffects,true),'Up the Ante modes did not wager separately before counting power.');
 $reset($p);$d=AddGraveyard($p,CardID:'graven_call',Owner:$p);$silver1=FaBWTRCreateArena($p,'silver');$silver2=FaBWTRCreateArena($p,'silver');$check(FaBARCActivate($p,FaBFindUID(intval($d->UniqueID)),0),'Graven Call could not activate from graveyard.');$answer($p,$ref($silver1).'&'.$ref($silver2));$stack=FaBStackTop();if($stack)DoResolveCard($p,$ref($stack));$f=FaBFindUID(intval($d->UniqueID));$check($f['zone']==='Weapons'&&intval(FaBObjectCounters($f['object'])['POWER']??0)===1,'Graven Call did not equip with its power counter.');
 $reset($p);$a=$attack(1,'wage_gold_red',$p);$head=AddEquipment($p,CardID:'headliner_helm',Owner:$p,Controller:$p);AddHealth($p,1);$s=FaBGetState();$s['window']='DEFEND_DECLARE';FaBSetState($s);$check(FaBCanBlock($p,$ref($head))&&FaBCurrentDefense($head,$p)===$p-1,'Variable-defense equipment cannot defend or counted the wrong heroes.');
 $reset($p);foreach(['graven_call','cintari_sellsword'] as $id){$a=$attack($p,$id);$check(FaBAttackHasGoAgain(FaBGetState(),$a),$id.' attack ability lost go again.');}
 $reset($p);$six=AddHand($p,CardID:'clash_of_might_red');$uid=$macro($p,'no_fear_red');FaBHVYNoFear($p,$uid,$ref($six));$check(FaBFindUID(intval($six->UniqueID))['zone']==='Banish','No Fear failed its banish cost.');FaBCloseCombatChain();FaBHVYEnd();$check(FaBFindUID(intval($six->UniqueID))['zone']==='Hand','No Fear card failed to return after the combat chain closed.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "HVY mechanic outcomes passed in duels and UPF.\n";
