<?php
require_once __DIR__.'/mpg_test.php';
$failures=[];
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $v)foreach(['Temp','Inventory'] as $z){$get='Get'.$z;$a=&$get($v);$a=[];}};
$run=function(int $p,object $o,string $name='ResolveCard',array $params=[])use($ref){FaBRunSourceMacro($name,$p,$o->CardID,['mzID'=>$ref($o)]+$params);};
$resolve=function()use($answer){for($i=0;$i<50;$i++){if(FaBHasPendingDecision())return;$o=FaBStackTop();if(!$o)return;DoResolveCard(intval($o->Controller),'Stack-'.$o->mzIndex);}throw new RuntimeException('Stack did not settle');};
$gold=fn($p)=>count(FaBChoiceRefs($p,'Arena',['base'=>'gold']));
foreach([2,4] as $p){
 $reset($p);$a=FaBWTRCreateArena($p,'promising_terrain_blue');FaBHVYToken($p,'seismic_surge',2);$check(FaBMPGSurges($p)===3,'Promising Terrain did not replace a batch of two with three');AddDeck($p,CardID:'zap_blue');$hp=GetHealth($p);FaBMPGBegin($p);$check(FaBHandCount($p)===1&&GetHealth($p)===$hp+1,'Promising Terrain missed draw/life before Surges expire');
 $reset($p);$a=FaBWTRCreateArena($p,'geyser_of_seismic_stirrings_yellow');FaBMPGEnd($p);$check(FaBMPGSurges($p)===1&&intval(FaBObjectCounters($a)['ENERGY'])===1,'Geyser first end phase');FaBMPGEnd($p);$check(FaBMPGSurges($p)===2&&FaBFindUID(intval($a->UniqueID))['zone']==='Graveyard','Geyser did not expire on final counter');
 $reset($p);GetHero($p)[0]->CardID='valda_seismic_impact';AddDeck(1,CardID:'zap_blue');AddDeck(1,CardID:'zap_red');DoDrawCard(1,2);$check(FaBMPGSurges($p)===2,'Valda did not observe opponent drawing two');AddDeck($p,CardID:'zap_blue');DoDrawCard($p,1);$check(FaBMPGSurges($p)===2,'Valda triggered on her own draw');FaBHVYToken($p,'seismic_surge');FaBMPGStart($p);$a=$attack($p,'grind_them_down_red');FaBEVRAttack($p,$a);$check(FaBCurrentAttackHasKeyword(FaBGetState(),'Dominate'),'Valda did not grant crush dominate');
 $reset($p);FaBHVYToken($p,'seismic_surge');FaBWTRStartTurn($p);$a=$attack($p,'aftershock_red');$run($p,$a,'AttackDeclared');$check(FaBMPGSurges($p)===1,'Aftershock forgot Surge controlled earlier this turn');
 $reset($p);$a=FaBWTRCreateArena($p,'ley_line_of_the_old_ones_blue');$check(FaBMPGSurges($p)===1,'Ley Line entry');DoDamage($p,'',1,1);$check(FaBMPGSurges($p)===2,'Ley Line damage trigger');
 $reset($p);$a=AddHand($p,CardID:'solid_ground_blue',Owner:$p,Controller:$p);FaBHVYToken($p,'seismic_surge',2);$check(FaBCardCost($a,$p)===1,'Solid Ground discount');
 $reset($p);$a=$attack($p,'little_big_foot_red');$base=FaBAttackPower(FaBGetState());AddPitch($p,CardID:'disable_blue');AddPitch($p,CardID:'crush_confidence_red');$check(FaBAttackPower(FaBGetState())===$base+6,'Little Big Foot pitch power');
 $reset($p);$a=AddEquipment($p,CardID:'testament_of_valahai',Owner:$p,Controller:$p);FaBHVYToken($p,'seismic_surge',6);$check(FaBCurrentDefense($a,$p)===5,'Testament six Surge defense');$a->Role='DEFENSE';FaBHVYClose($p,$a);$check(FaBCurrentDefense($a,$p)===0,'Guardwell did not remove all current defense');
 // A next-turn restriction survives intervening UPF seats and expires after its named seat.
 $reset($p);FaBMPGDuration(1,'NO_AURA');$check(FaBHVYToken(1,'seismic_surge')!==null,'Renounce restriction began too early');$s=FaBResetWindowState();FaBSetState($s);FaBMPGStart($p);FaBMPGExpire($p);$check(count(FaBGetState()['mpgDurations'])===1,'Other seat consumed next-turn restriction');FaBMPGStart(1);$before=FaBMPGSurges(1);FaBHVYToken(1,'seismic_surge');$check(FaBMPGSurges(1)===$before,'Renounce allowed aura token during target turn');$check(FaBHVYToken(1,'gold')!==null,'Renounce blocked non-aura token');FaBMPGExpire(1);$check(FaBHVYToken(1,'seismic_surge')!==null,'Renounce did not expire');
 $reset($p);FaBMPGDuration(1,'NO_NAMED_AURA','until',['card'=>'seismic_surge']);$check(FaBHVYToken(1,'seismic_surge')===null&&FaBHVYToken(1,'quicken')!==null,'Break Stature blocked wrong token');
 $reset($p);GetHero(1)[0]->CardID='bravo';$a=$attack($p,'annexation_of_all_things_known_yellow');$r=AddArsenal(1,CardID:'nimblism_red',Owner:1,Controller:1,FaceDown:0);$run($p,$a,'Hit',['amount'=>4]);$s=FaBGetState();$s['window']='ACTION';$s['combatOpen']=false;FaBSetState($s);SetPriorityPlayer($p);$check(CanPlayCard($p,$ref($r)),'Annexation did not allow opponent face-up arsenal');SetPriorityPlayer(1);SetTurnPlayer(1);AddActionPoints(1,1);$check(!CanPlayCard(1,$ref($r)),'Annexation let owner play face-up arsenal');$r->FaceDown=1;$check(!FaBMPGCanStealPlay($p,FaBIdentityFromMZ($ref($r))),'Annexation exposed face-down arsenal');$r->FaceDown=0;FaBMPGStart($p);FaBMPGExpire($p);$check(!FaBMPGCanStealPlay($p,FaBIdentityFromMZ($ref($r))),'Annexation lasted beyond next controller turn');
 $reset($p);$a=AddArena(1,CardID:'seismic_surge',Owner:1,Controller:1,Counters:['ENERGY'=>2]);FaBMPGStealAura($p,$ref($a));$f=FaBFindUID(intval($a->UniqueID));$check($f['player']===$p&&$f['object']->Owner===1&&intval(FaBObjectCounters($f['object'])['ENERGY'])===2,'Aura theft lost controller/owner/counters');
 $reset($p);$old=AddEquipment($p,CardID:'ironrot_plate',Owner:$p,Controller:$p);$a=AddEquipment(1,CardID:'testament_of_valahai',Owner:1,Controller:1,Counters:['DEFENSE'=>1]);FaBMPGEquip($p,$ref($a));$f=FaBFindUID(intval($a->UniqueID));$check($f['player']===$p&&$f['object']->Owner===1&&intval(FaBObjectCounters($f['object'])['DEFENSE'])===1,'Equipment theft lost counters/ownership');
 $reset($p);$a=$attack($p,'crush_confidence_red');FaBWTRTag($a,'DOMINATE');$c=AddHand(1,CardID:'fearless_confrontation_blue',Owner:1,Controller:1);$s=FaBGetState();$s['window']='REACTION';$s['combatStep']='REACTION';FaBSetState($s);SetPriorityPlayer(1);$power=FaBAttackPower($s);$check(FaBARCActivate(1,FaBIdentityFromMZ($ref($c)),0),'Fearless activation unavailable to defending hero');$resolve();$check(FaBFindUID(intval($c->UniqueID))['zone']==='Graveyard'&&FaBAttackPower(FaBGetState())===$power-1&&!FaBCurrentAttackHasKeyword(FaBGetState(),'Dominate'),'Fearless missed discard/power/dominate');FaBWTRTag($a,'DOMINATE');$check(!FaBCurrentAttackHasKeyword(FaBGetState(),'Dominate'),'Attack regained dominate');
 $reset($p);$a=$attack($p,'headbutt_blue');$helm=AddEquipment(1,CardID:'ironrot_helm',Owner:1,Controller:1);$chest=AddEquipment(1,CardID:'ironrot_plate',Owner:1,Controller:1);$check(FaBMPGBlockLegal($helm)&&!FaBMPGBlockLegal($chest),'Headbutt equipment restriction');
 // Tectonic Instability asks every live seat and awards tokens to the original actor.
 $reset($p);$cards=[];foreach(FaBLiveSeats() as $seat){$cards[$seat]=AddArsenal($seat,CardID:'zap_red',Owner:$seat,Controller:$seat);AddDeck($seat,CardID:'zap_blue');}$a=AddGraveyard($p,CardID:'tectonic_instability_blue',Owner:$p,Controller:$p);$run($p,$a);foreach(FaBLiveSeats() as $seat)$answer($seat,$ref($cards[$seat]));$check(FaBMPGSurges($p)===$p,'Tectonic Instability awarded wrong seat/count');foreach(FaBLiveSeats() as $seat)$check(FaBHandCount($seat)===1,'Tectonic skipped live seat '.$seat);
 // Heave 2 pays two, preserves its selected card while pitching, and creates two tokens.
 $reset($p);AddResources($p,0);$h=AddHand($p,CardID:'rubble_raiser_red',Owner:$p,Controller:$p);$pitch=AddHand($p,CardID:'zap_blue',Owner:$p,Controller:$p);$run($p,$h,'ResolveAbility');$answer($p,$ref($h));$answer($p,$ref($pitch));$f=FaBFindUID(intval($h->UniqueID));$check($f['zone']==='Arsenal'&&empty($f['object']->FaceDown)&&FaBMPGSurges($p)===2&&GetResources($p)===1,'Heave 2 payment/arsenal/token outcome');
 // Clashes reward the actual winner, including a nonadjacent opponent in UPF.
 $reset($p);$a=$attack(1,'aftershock_red',$p);AddDeck($p,CardID:'rubble_raiser_red');AddDeck(1,CardID:'zap_blue');$d=AddCombatChain($p,CardID:'clash_of_mountains_blue',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$run($p,$d,'Defended');$check(FaBMPGSurges($p)===1&&FaBMPGSurges(1)===0,'Clash of Mountains wrong winner');
 $reset($p);$a=$attack(1,'aftershock_red',$p);AddDeck($p,CardID:'zap_blue');AddDeck(1,CardID:'rubble_raiser_red');$d=AddCombatChain($p,CardID:'clash_of_heads_yellow',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$e=AddEquipment($p,CardID:'ironrot_helm',Owner:$p,Controller:$p);$run($p,$d,'Defended');$answer($p,$ref($e));$check(intval(FaBObjectCounters($e)['DEFENSE'])===1,'Losing clashing hero did not choose own equipment');
 $reset($p);$a=$attack(1,'aftershock_red',$p);AddDeck($p,CardID:'zap_blue');AddDeck(1,CardID:'rubble_raiser_red');$d=AddCombatChain($p,CardID:'clash_of_legs_yellow',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$hp=GetHealth($p);$run($p,$d,'Defended');$check(GetHealth($p)===$hp-1,'Missing clash equipment did not lose life');
 $reset($p);$a=$attack(1,'aftershock_red',$p);AddDeck($p,CardID:'rubble_raiser_red');AddDeck(1,CardID:'rubble_raiser_red');$d=AddCombatChain($p,CardID:'test_of_iron_grip_red',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);AddHand(1,CardID:'zap_blue');$run($p,$d,'Defended');$check(!FaBHasPendingDecision()&&FaBHandCount(1)===1,'Clash tie incorrectly discarded');
 // Base of the Mountain bypasses hand-block restrictions by adding banished actions.
 $reset($p);$a=$attack(1,'aftershock_red',$p);$d=AddCombatChain($p,CardID:'base_of_the_mountain',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Equipment',ChainLink:1);$h=AddHand($p,CardID:'aftershock_blue',Owner:$p,Controller:$p);$n=AddHand($p,CardID:'overswing_blue',Owner:$p,Controller:$p);$run($p,$d,'Defended');$answer($p,$ref($h).'&'.$ref($n));$check(FaBCurrentDefense($d,$p)===2&&FaBHandCount($p)===0&&FaBFindUID(intval($h->UniqueID))['object']->FromZone==='Banish','Base of the Mountain did not add both banished actions');
 // Call for Backup locks in different names before the selected opponent chooses.
 $reset($p);$a=$attack(1,'aftershock_red',$p);$d=AddCombatChain($p,CardID:'call_for_backup_red',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$x=AddGraveyard($p,CardID:'aftershock_red',Owner:$p,Controller:$p);$y=AddGraveyard($p,CardID:'headbutt_blue',Owner:$p,Controller:$p);$run($p,$d,'Defended');$answer($p,$ref($x));$answer($p,$ref($y));$answer($p,$ref(GetHero(1)[0]));$answer(1,$ref($x));$check(FaBFindUID(intval($x->UniqueID))['zone']==='Banish'&&GetDeck($p)[0]->CardID==='headbutt_blue','Call for Backup resumed under the choosing opponent');
 // Jarl asks for an exposed slot and cannot fill that occupied slot again.
 $reset($p);GetHero($p)[0]->CardID='jarl_vetreidi';$h=AddStack(CardID:'ice_quake_blue',Owner:$p,Controller:$p,Kind:'ATTACK');FaBMPGPlayed($p,$h,'Hand');$resolve();$options=explode('&',explode('|',GetDecisionQueue($p)[0]->Param,3)[2]);$index=array_search('Player_1_Head',$options,true);$check($index!==false,'Jarl did not offer opponent head');$answer($p,strval($index));$check(!FaBMPGExposed(1,'Head')&&!str_contains(FaBMPGJarlOptions($p),'Player_1_Head'),'Jarl frostbite did not occupy selected slot');
 // The Forge cannot replace occupied gear, and cannot fit an off-hand beside a 2H weapon.
 $reset($p);AddEquipment($p,CardID:'ironrot_helm',Owner:$p,Controller:$p);$e=AddEquipment(1,CardID:'ironhide_helm',Owner:1,Controller:1);$check(!FaBMPGEquipSpace($p,$e),'The Forge replaced occupied head');AddWeapons($p,CardID:'anothos',Owner:$p,Controller:$p);$e=AddEquipment(1,CardID:'rampart_of_the_rams_head',Owner:1,Controller:1);$check(!FaBMPGEquipSpace($p,$e),'The Forge exceeded weapon slots');
 // A clash triggered while blocking resumes defense priority, not a nonexistent DEFEND window.
 $reset($p);$a=$attack(1,'pec_perfect_red',$p);AddDeck(1,CardID:'aftershock_red');$top=AddDeck($p,CardID:'zap_blue');$d=AddCombatChain($p,CardID:'rubble_raiser_blue',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$s=FaBGetState();$s['combatStep']='DEFEND';$s['window']='DEFEND_PRIORITY';FaBSetState($s);FaBMPGDefended($p,$d);$resolve();$check(FaBGetState()['window']==='DEFEND_PRIORITY'&&FaBFindUID(intval($top->UniqueID))['zone']==='Graveyard','Pec Perfect failed to mill or restore defense priority');
 // Captain remains a defending card across links, and compares the current attack's power.
 $reset($p);$a=$attack(1,'headbutt_blue',$p);$cap=AddCombatChain($p,CardID:'captain_of_the_guard_blue',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:1);$d=AddCombatChain($p,CardID:'aftershock_red',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand',ChainLink:2);$s=FaBGetState();$s['chainLink']=2;FaBSetState($s);$a->ChainLink=2;$check(FaBCurrentDefense($d,$p)===4,'Captain stopped applying on a later chain link');
 // Arsenal-only buffs wait through attacks played from hand, then stack on the arsenal attack.
 $reset($p);FaBMPGNext($p,2,'',true);FaBMPGNext($p,0,'DOMINATE',true);$a=AddStack(CardID:'aftershock_red',Owner:$p,Controller:$p,Kind:'ATTACK');FaBMPGPlayed($p,$a,'Hand');$check(!in_array('DOMINATE',(array)$a->TurnEffects,true),'Arsenal buff consumed by hand attack');FaBMPGPlayed($p,$a,'Arsenal');$check(in_array('DOMINATE',(array)$a->TurnEffects,true)&&in_array('WTR_POWER:2',(array)$a->TurnEffects,true),'Arsenal bonuses failed to combine');
 // Visit Anvilheim announces X before payment and removes at most that many counters.
 $reset($p);$e=AddEquipment($p,CardID:'rampart_of_the_rams_head',Owner:$p,Controller:$p,Counters:['DEFENSE'=>3]);$h=AddHand($p,CardID:'visit_anvilheim_blue',Owner:$p,Controller:$p);$check(DoPlayCard($p,$ref($h)),'Visit Anvilheim not playable');$answer($p,'2');$resolve();$answer($p,$ref($e));$check(intval(FaBObjectCounters($e)['DEFENSE'])===1&&GetResources($p)===18,'Visit Anvilheim X payment or repair');
 // Suppression disables native crush text and Seismic Surge upkeep while leaving cards in play.
 $reset($p);FaBMPGDuration($p,'BLIND');FaBMPGStart($p);$surge=AddArena($p,CardID:'seismic_surge',Owner:$p,Controller:$p);FaBWTRStartTurn($p);$check(FaBMPGSurges($p)===1,'Abilityless Seismic Surge still destroyed itself');$a=$attack($p,'disable_blue');$ar=AddArsenal(1,CardID:'zap_blue',Owner:1,Controller:1);OnHit($p,$ref($a),4);$check(FaBFindUID(intval($ar->UniqueID))['zone']==='Arsenal','Blinding left native crush active');
 // Eliminated UPF seats are omitted from table-wide choices and cannot be newly targeted.
 if($p===4){$reset($p);FaBEliminateSeat(2,1);$check(!str_contains(FaBMPGJarlOptions($p),'Player_2_'),'Jarl offered an eliminated opponent');$check(FaBHVYToken(2,'seismic_surge')===null,'Created token for eliminated player');}
 // Next-turn ability loss follows physical ownership and does not prevent playing a vanilla attack.
 $reset($p);FaBMPGDuration($p,'BLIND');FaBMPGStart($p);$a=$attack($p,'aftershock_red');FaBWTRAddEffect($p,'MPG_CONTROLLED_SURGE',1);$run($p,$a,'AttackDeclared');$check(HasNoAbilities($a)&&FaBMPGSurges($p)===0,'Blinding did not remove triggered ability');FaBMPGExpire($p);$check(!HasNoAbilities($a),'Blinding persisted after target turn');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "MPG mechanic outcomes passed in duels and UPF.\n";
