<?php
require_once __DIR__.'/mst_test.php';
$failures=[];
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $s){AddChi($s,0);foreach(['Temp','Inventory'] as $z){$get='Get'.$z;$a=&$get($s);$a=[];}}DecisionQueueController::StoreVariable('mzID','');DecisionQueueController::StoreVariable('mstEvent','');};
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id,'Owner'=>$p,'Controller'=>$p]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
foreach([2,4] as $p){
 $reset($p);AddResources($p,5);AddChi($p,3);AddResources($p,3);$check(FaBMSTChi($p)===1,'Ordinary payment did not consume Chi first.');AddResources($p,0);$check(FaBMSTChi($p)===0,'Chi survived resource clearing.');
 $reset($p);GetHero($p)[0]->CardID='enigma';AddResources($p,20);$heroRef=$ref(GetHero($p)[0]);$check(!FaBARCAbilityActions($p,FaBIdentityFromMZ($heroRef)),'Ordinary resources paid Chi activation.');$chi=AddHand($p,CardID:'inner_chi_blue',Owner:$p);$normal=AddHand($p,CardID:'zap_blue',Owner:$p);$check(FaBARCActivate($p,FaBIdentityFromMZ($heroRef),0),'Enigma could not activate with Chi in hand.');$check(!CanPitchCard($p,$ref($normal))&&CanPitchCard($p,$ref($chi)),'Chi payment allowed a non-Chi pitch.');DoPitchCard($p,$ref($chi));$check(FaBGetState()['pendingPayment']===null&&FaBMSTChi($p)===0,'Chi activation failed payment.');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$ss=FaBMONArena($p,'spectral_shield');$check(count($ss)===1&&FaBMSTCounterAmount($ss[0])===1,'Enigma failed to create a shield with a power counter.');
 $reset($p);$hidden=AddEquipment($p,CardID:'aqua_laps',Owner:$p,Controller:$p);FaBMSTSetup($p);$check(FaBMSTHidden($hidden)&&HasNoAbilities($hidden),'Cloaked equipment was active face down.');$a=$attack($p,'droplet_blue');$check(FaBARCActivate($p,FaBFindUID(intval($hidden->UniqueID)),0),'Face-down activated ability was unavailable.');$check(!FaBMSTHidden($hidden),'Cloaked activation did not turn equipment up as a cost.');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$answer($p,$ref($a));$check(in_array('GO_AGAIN',$a->TurnEffects,true),'Aqua Laps failed to grant go again.');
 $reset($p);$owned=AddGraveyard($p,CardID:'homage_to_ancestors_blue',Owner:1,Controller:$p);FaBMSTTranscend($p,intval($owned->UniqueID));$f=FaBFindUID(intval($owned->UniqueID));$check($f['player']===1&&$f['zone']==='Hand'&&$f['object']->CardID==='inner_chi_blue','Transcend did not preserve owner and transformed identity.');
 $reset($p);FaBMSTAdd($p,'BLUE_PLAYED');$uid=$macro($p,'homage_to_ancestors_blue');$check(FaBFindUID($uid)['zone']==='Hand'&&FaBFindUID($uid)['object']->CardID==='inner_chi_blue','Other-blue Transcend did not resolve.');
 $reset($p);AddWeapons($p,CardID:'cosmo_scroll_of_ancestral_tapestry',Owner:$p,Controller:$p);GetHero($p)[0]->CardID='enigma';$aura=AddArena($p,CardID:'manifestation_of_miragai_blue',Owner:$p,Controller:$p);FaBMSTEnter($p,$aura);$check(FaBMSTWard($p,$aura)===2,'Miragai did not enter with counters.');FaBMSTCounters($ref($aura),2);$check(FaBMONArenaAttackSpec($p,FaBFindUID(intval($aura->UniqueID)))['power']===4,'Cosmo did not use current Ward value.');FaBMSTShield($p,1);$shield=FaBIdentityFromMZ(FaBMONArena($p,'spectral_shield')[0]);$check(FaBMONArenaAttackSpec($p,$shield)['cost']===0,'Enigma first shield attack discount missing.');FaBMSTAdd($p,'SHIELD_ATTACK');$check(FaBMONArenaAttackSpec($p,$shield)['cost']===1,'Enigma discounted a second shield attack.');
 $reset($p);$aura=AddArena($p,CardID:'three_visits_red',Owner:$p,Controller:$p);$check(FaBMSTWard($p,$aura)===0,'Three Visits had Ward without a blue pitch.');FaBMSTAdd($p,'BLUE_PITCHED',2);$check(FaBMSTWard($p,$aura)===6,'Three Visits did not update Ward dynamically.');$check(FaBDYNWard($p,7)===1&&FaBFindUID(intval($aura->UniqueID))['zone']==='Graveyard','Dynamic Ward prevention failed.');
 $reset($p);$a=$attack($p,'bonds_of_agony_blue');FaBMSTReaction($p);FaBMSTReaction($p);FaBMSTReaction($p);$check(FaBMSTPower($p,$a)===3,'Bonds of Agony reaction threshold failed.');$a->CardID='pick_to_pieces_red';$check(FaBUPRUnpreventable(intval($a->UniqueID)),'Pick to Pieces did not become unpreventable.');
 $reset($p);FaBMSTNuuPermission($p,1);$stolen=AddBanish(1,CardID:'droplet_blue',Owner:1,Controller:1);$check(FaBMSTStolen($p,FaBFindUID(intval($stolen->UniqueID)))&&FaBCardCost($stolen,$p)===0,'Nuu permission failed to waive blue card cost.');if($p===4){$other=AddBanish(3,CardID:'droplet_blue',Owner:3);$check(!FaBMSTStolen($p,FaBFindUID(intval($other->UniqueID))),'Nuu permission leaked to another opponent.');}
 $reset($p);$a=$attack($p,'droplet_blue');$blue=AddHand(1,CardID:'wash_away_blue',Owner:1);AddDeck($p,CardID:'zap_blue');$uid=$macro($p,'sirens_call_red');$q=GetDecisionQueue($p)[0];$answer($p,explode('&',$q->Param)[0]);$f=FaBFindUID(intval($blue->UniqueID));$check($f['zone']==='CombatChain'&&$f['player']===1&&$f['object']->Role==='DEFENSE'&&FaBHandCount($p)===1,'Sirens Call moved a preview instead of the chosen original or failed to draw.');$check(count(FaBChoiceRefs($p,'Temp'))===0,'Sirens Call leaked private hand previews.');
 $reset($p);FaBMSTTiger($p);$block=AddHand($p,CardID:'territorial_domain_blue');$check(FaBMSTDefense($p,$block)===3,'Territorial Domain missed created Tiger.');FaBMSTEnd($p);$check(count(FaBChoiceRefs($p,'Hand',['base'=>'crouching_tiger']))===1,'Ephemeral incorrectly removed a card that never entered a graveyard.');
 $reset($p);$aura=AddArena($p,CardID:'haunting_specter_red',Owner:$p,Controller:$p);FaBMONDestroy(intval($aura->UniqueID));$r=FaBMONArena($p,'spectral_shield');$check(count($r)===1&&FaBMSTCounterAmount($r[0])===1,'Last Haunting Specter failed its shield replacement.');
 $reset($p);$a=$attack($p,'bonds_of_agony_blue');FaBARCSetCard(intval($a->UniqueID),'mstReactions',3);$hand=AddHand(1,CardID:'zap_blue',Owner:1);AddDeck(1,CardID:'zap_blue',Owner:1);AddGraveyard(1,CardID:'zap_red',Owner:1);FaBRunSourceMacro('Hit',$p,$a->CardID,['mzID'=>$ref($a),'amount'=>1]);$q=GetDecisionQueue($p)[0];$answer($p,explode('&',$q->Param)[0]);$q=GetDecisionQueue($p)[0];$choices=explode('|',$q->Param,3)[2];$answer($p,$choices);$check(count(FaBChoiceRefs(1,'Banish'))===3&&count(FaBChoiceRefs($p,'Temp'))===0,'Bonds of Agony failed across hand/deck/graveyard or exposed previews.');
 $reset($p);$a=$attack($p,'droplet_blue');FaBMSTAdd(1,'NO_HIT');$check(FaBCRUHitSuppressed($a,true),'Dense Blue Mist failed to suppress hit triggers.');
 $reset($p);$a=$attack(1,'wounding_blow_red',$p);$big=AddArena($p,CardID:'10000_year_reunion_red',Owner:$p,Controller:$p);FaBMSTShield($p);$before=GetHealth($p);FaBBeginDamageStep();$q=GetDecisionQueue($p)[0]??null;$check($q&&$q->Type==='MZCHOOSE','Ward did not offer prevention order.');$answer($p,$ref($big));$check(GetHealth($p)===$before&&count(FaBMONArena($p,'spectral_shield'))===1,'Ward choice destroyed an unselected shield or failed prevention.');
 $reset($p);$zero=AddArena($p,CardID:'three_visits_red',Owner:$p,Controller:$p);$check(FaBDYNWard($p,1)===1&&FaBFindUID(intval($zero->UniqueID))['zone']==='Graveyard','Ward zero failed to destroy its source.');
 $reset($p);GetHero($p)[0]->CardID='enigma';FaBEVRAdd($p,'IGNITION',2);$spec=FaBARCAbilitySpecs('enigma')[0];$check(FaBWTRAbilityCost($p,$spec)===3,'Resource reduction reduced a Chi cost.');FaBEVRClear($p,'IGNITION');FaBWTRCreateArena($p,'frostbite');$check(FaBWTRAbilityCost($p,$spec)===4,'Chi activation ignored an additional resource cost.');
 $reset($p);AddResources($p,0);FaBMSTShield($p,3);$shield=FaBIdentityFromMZ(FaBMONArena($p,'spectral_shield')[0])['object'];$reunion=AddHand($p,CardID:'10000_year_reunion_red',Owner:$p);$check(CanPlayCard($p,$ref($reunion)),'Reunion alternative cost was unavailable without resources.');DoPlayCard($p,$ref($reunion));$q=GetDecisionQueue($p)[0];$check($q->Type==='MZCHOOSE','Unpayable Reunion offered its resource alternative.');$answer($p,$ref($shield));$answer($p,'3');$check(FaBGetState()['pendingPayment']===null&&FaBMSTCounterAmount($ref($shield))===0,'Reunion alternative failed to remove counters or finish payment.');
 $reset($p);FaBMSTNext($p,0,'aa','MST_BOOST');AddDeck($p,CardID:'throttle_blue',Owner:$p);$card=AddHand($p,CardID:'wounding_blow_red',Owner:$p);DoPlayCard($p,$ref($card));if((GetDecisionQueue($p)[0]->Type??'')==='MZCHOOSE')$answer($p,$ref(GetHero(1)[0]));$check((GetDecisionQueue($p)[0]->Tooltip??'')==='Banish_top_card_to_boost','Evo Speedslip did not offer granted Boost.');$answer($p,'0');$f=FaBFindUID(intval($card->UniqueID));$check(FaBARCCard(intval($card->UniqueID),'boosted')&&in_array('GO_AGAIN',$f['object']->TurnEffects,true)&&FaBGetState()['pendingPayment']===null,'Granted Boost failed to resolve or resume payment.');
 $reset($p);FaBMSTShield($p,2);$shield=FaBIdentityFromMZ(FaBMONArena($p,'spectral_shield')[0])['object'];$uid=$macro($p,'restless_coalescence_yellow','ResolveCard','Arena');$answer($p,$ref($shield));$answer($p,'2');$check(FaBMSTCounterAmount(FaBDTDSource($uid))===2&&FaBMSTCounterAmount($ref($shield))===0,'Restless Coalescence failed to transfer counters.');
 $reset($p);FaBMSTBlanch($p,1);$check(FaBMSTColor(1,'droplet_blue')===0&&intval(CardPitch('droplet_blue'))===3,'Blanch did not remove color independently of pitch resources.');FaBMSTEnd($p);$check(FaBMSTColor(1,'droplet_blue')===0,'Blanch expired before affected hero next turn.');FaBMSTEnd(1);$check(FaBMSTColor(1,'droplet_blue')===3,'Blanch did not expire after affected hero turn.');
 $reset($p);$a=$attack($p,'eloquent_eulogy_red');FaBDTDAdd(1,'LOST');FaBCloseCombatChain();$check(count(FaBMONArena($p,'eloquence'))===1,'Eloquent Eulogy missed combat chain closure.');
 $reset($p);FaBMSTNuuPermission($p,1);$aura=AddBanish(1,CardID:'waxing_specter_blue',Owner:1,Controller:1);DoPlayCard($p,$ref($aura));$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$f=FaBFindUID(intval($aura->UniqueID));$check($f['player']===$p&&$f['zone']==='Arena'&&intval($f['object']->Owner)===1,'Nuu played a stolen aura under its owner control.');

 $reset($p);GetHero($p)[0]->CardID='enigma';AddResources($p,0);$path=AddEquipment($p,CardID:'meridian_pathway',Owner:$p,Controller:$p);$chi=AddHand($p,CardID:'inner_chi_blue',Owner:$p);FaBARCActivate($p,FaBFindUID(intval(GetHero($p)[0]->UniqueID)),0);DoPitchCard($p,$ref($chi));$answer($p,'1');$check(FaBGetState()['pendingPayment']===null&&FaBMSTWard($p,$path)===3,'Meridian pitch trigger failed to resume Chi payment or grant Ward.');
 $reset($p);$sigil=AddArena($p,CardID:'sigil_of_solitude_red',Owner:$p,Controller:$p);FaBMSTShield($p);FaBMSTStart($p);$check(FaBFindUID(intval($sigil->UniqueID))['zone']==='Graveyard','Sigil of Solitude did not trigger at start of turn.');
 $reset($p);$proxy=AddCombatChain($p,CardID:'waxing_specter_blue',Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:1);FaBEVOCounter($proxy,'MON_ARENA_ATTACK',1);FaBEVOCounter($proxy,'MON_AURA',1);FaBMSTPlayed($p,$proxy,'Weapons');$check(FaBMSTCount($p,'BLUE_PLAYED')===0,'Aura weapon activation counted as playing a blue card.');
 if($p===4){$reset($p);$a=$attack(4,'wounding_blow_red',1);$s=FaBGetState();$s['attackTargets']=[['type'=>'HERO','player'=>1],['type'=>'HERO','player'=>3]];FaBSetState($s);FaBMSTAdd(3,'DENSE_MIST');FaBMSTAdd(3,'NO_HIT');$check(FaBMSTPower(4,$a)===-1&&FaBCRUHitSuppressed($a,true),'Dense Blue Mist missed a secondary UPF target.');}

 $reset($p);FaBMSTSupercell($p,0,'');$drivers=FaBChoiceRefs($p,'Arena',['base'=>'hyper_driver']);$check(count($drivers)===1&&FaBStackTop()!==null,'Zero-steam Hyper Driver did not create its destruction trigger.');$d=FaBIdentityFromMZ($drivers[0])['object'];FaBARCSteam($d,1);DoResolveCard($p,$ref(FaBStackTop()));$check((FaBFindUID(intval($d->UniqueID))['zone']??'')==='Arena','Zero-steam trigger did not recheck counters on resolution.');FaBMSTSupercell($p,0,'');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$check(count(FaBChoiceRefs($p,'Arena',['base'=>'hyper_driver']))===1,'Zero-steam token survived its trigger.');
 $reset($p);AddEquipment($p,CardID:'ironrot_helm',Owner:$p,Controller:$p);$item=AddInventory($p,CardID:'skycrest_keikoi',Owner:$p,Controller:$p);$check(FaBMSTInventory($p)==='','Golden Anvil offered equipment for an occupied slot.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "MST mechanic outcomes passed in duels and UPF.\n";
