<?php
require_once __DIR__.'/out_test.php';
$failures=[];
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard'){ $o=FaBAddToZone($zone,$p,(object)['CardID'=>$id]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,['mzID'=>FaBOUTSource($uid)]);return $uid;};
$outReset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $seat){$z=&GetInventory($seat);$z=[];$z=&GetTemp($seat);$z=[];}};
$drain=function(int $limit=80)use($answer){for($i=0;$i<$limit;++$i){$seat=0;foreach(FaBLiveSeats() as $p)if(GetDecisionQueue($p)){$seat=$p;break;}if(!$seat)return;$d=GetDecisionQueue($seat)[0];$v=match($d->Type){'MZCHOOSE','MZMAYCHOOSE'=>explode('&',$d->Param)[0],'MZMODAL'=>'0','MZREARRANGE'=>$d->Param,'MZMULTICHOOSE'=>implode('&',array_slice(explode('&',explode('|',$d->Param,3)[2]??''),0,intval(explode('|',$d->Param)[0]))),'NAMECARD'=>'Surging Strike',default=>throw new RuntimeException('Unsupported '.$d->Type)};$answer($seat,$v);}throw new RuntimeException('OUT choice loop did not finish');};
foreach([2,4] as $p){
 foreach(['infect_red'=>'bloodrot_pox','sedate_blue'=>'inertia','wither_yellow'=>'frailty'] as $id=>$token){$outReset($p);$a=$attack($p,$id);OnHit($p,$ref($a),1);$check(count(FaBMONArena(1,$token))===1&&!FaBMONArena($p,$token),'Disease hit used wrong seat: '.$id);}
 $outReset($p);GetHero($p)[0]->CardID='arakni_solitary_confinement';$a=AddStack(CardID:'infect_red',Controller:$p,Kind:'ATTACK');FaBOUTPlayed($p,$a,'Hand');$check(in_array('GO_AGAIN',$a->TurnEffects,true),'Solitary Confinement first stealth missing go again.');$b=AddStack(CardID:'wither_red',Controller:$p,Kind:'ATTACK');FaBOUTPlayed($p,$b,'Hand');$check(!in_array('GO_AGAIN',$b->TurnEffects,true),'Solitary Confinement applied to second stealth.');
 // Uzuri pays the real face-down cost, replaces the attack, keeps defenders, and never transfers buffs.
 $outReset($p);GetHero($p)[0]->CardID='uzuri';$a=$attack($p,'infect_red');FaBWTRTag($a,'WTR_POWER:5');$oldUID=intval($a->UniqueID);$d=AddCombatChain(1,CardID:'head_jab_blue',Role:'DEFENSE',ChainLink:1,FromZone:'Hand',Owner:1,Controller:1);$h=AddHand($p,CardID:'sneak_attack_red');$hid=intval($h->UniqueID);
 $check(FaBWTRActivate($p,$ref(GetHero($p)[0])),'Uzuri could not activate.');$answer($p,$ref($h));$check(FaBFindUID($hid)['zone']==='Banish'&&intval(FaBFindUID($hid)['object']->FaceDown)===1,'Uzuri cost did not banish face down.');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$new=FaBFindUID($hid);$check(intval(FaBGetState()['attackUID'])===$hid&&$new['zone']==='CombatChain'&&!$new['object']->TurnEffects,'Uzuri swap transferred old buffs or failed.');$check(FaBFindUID($oldUID)['zone']==='Deck'&&FaBFindUID(intval($d->UniqueID))['zone']==='CombatChain','Uzuri lost a defender or failed to bottom old attack.');$check(FaBOUTPower($p,$new['object'])===4,'Uzuri activation did not enable Sneak Attack.');
 $outReset($p);$a=$attack($p,'infect_red');$u=AddStack(CardID:'uzuri',Controller:$p);$h=AddHand($p,CardID:'razors_edge_red');FaBOUTBanishCost($p,intval($u->UniqueID),$ref($h));FaBOUTSwap($p,intval($u->UniqueID));$check(FaBGetState()['attackUID']===$a->UniqueID&&!FaBFindUID(intval($h->UniqueID))['object']->FaceDown,'Invalid Uzuri swap changed the attack or stayed face down.');
 $outReset($p);$w=AddWeapons($p,CardID:'nerve_scalpel',Owner:$p,Controller:$p);$check(FaBWTRCanActivate($p,$ref($w)),'OUT dagger cannot attack through normal activation.');
 // Conditional traps deal Riptide damage only when their own condition triggers.
 foreach([false,true] as $reaction){$outReset($p);GetHero($p)[0]->CardID='riptide';$a=$attack(1,'head_jab_red',$p);if($reaction)FaBOUTReactionPlayed(1,true);$trap=AddCombatChain($p,CardID:'bloodrot_trap_red',Role:'DEFENSE_REACTION',ChainLink:1,Owner:$p,Controller:$p);$before=GetHealth(1);OnDefended($p,$ref($trap),$p);$drain();$check(GetHealth(1)===$before-($reaction?1:0)&&count(FaBMONArena(1,'bloodrot_pox'))===($reaction?1:0),'Bloodrot Trap/Riptide condition incorrect.');}
 $outReset($p);GetHero($p)[0]->CardID='riptide';AddHand($p,CardID:'infect_red');$o=AddStack(CardID:'come_to_fight_red',Controller:$p);FaBOUTPlayed($p,$o,'Hand');$check(GetDecisionQueue($p)[0]->Type==='MZMAYCHOOSE','Riptide did not offer arsenal load.');$answer($p,FaBChoiceRefs($p,'Hand')[0]);$check(count(FaBChoiceRefs($p,'Arsenal'))===1&&intval(GetArsenal($p)[0]->FaceDown)===1,'Riptide arsenal not face down.');
 foreach(['codex_of_bloodrot_yellow','codex_of_frailty_yellow','codex_of_inertia_yellow'] as $id){$outReset($p);foreach(FaBLiveSeats() as $seat){AddArsenal($seat,CardID:'head_jab_blue');AddHand($seat,CardID:'head_jab_red');AddGraveyard($seat,CardID:'infect_red');AddDeck($seat,CardID:'wither_red');}$macro($p,$id);$drain();foreach(FaBLiveSeats() as $seat)$check(count(FaBChoiceRefs($seat,'Arsenal'))===2,'Codex failed to put a card into an occupied arsenal for seat '.$seat);$check(count(FaBMONArena($p,'ponder'))===1,'Codex did not give caster Ponder.');$token=['codex_of_bloodrot_yellow'=>'bloodrot_pox','codex_of_frailty_yellow'=>'frailty','codex_of_inertia_yellow'=>'inertia'][$id];foreach(FaBOpponents($p) as $seat)$check(count(FaBMONArena($seat,$token))===1,'Codex missed opponent token.');}
 // The active player chooses the order of Inertia and Ponder at end phase.
 foreach(['inertia','ponder'] as $first){$outReset($p);FaBOUTToken($p,'inertia');FaBOUTToken($p,'ponder');AddHand($p,CardID:'infect_red');AddDeck($p,CardID:'zap_blue');FaBRunSourceMacro('EndTurn',$p,'bloodrot_pox',[]);$answer($p,FaBMONArena($p,$first)[0]);$drain();$check(FaBHandCount($p)===($first==='inertia'?1:0),'Inertia/Ponder ordering was ignored.');}
 $outReset($p);FaBOUTToken($p,'bloodrot_pox');FaBRunSourceMacro('EndTurn',$p,'bloodrot_pox',[]);$drain();$check(GetHealth($p)===28&&!FaBMONArena($p,'bloodrot_pox'),'Unpaid Bloodrot failed.');
 $outReset($p);$a=$attack($p,'infect_red');FaBOUTToken($p,'frailty');$a->FromZone='Arsenal';$check(FaBOUTPower($p,$a)===-1,'Frailty missing arsenal penalty.');$a->FromZone='Hand';$check(FaBOUTPower($p,$a)===0,'Frailty affected hand attack.');
 $outReset($p);$a=$attack($p,'spiders_bite');$w=AddWeapons($p,CardID:'nerve_scalpel',Owner:$p,Controller:$p);$victim=$p===4?3:1;$before=GetHealth($victim);FaBOUTThrow($p,$ref($w),$ref(GetHero($victim)[0]));$check(GetHealth($victim)===$before-1&&FaBOUTCount($victim,'DAGGER_REACTION')===1&&FaBFindUID(intval($w->UniqueID))['zone']==='Graveyard','Thrown dagger used wrong hero or missed on-hit.');
 $outReset($p);$a=$attack($p,'nerve_scalpel');FaBOUTDaggerHit($p,$a,1,1);$d1=AddCombatChain(1,CardID:'razors_edge_red',Role:'DEFENSE',ChainLink:1,Owner:1,Controller:1);$d2=AddCombatChain(1,CardID:'shred_blue',Role:'DEFENSE',ChainLink:1,Owner:1,Controller:1);FaBOUTDefendGroup(1,[$d1->UniqueID,$d2->UniqueID]);$check(FaBDYNDefense(1,$d1)===-1&&FaBDYNDefense(1,$d2)===-1&&FaBOUTCount(1,'DAGGER_REACTION')===0,'Dagger did not reduce the entire next defending group.');
 $outReset($p);$a=$attack($p,'amplifying_arrow_yellow');FaBWTRTag($a,'WTR_POWER:3');FaBWTRTag($a,'WTR_POWER:1');$check(in_array('WTR_POWER:4',$a->TurnEffects,true)&&in_array('WTR_POWER:2',$a->TurnEffects,true),'Amplifying Arrow did not replace each gain.');FaBWTRTag($a,'OUT_NO_GAIN');$before=$a->TurnEffects;FaBWTRTag($a,'WTR_POWER:2');$check($a->TurnEffects===$before,'Buzzsaw allows new power.');
 $outReset($p);$a=$attack($p,'surging_strike_red');$next=AddStack(CardID:'descendent_gustwave_red',Controller:$p);$check(FaBOUTCost($p,$next)===-1,'Descendent Gustwave combo discount missing.');FaBOUTPlayed($p,$next,'Hand');$check(FaBOUTCombo($p,'descendent_gustwave',$next),'Combo was not preserved across card play.');
 $outReset($p);$a=$attack($p,'back_stab_red');$h=AddHand(1,CardID:'sink_below_red');$check(!FaBOUTCanPlay(1,FaBFindUID(intval($h->UniqueID))),'Back Stab permits defense reactions.');
 $outReset($p);$a=$attack($p,'barbed_undertow_red');FaBSetObjectCounter($a,'AIM',1);OnHit($p,$ref($a),1);$answer($p,'2');$blue=AddHand(1,CardID:'head_jab_blue');$red=AddHand(1,CardID:'head_jab_red');$check(!FaBOUTCanPitch(1,$blue)&&FaBOUTCanPitch(1,$red),'Barbed Undertow blocked wrong color.');
 $outReset($p);$a=$attack($p,'infiltrate_red');$top=AddDeck(1,CardID:'head_jab_red');OnHit($p,$ref($a),1);$f=FaBFindUID(intval($top->UniqueID));$check($f['player']===1&&$f['zone']==='Banish'&&FaBOUTCanPlayStolen($p,$f),'Infiltrate changed owner or omitted permission.');FaBOUTEndPermissions($p);$check(FaBOUTCanPlayStolen($p,$f),'Infiltrate expired during the current turn.');SetTurnNumber(GetTurnNumber()+4);FaBOUTEndPermissions($p);$check(!FaBOUTCanPlayStolen($p,$f),'Infiltrate permission outlived next turn.');
 $outReset($p);$a=$attack($p,'dishonor_blue');foreach(['surging_strike_red','descendent_gustwave_red','bonds_of_ancestry_red'] as $id)AddCombatChain($p,CardID:$id,Role:'ATTACK',Owner:$p,Controller:$p);FaBOUTDishonor($p,1);$check(!FaBWTRHeroActive(1),'Dishonor hero abilities remain active.');
 $outReset($p);$o=AddHand(1,CardID:'head_jab_red',Owner:1);FaBOUTLongEffect($p,1,'AMNESIA');$check(!FaBOUTNames($o),'Amnesia did not remove names.');
 $outReset($p);$macro($p,'brush_off_red');$check(DoDamage(1,'',$p,4,'PHYSICAL')===4&&DoDamage(1,'',$p,3,'PHYSICAL')===0,'Brush Off consumed on oversized packet or failed to prevent.');
 $outReset($p);$macro($p,'peace_of_mind_red');$check(DoDamage(1,'',$p,2,'ARCANE')===2&&DoDamage(1,'',$p,6,'PHYSICAL')===2&&DoDamage(1,'',$p,2,'PHYSICAL')===2,'Peace of Mind wrong type or number of uses.');
 $outReset($p);AddResources($p,0);AddHand($p,CardID:'head_jab_blue');FaBOUTToken($p,'bloodrot_pox');FaBRunSourceMacro('EndTurn',$p,'bloodrot_pox',[]);$answer($p,FaBMONArena($p,'bloodrot_pox')[0]);$answer($p,'1');$answer($p,FaBChoiceRefs($p,'Hand')[0]);$check(GetHealth($p)===30&&GetResources($p)===0&&count(FaBChoiceRefs($p,'Pitch'))===1,'Bloodrot did not allow payment by pitching.');
 $outReset($p);$a=$attack($p,'head_jab_red');$h=AddHand(1,CardID:'down_and_dirty_red');FaBMoveUID(intval($h->UniqueID),'Arsenal',1);$s=FaBGetState();$s['window']='DEFEND_DECLARE';FaBSetState($s);$check(FaBCanBlock(1,$ref(FaBFindUID(intval($h->UniqueID))['object'])),'Down and Dirty cannot defend from arsenal.');
 $outReset($p);$prior=$attack($p,'be_like_water_red');FaBOUTWaterName(intval($prior->UniqueID),'1');$next=AddStack(CardID:'descendent_gustwave_red',Controller:$p);$check(FaBOUTCost($p,$next)===-1,'Be Like Water gained name does not enable combo.');$s=FaBGetState();$s['outPreviousNames'][$p]=FaBOUTNames($prior);$check(FaBComboActive($s,'surging_strike_red'),'Gained name does not enable an older-set combo.');FaBOUTLongEffect(1,$p,'AMNESIA');$check(!FaBOUTCombo($p,'descendent_gustwave'),'Amnesia still permits a named previous attack.');
 $outReset($p);$a=$attack($p,'infiltrate_red');$top=AddDeck(1,CardID:'come_to_fight_red');FaBOUTInfiltrate($p,1);$r=$ref(FaBFindUID(intval($top->UniqueID))['object']);$s=FaBGetState();$s['window']='ACTION';$s['combatOpen']=false;FaBSetState($s);SetPriorityPlayer($p);$check(DoPlayCard($p,$r),'Infiltrate card cannot be played by the stealing seat.');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$f=FaBFindUID(intval($top->UniqueID));$check($f['zone']==='Graveyard'&&$f['player']===1,'Stolen action went to the controller graveyard instead of its owner.');
 $outReset($p);AddInventory($p,CardID:'nerve_scalpel',Owner:$p,Controller:$p);$r=FaBOUTInventoryDaggers($p);$check($r!=='','Concealed Blade has no inventory candidates.');FaBOUTEquipDagger($p,$r);$check(count(FaBChoiceRefs($p,'Weapons'))===1&&!FaBChoiceRefs($p,'Inventory'),'Concealed Blade did not consume inventory dagger: '.json_encode([FaBChoiceRefs($p,'Weapons'),FaBChoiceRefs($p,'Inventory'),$r,FaBIdentityFromMZ($r)]));
 $outReset($p);$a=$attack($p,'malign_red');$check(FaBUPRUnpreventable(intval($a->UniqueID)),'Malign still offers damage prevention.');FaBWTRAddEffect(1,'PREVENT_DAMAGE',5);$check(DoDamage($p,$ref($a),1,3,'PHYSICAL')===3,'Malign damage was prevented.');
 $outReset($p);$a=$attack($p,'head_jab_red');FaBOUTAdd($p,'VAMBRACE');FaBWTRAddEffect(1,'PREVENT_DAMAGE',2);$check(DoDamage($p,$ref($a),1,3,'PHYSICAL')===2&&!FaBOUTCount($p,'VAMBRACE'),'Vambrace did not reduce prevention once.');
 $outReset($p);FaBOUTPitch($p,'plague_hive_yellow');foreach(FaBOpponents($p) as $seat)$check(count(FaBChoiceRefs($seat,'Arena'))===1,'Plague Hive missed a multiplayer opponent.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "Outsiders mechanic outcomes passed in duels and UPF.\n";
