<?php
require_once __DIR__.'/ros_test.php';
$failures=[];
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $seat){AddChi($seat,0);foreach(['Temp','Inventory','Banish','Arena','Equipment','Weapons','Graveyard'] as $z){$get='Get'.$z;$a=&$get($seat);$a=[];}}DecisionQueueController::StoreVariable('mzID','');};
$macro=function(int $p,string $id,string $name='ResolveCard',string $zone='Graveyard',array $params=[]){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id,'Owner'=>$p,'Controller'=>$p]);$uid=intval($o->UniqueID);FaBRunSourceMacro($name,$p,$id,array_merge(['mzID'=>FaBDTDSource($uid)],$params));return $uid;};
foreach([2,4] as $p){
 $reset($p);GetHero($p)[0]->CardID='florian';for($i=0;$i<4;++$i)AddBanish($p,CardID:'autumns_touch_blue');FaBARCCreateRunes($p,3);$check(FaBARCRunechants($p)===4,'Florian must add one token per creation event, not per token.');FaBARCCreateRunes($p,1);$check(FaBARCRunechants($p)===6,'Florian missed a second creation event.');
 $reset($p);GetHero($p)[0]->CardID='florian_rotwood_harbinger';for($i=0;$i<4;++$i)AddBanish($p,CardID:'autumns_touch_blue');FaBARCCreateRunes($p,1);$check(FaBARCRunechants($p)===1,'Adult Florian activated below eight Earth cards.');
 $reset($p);GetHero($p)[0]->CardID='verdance';for($i=0;$i<4;++$i)AddBanish($p,CardID:'autumns_touch_blue');$h=intval(GetHealth($p));$macro($p,'heartbeat_of_candlehold_blue');$check(intval(GetHealth($p))===$h+3&&FaBROSCount($p,'LIFE')===3,'Heartbeat did not gain three life.');$check(count(array_filter(GetStack(),fn($o)=>is_object($o)&&empty($o->removed)&&!empty($o->Params['rosTrigger'])))===3,'Verdance did not trigger once per life gain.');
 $reset($p);$e1=AddGraveyard($p,CardID:'autumns_touch_blue');$e2=AddGraveyard($p,CardID:'earthlore_surge_blue');$a=AddGraveyard($p,CardID:'zap_blue');$check(FaBROSDecomposeReady($p),'Decompose failed to find Earth/Earth/action.');$check(!FaBROSDecompose($p,$ref($e1).'&'.$ref($e2),$ref($e1)),'Decompose reused an Earth as the third card.');$check(FaBROSDecompose($p,$ref($e1).'&'.$ref($e2),$ref($a))&&FaBROSEarth($p)===2,'Decompose failed to banish three distinct cards.');
 $reset($p);$hidden=AddBanish($p,CardID:'autumns_touch_blue',FaceDown:1);$check(FaBROSEarth($p)===0,'Face-down banished card counted as Earth.');
 $reset($p);$e1=AddGraveyard($p,CardID:'autumns_touch_blue');$e2=AddGraveyard($p,CardID:'earthlore_surge_blue');$cost=AddGraveyard($p,CardID:'zap_blue');$a=$attack($p,'cadaverous_tilling_blue',1);FaBRunSourceMacro('AttackDeclared',$p,$a->CardID,['mzID'=>$ref($a)]);$answer($p,'1');$answer($p,$ref($e1).'&'.$ref($e2));$answer($p,$ref($cost));$check(in_array('WTR_POWER:2',(array)$a->TurnEffects,true)&&count(FaBChoiceRefs($p,'Banish'))===3,'Decompose continuation did not pay the selected cards and apply power.');
 $reset($p);$r=FaBWTRCreateArena($p,'runechant');FaBMSTAdd($p,'AMP',3);$check(FaBUPRDamageBonus($p,intval($r->UniqueID),1,'ARCANE')===1&&FaBMSTCount($p,'AMP')===3,'Amp was consumed by Runechant.');$spell=AddGraveyard($p,CardID:'photon_splicing_red');$check(FaBUPRDamageBonus($p,intval($spell->UniqueID),4,'ARCANE')===7&&FaBMSTCount($p,'AMP')===0,'Amp did not enhance the next action damage event.');
 $reset($p);$shield=FaBWTRCreateArena(1,'sigil_of_sanctuary_blue');$spell=AddGraveyard($p,CardID:'photon_splicing_red');$check(FaBDTDPreventionChoices(1,3,[],'PHYSICAL')===''&&str_contains(FaBDTDPreventionChoices(1,3,[],'ARCANE'),$ref($shield)),'Arcane Shelter offered against physical or missed arcane damage.');$used=[];$check(FaBDTDPreventionPay(1,$ref($shield),3,$used)===1,'Arcane Shelter amount wrong.');$trigger=FaBStackTop();$check($trigger!==null,'Leaving Sigil did not create a trigger.');DoResolveCard(1,$ref($trigger));$check(count(FaBMONArena(1,'embodiment_of_earth'))===1,'Sigil of Sanctuary did not create Earth token.');
 $reset($p);$spell=AddHand($p,CardID:'pulsing_aether_life_red',Owner:$p,Controller:$p);AddResources($p,2);AddActionPoints($p,1);$check(DoPlayCard($p,$ref($spell)),'Meld card not playable.');$answer($p,'2');$answer($p,$ref(GetHero(1)[0]));$check(GetResources($p)===0&&GetActionPoints($p)===0,'Meld both did not pay two resources and one action.');$stack=FaBStackTop();$uid=intval($stack->UniqueID);$life=intval(GetHealth($p));DoResolveCard($p,$ref($stack));$check(intval(GetHealth($p))===$life+1&&(FaBFindUID($uid)['zone']??'')==='Stack'&&FaBARCCard($uid,'rosSide')===0,'Meld right half did not resolve first and leave the left on stack.');$hp=intval(GetHealth(1));DoResolveCard($p,FaBDTDSource($uid));$check(intval(GetHealth(1))===$hp-4&&(FaBFindUID($uid)['zone']??'')==='Graveyard','Meld left half did not resolve after priority window.');
 $reset($p);SetTurnPlayer(1);$s=FaBGetState();$s['window']='REACTION';FaBSetState($s);AddResources($p,1);$spell=AddHand($p,CardID:'pulsing_aether_life_red',Owner:$p,Controller:$p);$check(DoPlayCard($p,$ref($spell)),'Right half unavailable as instant.');$d=GetDecisionQueue($p)[0];$check(str_contains($d->Param,'Right_half')&&!str_contains($d->Param,'Left_half')&&!str_contains($d->Param,'Meld_both'),'Meld offered action half outside action timing.');$answer($p,'0');$s=FaBStackTop();$check($s->Kind==='INSTANT'&&!FaBHasType($s,'Action')&&FaBHasType($s,'Earth')&&!FaBHasType($s,'Wizard'),'Right half retained wrong properties.');
 $reset($p);$o=AddEquipment($p,CardID:'well_grounded',Owner:$p,Controller:$p);$check(!FaBARCAbilityLegal($p,FaBFindUID(intval($o->UniqueID)),FaBARCAbilitySpecs('well_grounded')[0]),'Well Grounded available without Earth.');
 $reset($p);$o=AddHand($p,CardID:'fruits_of_the_forest_blue',Owner:$p,Controller:$p);$hp=intval(GetHealth($p));$check(FaBARCActivate($p,FaBFindUID(intval($o->UniqueID)),0),'Hand discard activation unavailable.');$check((FaBFindUID(intval($o->UniqueID))['zone']??'')==='Graveyard','Discard ability did not pay its cost.');DoResolveCard($p,$ref(FaBStackTop()));$check(GetHealth($p)===$hp+2,'Blue Fruits of the Forest did not gain two.');
 $reset($p);$a=$attack($p,'star_fall',1);FaBROSAdd($p,'LIGHTNING');$check(FaBROSPower($p,$a)===1&&FaBROSGoAgain($p,$a),'Star Fall missed Lightning bonus.');
 $reset($p);$a=$attack($p,'flittering_charge_red',1);$instant=AddStack(CardID:'high_voltage_blue',Controller:$p,Kind:'INSTANT');FaBROSPlayed($p,$instant,'Hand');$check(FaBROSGoAgain($p,$a),'Instant did not enable Flittering Charge.');
 $reset($p);AddDeck($p,CardID:'zap_blue',Owner:$p);$sigil=FaBWTRCreateArena($p,'sigil_of_brilliance_yellow');$before=FaBHandCount($p);FaBMoveUID(intval($sigil->UniqueID),'Hand',$p);DoResolveCard($p,$ref(FaBStackTop()));$check(FaBHandCount($p)===$before+2,'Sigil return did not draw as a leave-arena trigger.');
 $reset($p);$hp=intval(GetHealth($p));FaBROSAdd($p,'PREVENT',2,['token'=>'ponder']);$source=AddCombatChain(1,CardID:'wounding_blow_red');DoDamage(1,$ref($source),$p,1);DoDamage(1,$ref($source),$p,2);$check(intval(GetHealth($p))===$hp-1&&count(FaBMONArena($p,'ponder'))===1,'Mental Block prevention created more than one Ponder or used wrong amount.');
 $reset($p);$weapon=AddWeapons($p,CardID:'rotwood_reaper',Owner:$p,Controller:$p);$check(FaBDYNWeaponCost('rotwood_reaper')===2&&FaBDYNWeaponCanAttack($p,FaBFindUID(intval($weapon->UniqueID))),'Rotwood Reaper attack not available at the correct cost.');FaBROSAdd($p,'RUNE_NEXT',3);FaBROSPlayed($p,$weapon,'Weapons');$check(in_array('WTR_POWER:3',(array)$weapon->TurnEffects,true)&&FaBROSCount($p,'RUNE_NEXT')===0,'Runeblade weapon did not consume next-attack bonus.');
 $reset($p);$o=AddHand($p,CardID:'photon_splicing_blue',Owner:$p,Controller:$p);$check(FaBARCActivate($p,FaBFindUID(intval($o->UniqueID)),0)&&!FaBHasPendingDecision(),'Discard-to-Amp incorrectly requested a spell target.');DoResolveCard($p,$ref(FaBStackTop()));$check(FaBMSTCount($p,'AMP')===1,'Discard-to-Amp ability did not resolve.');
 $reset($p);$hp=intval(GetHealth(1));$spell=AddHand($p,CardID:'trailblazing_aether_red',Owner:$p,Controller:$p);AddResources($p,3);AddActionPoints($p,1);FaBMSTAdd($p,'AMP');DoPlayCard($p,$ref($spell));$answer($p,$ref(GetHero(1)[0]));DoResolveCard($p,$ref(FaBStackTop()));$check(intval(GetHealth(1))===$hp-4&&intval(GetActionPoints($p))===1,'Surge failed to grant go again after increased damage.');
 $reset($p);FaBWTRCreateArena($p,'sigil_of_forethought_blue');$glyph=AddHand($p,CardID:'glyph_overlay_blue',Owner:$p,Controller:$p);DoPlayCard($p,$ref($glyph));$answer($p,$ref(GetHero(1)[0]));DoResolveCard($p,$ref(FaBStackTop()));$check(count(explode('&',FaBROSSigils($p)))===1,'Blue Glyph Overlay incorrectly surged below four damage.');
 $reset($p);GetHero($p)[0]->CardID='verdance';for($i=0;$i<4;++$i)AddBanish($p,CardID:'autumns_touch_blue');$truce=FaBWTRCreateArena(1,'truce_blue');FaBSetObjectCounter($truce,'ROS_OPP',$p);$oldTurn=intval(GetTurnNumber());FaBEndTurn($p);$check(GetTurnNumber()===$oldTurn&&FaBStackTop()!==null&&GetCurrentPhase()==='END','End phase advanced past an unresolved Verdance trigger.');$stack=FaBStackTop();DoResolveCard($p,$ref($stack));$answer($p,'-');GameAfterEngineAction([],[]);$check(intval(GetTurnNumber())===$oldTurn+1,'End phase did not resume after the last trigger.');
 $reset($p);$cuss=FaBWTRCreateArena($p,'arcane_cussing_red');$source=AddGraveyard($p,CardID:'photon_splicing_red');DoDamage($p,$ref($source),1,1,'ARCANE');$check(FaBARCRunechants($p)===0&&FaBStackTop()!==null,'Arcane Cussing skipped its triggered ability window.');DoResolveCard($p,$ref(FaBStackTop()));$check(FaBARCRunechants($p)===3,'Arcane Cussing did not create three Runechants.');
 $reset($p);FaBWTRCreateArena($p,'runechant');$uid=$macro($p,'condemn_to_slaughter_red');$answer($p,'-');$check(FaBROSCount($p,'RUNE_NEXT')===3,'Condemn lost its attack bonus when declining aura destruction.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "Rosetta mechanic outcomes passed in duels and UPF.\n";
