<?php
require_once __DIR__.'/sea_test.php';
$failures=[];
$reset=function(int $p)use($dynReset){$dynReset($p);foreach(FaBSeatOrder() as $v)foreach(['Temp','Inventory'] as $z){$get='Get'.$z;$a=&$get($v);$a=[];}};
$run=function(int $p,object $o,string $name='ResolveCard',array $params=[])use($ref){FaBRunSourceMacro($name,$p,$o->CardID,['mzID'=>$ref($o)]+$params);};
$resolve=function()use($answer){for($i=0;$i<50;$i++){if(FaBHasPendingDecision())return;$o=FaBStackTop();if(!$o)return;DoResolveCard(intval($o->Controller),'Stack-'.$o->mzIndex);}throw new RuntimeException('Stack did not settle');};
$gold=fn($p)=>count(FaBChoiceRefs($p,'Arena',['base'=>'gold']));
foreach([2,4] as $p){
 // Gravy Bones: additional Gold cost, tapping, draw/discard and live graveyard permission.
 $reset($p);GetHero($p)[0]->CardID='gravy_bones';$g=FaBWTRCreateArena($p,'gold');$blue=AddHand($p,CardID:'zap_blue',Owner:$p,Controller:$p);AddDeck($p,CardID:'barnacle_yellow',Owner:$p,Controller:$p);
 $check(FaBARCActivate($p,FaBIdentityFromMZ('p'.$p.'Hero-0'),0),'Gravy ability was not legal');$answer($p,$ref($g));$check(GetHero($p)[0]->Status===1&&$gold($p)===0,'Gravy did not tap and destroy Gold as costs');$resolve();$answer($p,$ref($blue));$check(FaBSEACount($p,'BLUE_GRAVE')===1&&FaBHandCount($p)===1,'Gravy draw/discard did not enable blue-grave condition');
 $ally=AddGraveyard($p,CardID:'barnacle_yellow',Owner:$p,Controller:$p);$s=FaBGetState();$s['window']='ACTION';FaBSetState($s);SetPriorityPlayer($p);$check(CanPlayCard($p,$ref($ally)),'Gravy cannot play face-up watery ally');FaBSEAFaceDown($ref($ally));$check(!CanPlayCard($p,$ref($ally))&&!in_array($ref($ally),FaBChoiceRefs($p,'Graveyard'),true),'Face-down grave card remained playable or selectable');
 // Watery Grave is triggered only by leaving the arena; defending action cards stay face-up.
 $reset($p);$a=AddArena($p,CardID:'barnacle_yellow',Owner:$p,Controller:$p);FaBMONDestroy(intval($a->UniqueID));$check(empty(FaBFindUID(intval($a->UniqueID))['object']->FaceDown)&&FaBStackTop()!==null,'Watery Grave skipped its trigger window');$resolve();$check(FaBFindUID(intval($a->UniqueID))['object']->FaceDown===1,'Watery Grave did not turn the physical card face-down');
 $a=AddCombatChain($p,CardID:'barnacle_yellow',Owner:$p,Controller:$p,Role:'DEFENSE',FromZone:'Hand');FaBMoveUID(intval($a->UniqueID),'Graveyard',$p);$check(empty(FaBFindUID(intval($a->UniqueID))['object']->FaceDown)&&FaBStackTop()===null,'Defending ally card incorrectly triggered Watery Grave');
 // Graveyard entry, discard and removal replacements have distinct conditions.
 $reset($p);$h=GetHealth($p);$a=AddDeck($p,CardID:'fiddlers_green_blue',Owner:$p,Controller:$p);FaBSEAMill($p);$check(GetHealth($p)===$h+3&&FaBSEACount($p,'BLUE_GRAVE')===1,'Fiddlers Green grave entry missed life or blue record');$a=AddHand($p,CardID:'fools_gold_yellow',Owner:$p,Controller:$p);FaBDiscardChoice($p,$ref($a));$check($gold($p)===1,'Discarding Fools Gold did not create Gold');
 $a=AddHand($p,CardID:'sea_legs_yellow',Owner:$p,Controller:$p);FaBDiscardChoice($p,$ref($a));$check(count(FaBChoiceRefs($p,'Arena',['base'=>'goldkiss_rum']))===1,'Sea Legs discard missed Rum');$a=AddStack(CardID:'goldfin_harpoon_yellow',Controller:$p,Kind:'ATTACK');FaBMoveStackUID(intval($a->UniqueID),'Graveyard',$p);$check(FaBFindUID(intval($a->UniqueID))===null,'Goldfin Harpoon survived graveyard replacement');
 $reset($p);$a=AddArena($p,CardID:'oysten_heart_of_gold_yellow',Owner:$p,Controller:$p);FaBMONDestroy(intval($a->UniqueID));$check($gold($p)===1,'Oysten death missed Gold');
 // Puffin, cog entry counters, crank's action point and second-crank draw.
 $reset($p);GetHero($p)[0]->CardID='puffin';AddDeck($p,CardID:'zap_blue');$a=FaBWTRCreateArena($p,'golden_cog');$check(intval(FaBObjectCounters($a)['STEAM']??0)===1,'Golden Cog did not enter with one steam');$answer($p,'0');$ap=GetActionPoints($p);FaBEVODoCrank($p,intval($a->UniqueID));$b=AddArena($p,CardID:'copper_cog_blue',Owner:$p,Controller:$p);FaBARCEnterItem($p,$b);$check(intval(FaBObjectCounters($b)['STEAM']??0)===2,'Copper Cog did not enter with two steam');$answer($p,'0');FaBEVODoCrank($p,intval($b->UniqueID));$check(GetActionPoints($p)===$ap+2&&FaBHandCount($p)===1,'Puffin second crank did not draw exactly once');FaBSEAUpkeepCog(intval($a->UniqueID));$check(FaBFindUID(intval($a->UniqueID))['zone']==='Graveyard','Empty Cog survived upkeep');
 // Marlynn draw trigger and arsenal entry; Sarong turning face-up is not entering arsenal.
 $reset($p);GetHero($p)[0]->CardID='marlynn';$a=AddDeck($p,CardID:'dry_powder_shot_red',Owner:$p,Controller:$p);DoDrawCard($p,1);$resolve();$answer($p,$ref($a));$f=FaBFindUID(intval($a->UniqueID));$check($f['zone']==='Arsenal'&&empty($f['object']->FaceDown)&&in_array('WTR_POWER:2',(array)$f['object']->TurnEffects,true),'Marlynn failed to load the drawn arrow with its entry bonus');
 $reset($p);$a=AddArsenal($p,CardID:'blue_fin_harpoon_blue',Owner:$p,Controller:$p,FaceDown:1);$e=AddEquipment($p,CardID:'sealace_sarong',Owner:$p,Controller:$p);$check(FaBARCActivate($p,FaBIdentityFromMZ($ref($e)),0),'Sarong activation failed');$answer($p,$ref($a));$resolve();$check(empty($a->FaceDown)&&in_array('GO_AGAIN',(array)$a->TurnEffects,true)&&$e->Status===1,'Sarong did not pay face-up/tap costs and grant go again');
 // Go Fish uses the victim's choice without cannon, private copies with cannon.
 foreach([false,true] as $cannon){$reset($p);$a=$attack($p,'red_fin_harpoon_blue');$h=AddHand(1,CardID:'zap_red',Owner:1,Controller:1);if($cannon)FaBSEAAdd($p,'CANNON');$run($p,$a,'Hit');$chooser=$cannon?$p:1;$d=GetDecisionQueue($chooser)[0];$choice=explode('&',$d->Param)[0];$check(str_starts_with($choice,'p'.$chooser.($cannon?'Temp':'Hand').'-'),'Go Fish exposed the wrong seat or zone');$answer($chooser,$choice);$check(FaBFindUID(intval($h->UniqueID))['zone']==='Graveyard'&&$gold($p)===1&&FaBChoiceRefs($p,'Temp')===[],'Go Fish missed discard/Gold or left a private preview: cannon='.intval($cannon).' zone='.(FaBFindUID(intval($h->UniqueID))['zone']??'gone').' gold='.$gold($p).' victimGold='.$gold(1).' temp='.count(FaBChoiceRefs($p,'Temp')));}
 // Goldkiss Rum taps, locks non-Pirates, and applies to the next action.
 $reset($p);GetHero($p)[0]->CardID='scurv_stowaway';$a=FaBWTRCreateArena($p,'goldkiss_rum');$r=GetResources($p);$check(FaBARCActivate($p,FaBIdentityFromMZ($ref($a)),0),'Rum activation failed');$resolve();$check(GetHero($p)[0]->Status===1&&GetResources($p)===$r+1,'Rum did not tap hero or trigger Scurv');$o=AddStack(CardID:'cogwerx_workshop_blue',Controller:$p,Kind:'ACTION');FaBSEAPlayed($p,$o,'Hand');$check(in_array('GO_AGAIN',(array)$o->TurnEffects,true),'Rum failed on a non-attack action');FaBSEAUntap('p'.$p.'Hero-0');$check(GetHero($p)[0]->Status===2,'Rum wrongly locked Pirate');GetHero($p)[0]->CardID='ira_crimson_haze';GetHero($p)[0]->Status=1;FaBSEAUntap('p'.$p.'Hero-0');$check(GetHero($p)[0]->Status===1,'Rum allowed non-Pirate to untap');
 // Not So Fast applies to Gold's draw only.
 $reset($p);AddDeck(1,CardID:'zap_red');AddDeck(1,CardID:'zap_blue');AddDeck($p,CardID:'nimblism_red');FaBSEAAdd($p,'NOT_SO_FAST');DoDrawCard(1,1);$check(FaBHandCount(1)===1&&FaBSEACount($p,'NOT_SO_FAST')===1,'Not So Fast replaced a non-Gold draw');$GLOBALS['seaDrawSource']='gold';DoDrawCard(1,1);unset($GLOBALS['seaDrawSource']);$check(FaBHandCount(1)===1&&FaBHandCount($p)===1&&!FaBSEACount($p,'NOT_SO_FAST'),'Not So Fast did not transfer the Gold draw');
 // High Tide / less Gold properties update while the attack is active.
 $reset($p);$a=$attack($p,'hms_marlin_yellow');$base=FaBAttackPower(FaBGetState());AddPitch($p,CardID:'zap_blue');$check(!FaBDYNOverpower($a,FaBGetState()),'High Tide active below two blues');AddPitch($p,CardID:'zap_blue');$check(FaBAttackPower(FaBGetState())===$base+1&&FaBDYNOverpower($a,FaBGetState()),'High Tide power/overpower did not update');
 $reset($p);$a=AddHand($p,CardID:'gold_hunter_ketch_yellow',Owner:$p,Controller:$p);$cost=FaBCardCost($a,$p);FaBWTRCreateArena(1,'gold');$check(FaBCardCost($a,$p)===max(0,$cost-2),'Gold Hunter Ketch did not discount');
 // Each Give No Quarter discounts the next two qualifying allies independently.
 $reset($p);$a=AddHand($p,CardID:'wailer_humperdinck_yellow',Owner:$p,Controller:$p);FaBSEAAdd($p,'QUARTER',2);FaBSEAAdd($p,'QUARTER',2);$check(FaBSEACost($p,$a)===-6,'Give No Quarter discounts did not stack');FaBSEAPlayed($p,$a,'Hand');$check(FaBSEACost($p,$a)===-6,'Stacked discount lost its second ally');FaBSEAPlayed($p,$a,'Hand');$check(FaBSEACost($p,$a)===0,'Stacked discount extended beyond two allies');
 // Pirate ally attacks pay their printed activation costs and respect tap state.
 $reset($p);$a=AddArena($p,CardID:'wailer_humperdinck_yellow',Owner:$p,Controller:$p);$check(FaBMONArenaAttackSpec($p,FaBIdentityFromMZ($ref($a)))['cost']===6,'Wailer attack lost its six-resource cost');$a->Status=1;$check(!FaBMONArenaCanAttack($p,FaBIdentityFromMZ($ref($a))),'Tapped ally was able to attack');FaBSEAUntap($ref($a));$check(FaBMONArenaCanAttack($p,FaBIdentityFromMZ($ref($a))),'Untapped ally could not attack');
 // Hero/ally taps, temporary control, Midas, and Treasure Island.
 $reset($p);$a=AddArena(1,CardID:'barnacle_yellow',Owner:1,Controller:1);$a->Status=1;FaBSEASteal($p,$ref($a),true);$f=FaBFindUID(intval($a->UniqueID));$check($f['player']===$p&&$f['object']->Owner===1&&$f['object']->Status===1,'Stealing changed physical owner or tap state');FaBSEAEnd($p);$check(FaBFindUID(intval($a->UniqueID))['player']===1,'Temporary control did not return');
 $reset($p);$a=AddArena(1,CardID:'swabbie_yellow',Owner:1,Controller:1);$cost=intval(CardCost($a->CardID));FaBSEAMidas($ref($a));$check($gold(1)===$cost&&$gold($p)===0,'Midas rewarded the wrong controller or amount');
 $reset($p);$island=AddArena(1,CardID:'treasure_island',Owner:1,Controller:1);$a=$attack($p,'strike_gold_red');FaBSEADeclared($p,$a);FaBSEADeclared($p,$a);$check(intval(FaBObjectCounters($island)['SEA_GOLD']??0)===1,'Treasure Island counted the same attacked hero twice');FaBSEAIslandGold(4);DoDamage($p,$ref($a),1,3);$check($gold($p)===3&&intval(FaBObjectCounters($island)['SEA_GOLD'])===2,'Treasure Island transferred the wrong number of counters');
 // Damage prevention and regeneration restrictions.
 $reset($p);FaBSEAAdd($p,'CAUTION',3);DoDamage(1,'',$p,1);$hp=GetHealth($p);DoDamage(1,'',$p,1);$check(GetHealth($p)===$hp-1,'Caution leaked unused prevention into a second event');FaBSEAAdd($p,'NO_HEAL');FaBCRUGainLife(1,4);$check(GetHealth(1)===30,'Deny Redemption did not prevent healing');
 // Mandatory equipment defense and returned arrows across a turn boundary.
 $reset($p);$a=$attack($p,'palantir_aeronought_red');$e=AddEquipment(1,CardID:'ironrot_helm',Owner:1,Controller:1);$s=FaBGetState();$s['window']='DEFEND_DECLARE';FaBSetState($s);SetPriorityPlayer(1);$check(FaBCRUMustEquip(1),'Palantir allowed passing with available equipment');
 $reset($p);$a=AddHand($p,CardID:'red_fin_harpoon_blue',Owner:$p,Controller:$p);FaBSEAReturnFire($p,$ref($a));SetTurnNumber(12);FaBSEABegin($p);$f=FaBFindUID(intval($a->UniqueID));$check($f['zone']==='Arsenal'&&empty($f['object']->FaceDown)&&in_array('WTR_POWER:3',(array)$f['object']->TurnEffects,true),'Return Fire lost its delayed arrow');
 // SEA non-attack bottom effects resolve from their live graveyard object.
 $reset($p);$a=AddGraveyard($p,CardID:'tip_the_barkeep_blue',Owner:$p,Controller:$p);FaBSEASetBottom(intval($a->UniqueID));$check(FaBFindUID(intval($a->UniqueID))['zone']==='Deck','Bottom-this effect remained in graveyard');
 // Damage to an extra ally target must not be charged to its hero.
 $reset($p);$a=$attack($p,'barbed_barrage_red');$ally=AddArena(1,CardID:'barnacle_yellow',Owner:1,Controller:1);$s=FaBGetState();$s['attackTargets']=[$s['attackTarget'],FaBAttackTargetDescriptor(FaBIdentityFromMZ($ref($ally)))];FaBSetState($s);$power=FaBAttackPower($s);FaBMultiTargetDamage($s);$check(GetHealth(1)===30-$power,'Barrage dealt the ally packet to its hero');
 // Hero-only creation suppression survives saved abilities and leaves card effects intact.
 $reset($p);$a=AddArena(1,CardID:'preach_modesty_red',Owner:1,Controller:1);GetHero($p)[0]->CardID='puffin';$run($p,GetHero($p)[0],'ResolveAbility');$check(FaBChoiceRefs($p,'Arena',['base'=>'golden_cog'])===[],'Modesty allowed Puffin to create a Cog');FaBHVYToken($p,'gold');$check($gold($p)===1,'Modesty suppressed an unrelated card effect');FaBMONDestroy(intval($a->UniqueID));$run($p,GetHero($p)[0],'ResolveAbility');$check(count(FaBChoiceRefs($p,'Arena',['base'=>'golden_cog']))===1,'Creation stayed blocked after Modesty left');
 // Compliance remains attached to the physical spell through stack-to-graveyard resolution.
 $reset($p);$a=AddStack(CardID:'zap_red',Controller:$p,Kind:'ACTION');$uid=intval($a->UniqueID);FaBARCSetCard($uid,'arcaneBonus',3);FaBSEACompliance($uid);FaBMoveStackUID($uid,'Graveyard',$p);$check(FaBUPRDamageBonus($p,$uid,3,'ARCANE')===3&&FaBARCArcaneAmount($p,$uid,3)===3,'Compliance lost the resolving spell');
 // A cog enhancement is limited by its own activation count and pays a live cog tap.
 $reset($p);$a=$attack($p,'sky_skimmer_red');$c=AddArena($p,CardID:'golden_cog',Owner:$p,Controller:$p);$d=AddArena($p,CardID:'golden_cog',Owner:$p,Controller:$p);SetPriorityPlayer($p);$check(FaBARCActivate($p,FaBIdentityFromMZ($ref($a)),0),'Sky Skimmer enhancement unavailable');$answer($p,$ref($c));$resolve();$answer($p,'0');$check($c->Status===1&&in_array('WTR_POWER:1',(array)$a->TurnEffects,true),'Cog enhancement did not pay tap and add power');SetPriorityPlayer($p);$check(!FaBARCAbilityActions($p,FaBIdentityFromMZ($ref($a))),'Sky Skimmer exceeded once per turn');
 // Native weapons and companions expose attacks independently of instant abilities.
 $reset($p);$a=AddWeapons($p,CardID:'cogwerx_blunderbuss',Owner:$p,Controller:$p);$check(FaBSEAWeaponCanAttack($p,FaBIdentityFromMZ($ref($a))),'Blunderbuss attack unavailable');$a->Status=1;$check(!FaBSEAWeaponCanAttack($p,FaBIdentityFromMZ($ref($a))),'Tapped Blunderbuss attack available');
 $reset($p);$a=AddEquipment($p,CardID:'polly_cranka',Owner:$p,Controller:$p);$check(FaBARCActivate($p,FaBIdentityFromMZ($ref($a)),0),'Polly activation unavailable');$check(FaBFindUID(intval($a->UniqueID))['zone']==='Banish','Polly did not banish as a cost');$resolve();$f=FaBFindUID(intval($a->UniqueID));$check($f['zone']==='Arena'&&$f['object']->Status===1&&intval(FaBObjectCounters($f['object'])['STEAM']??0)===1,'Polly did not return unequipped, tapped, with steam');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "High Seas mechanic outcomes passed in duels and UPF.\n";
