<?php
require_once __DIR__.'/upr_test.php';
$failures=[];
$uprReset=function(int $n)use($arcReset){$arcReset($n);SetTurnPlayer($n);SetPriorityPlayer($n);SetTurnNumber(10);SetCurrentPhase('MAIN');};
$uprMacro=function(int $p,string $id,string $macro='ResolveCard',string $zone='Graveyard'){$o=FaBAddToZone($zone,$p,(object)['CardID'=>$id]);FaBRunSourceMacro($macro,$p,$id,['mzID'=>FaBFindUID(intval($o->UniqueID))['mzID']]);return intval($o->UniqueID);};
$uprAttack=function(int $p,string $id,int $def=1){$o=AddCombatChain($p,CardID:$id,Owner:$p,Controller:$p,Role:'ATTACK',ChainLink:1);$s=FaBGetState();$s['attacker']=$p;$s['defender']=$def;$s['attackUID']=$o->UniqueID;$s['attackTarget']=['type'=>'HERO','player'=>$def,'uid'=>FaBUPRHeroUID($def),'zone'=>'Hero'];$s['chainLink']=1;$s['combatOpen']=true;$s['window']='REACTION';$s['combatStep']='REACTION';FaBSetState($s);return $o;};
foreach([2,4] as $n){$p=$n;
 $uprReset($n);$h=&GetHero($p);$h=[];AddHero($p,CardID:'dromai',Owner:$p,Controller:$p);FaBWTRCardPitched($p,'sweeping_blow_red');FaBWTRCardPitched($p,'sweeping_blow_blue');$check(count(FaBMONArena($p,'ash'))===1,'Dromai did not create exactly one Ash for red pitch.');
 $ash=FaBUPRAsh($p);$inv=AddArena($p,CardID:'invoke_yendurai_red',Owner:$p,Controller:$p);$dragon=FaBUPRTransform($p,$ash,'yendurai',intval($inv->UniqueID));$f=FaBFindUID($dragon);$check($f&&$f['object']->CardID==='yendurai'&&FaBUPRAsh($p)==='','Invocation failed to consume Ash and transform.');
 $check(FaBMONArenaAttackSpec($p,$f)===null,'Dragon attacks without Storm of Sandikai.');AddWeapons($p,CardID:'storm_of_sandikai',Owner:$p,Controller:$p);$check(FaBMONArenaAttackSpec($p,$f)!==null,'Storm did not enable dragon attacks.');
 $check(FaBUPRDeal(1,FaBUPRHeroUID(1),$dragon,4)===1&&$f['object']->Damage===1,'Yendurai endurance did not prevent three.');FaBUPRDeal(1,FaBUPRHeroUID(1),$dragon,3);$check(FaBFindUID($dragon)['zone']==='Graveyard'&&FaBFindUID($dragon)['object']->CardID==='invoke_yendurai_red','Dragon death did not restore invocation face.');
 $uprReset($n);$ally=FaBWTRCreateArena(1,'yendurai');FaBSetObjectCounter($ally,'ENDURANCE',1);$o=AddHand($p,CardID:'aether_dart_red');$uid=intval($o->UniqueID);$check(DoPlayCard($p,FaBFindUID($uid)['mzID']),'Aether Dart could not be announced.');$answer($p,FaBFindUID(intval($ally->UniqueID))['mzID']);$check(FaBStackTop()!==null&&FaBGetState()['pendingPayment']===null,'Any-target announcement failed to resume payment.');DoResolveCard($p,FaBFindUID($uid)['mzID']);$check($ally->Damage===0&&intval(FaBObjectCounters($ally)['ENDURANCE']??0)===0,'Spell targeting an ally bypassed endurance.');
 $uprReset($n);$ally=FaBWTRCreateArena(1,'nekria');$uid=intval($ally->UniqueID);FaBUPRDeal($p,FaBUPRHeroUID($p),$uid,1);$check($ally->Damage===1&&FaBUPRHealth($ally)===6&&count(FaBMONArena(1,'ash'))===1,'Nekria did not lose maximum health and create Ash.');
 $uprReset($n);$ar=AddArsenal(1,CardID:'aether_dart_blue');$r=FaBFindUID(intval($ar->UniqueID))['mzID'];FaBUPRFreeze($p,$r);$check(!FaBUPRCanPlay(1,FaBFindUID(intval($ar->UniqueID))),'Frozen arsenal was playable.');FaBUPRStart(1);$check(FaBUPRFrozen($ar),'Freeze expired at the wrong seat start.');FaBUPRStart($p);$check(!FaBUPRFrozen($ar),'Freeze did not expire at caster start.');
 $uprReset($n);FaBWTRCreateArena($p,'themai');$o=AddHand(1,CardID:'sigil_of_solace_red');$check(!FaBUPRCanPlay(1,FaBFindUID(intval($o->UniqueID))),'Themai allowed opposing instant.');SetTurnPlayer(1);$check(FaBUPRCanPlay(1,FaBFindUID(intval($o->UniqueID))),'Themai restricted an opponent on their own turn.');
 $uprReset($n);$a=$uprAttack($p,'critical_strike_red');FaBWTRTag($a,'GO_AGAIN');FaBWTRCreateArena($p,'hypothermia_blue');$check(!FaBAttackHasGoAgain(FaBGetState(),$a),'Hypothermia allowed gained go again.');$a->CardID='ronin_renegade_red';$check(FaBAttackHasGoAgain(FaBGetState(),$a),'Hypothermia removed printed go again.');
 $uprReset($n);$o=AddArena($p,CardID:'frost_hex_blue',Owner:$p,Controller:$p);$uid=intval($o->UniqueID);FaBUPRAfflict($p,$uid,FaBFindUID(FaBUPRHeroUID(1))['mzID']);$f=FaBFindUID($uid);$check($f['player']===1&&intval($f['object']->Owner)===$p,'Affliction lost its owner or controller.');FaBMONDestroy($uid);$check(FaBFindUID($uid)['player']===$p,'Destroyed affliction went to controller graveyard instead of owner.');
 $uprReset($n);$a=$uprAttack($p,'dunebreaker_cenipai_red');AddCombatChain(1,CardID:'fyendals_fighting_spirit_red',Owner:1,Controller:1,Role:'DEFENSE',ChainLink:1);$g=AddEquipment($p,CardID:'ghostly_touch',Owner:$p,Controller:$p);FaBMONPhantasm(FaBGetState(),false);$check(FaBFindUID(intval($a->UniqueID))['zone']==='CombatChain'&&FaBStackTop()!==null,'Phantasm did not provide a response window.');FaBWTRTag($a,'MON_NO_PHANTASM');$top=FaBStackTop();DoResolveCard($p,FaBFindUID(intval($top->UniqueID))['mzID']);$check(FaBFindUID(intval($a->UniqueID))['zone']==='CombatChain','Semblance did not stop pending phantasm.');$a->TurnEffects=[];FaBMONPhantasm(FaBGetState());$check(FaBObjectCounters($g)['HAUNT']===1&&count(FaBMONArena($p,'ash'))===1,'Phantasm did not trigger Ghostly Touch and Cenipai.');
 $uprReset($n);$o=AddHand($p,CardID:'sweeping_blow_red');FaBUPRAdd($p,'BLOOD',3);$check(FaBCardCost($o,$p)===0,'Blood did not reduce Draconic cost.');FaBUPRPlayed($p,$o);$check(FaBUPRCount($p,'BLOOD')===2,'Blood did not consume one of three reductions.');FaBUPRAdd($p,'TRANSMOGRIFY',8);FaBUPRPlayed($p,$o);$check(FaBHasType($o,'Illusionist')&&in_array('UPR_BASE:8',$o->TurnEffects,true),'Transmogrify did not set Illusionist and base power.');
 $uprReset($n);$o=AddHand(1,CardID:'sweeping_blow_red');FaBUPRAdd(1,'ERASE');$check(!FaBHasType($o,'Draconic')&&!FaBHasType($o,'Illusionist')&&FaBWTRIsAttackAction($o),'Erase Face did not remove class/talent while preserving action type.');
 $uprReset($n);$channel=FaBWTRCreateArena(1,'channel_the_bleak_expanse_blue');AddDeck($p,CardID:'critical_strike_red');DoDrawCard($p,1);$check(FaBHandCount($p)===0&&FaBStageSearch($p)==='','Bleak Expanse allowed effect draw/search.');$s=FaBGetState();$s['uprRefill']=true;FaBSetState($s);DoDrawCard($p,1);$check(FaBHandCount($p)===1,'Bleak Expanse blocked hand refill.');
 $uprReset($n);$a=$uprAttack($p,'critical_strike_red');$q=AddEquipment(1,CardID:'quelling_robe',Owner:1,Controller:1);AddResources(1,1);$before=intval(GetHealth(1));FaBBeginDamageStep();$check((GetDecisionQueue(1)[0]->Tooltip??'')==='Quell_combat_damage','Combat did not offer Quell.');$answer(1,FaBFindUID(intval($q->UniqueID))['mzID']);$check(intval(GetHealth(1))===$before-4&&intval(GetResources(1))===0&&FaBObjectCounters($q)['UPR_DESTROY_END']===1,'Quell did not pay, prevent one, and mark end-phase destruction.');
 $uprReset($n);$all=AddEquipment(1,CardID:'alluvion_constellas',Owner:1,Controller:1);AddResources(1,1);$o=AddHand($p,CardID:'aether_dart_red');$uid=intval($o->UniqueID);DoPlayCard($p,FaBFindUID($uid)['mzID']);$answer($p,FaBFindUID(FaBUPRHeroUID(1))['mzID']);$before=intval(GetHealth(1));DoResolveCard($p,FaBFindUID($uid)['mzID']);$answer(1,FaBFindUID(intval($all->UniqueID))['mzID']);$answer(1,'0');$check(intval(GetHealth(1))===$before-2&&FaBObjectCounters($all)['ENERGY']===1,'Alluvion barrier/energy did not resolve.');
 $uprReset($n);$o=AddDeck($p,CardID:'frosting_blue');$uid=intval($o->UniqueID);AddDeck($p,CardID:'aether_dart_red');$uprMacro($p,'tome_of_duplicity_blue');$answer($p,FaBFindUID($uid)['mzID']);$check(FaBFindUID($uid)['zone']==='Banish'&&FaBARCAsInstant($p,FaBFindUID($uid)['object'])&&count(FaBChoiceRefs($p,'Deck'))===1,'Duplicity did not preserve the other card and allow instant play.');

 $uprReset($n);$chill=FaBWTRCreateArena($p,'insidious_chill_blue');FaBSetObjectCounter($chill,'FROST',3);$ice=AddHand($p,CardID:'winters_grasp_blue');$spell=AddStack(CardID:'encase_red',Controller:$p,Kind:'ACTION',SourceZone:'Hand');$discard=AddHand(1,CardID:'critical_strike_red');FaBELEFinishFusion($p,intval($spell->UniqueID),[FaBFindUID(intval($ice->UniqueID))['mzID']],['Ice']);$answer($p,FaBFindUID(FaBUPRHeroUID(1))['mzID']);$answer(1,FaBFindUID(intval($discard->UniqueID))['mzID']);$check(FaBObjectCounters($chill)['FROST']===2&&FaBFindUID(intval($discard->UniqueID))['zone']==='Graveyard','Ice fusion did not trigger Chill tax.');
 $uprReset($n);$q=AddEquipment(1,CardID:'quelling_sleeves',Owner:1,Controller:1);AddResources(1,1);$before=intval(GetHealth(1));$o=AddHand($p,CardID:'zap_red');$uid=intval($o->UniqueID);DoPlayCard($p,FaBFindUID($uid)['mzID']);$answer($p,FaBFindUID(FaBUPRHeroUID(1))['mzID']);DoResolveCard($p,FaBFindUID($uid)['mzID']);$check(str_contains(GetDecisionQueue(1)[0]->Param,'Quell'),'Older-set spell did not offer Quell.');$answer(1,'1');$check(intval(GetHealth(1))===$before-2&&FaBObjectCounters($q)['UPR_DESTROY_END']===1,'Older-set spell Quell did not prevent damage and schedule destruction.');
 $uprReset($n);$g=AddEquipment($p,CardID:'ghostly_touch',Owner:$p,Controller:$p);$uid=intval($g->UniqueID);FaBSetObjectCounter($g,'HAUNT',3);FaBUPRAbilityPaid($p,$g);FaBUPRGhost($p,FaBFindUID($uid)['mzID']);$f=FaBFindUID($uid);$check($f['zone']==='Arena'&&FaBHasType($f['object'],'Ally')&&FaBUPRHealth($f['object'])===2&&FaBMONArenaAttackSpec($p,$f)['cost']===3,'Ghostly Touch transformation or attack cost failed.');FaBUPREnd($p);$check(FaBFindUID($uid)['zone']==='Equipment','Ghostly Touch did not return to equipment.');
 $uprReset($n);$w=AddWeapons($p,CardID:'searing_emberblade',Owner:$p,Controller:$p);AddResources($p,2);$check(FaBWTRCanActivate($p,FaBFindUID(intval($w->UniqueID))['mzID']),'Searing Emberblade has no attack activation.');

 $uprReset($n);$a=$uprAttack($p,'sweeping_blow_red');FaBUPRAdd($p,'UPRISING',4);FaBUPRAdd($p,'UPRISING',4);FaBUPRAttack($p,$a);$check(in_array('WTR_POWER:2',$a->TurnEffects,true)&&FaBUPRCount($p,'UPRISING')===6,'Stacked Uprisings did not each buff and consume a use.');FaBUPRAdd($p,'TRANSMOGRIFY',8);FaBUPRAdd($p,'TRANSMOGRIFY',7);FaBUPRPlayed($p,$a);$check(in_array('UPR_BASE:7',$a->TurnEffects,true),'Transmogrify base overrides were added together.');
 $uprReset($n);$ice=AddHand($p,CardID:'winters_grasp_blue');$spell=AddStack(CardID:'encase_red',Controller:$p,Kind:'ACTION',SourceZone:'Hand');FaBUPRAdd($p,'WEATHERVANE',4);FaBUPRAdd($p,'WEATHERVANE',3);FaBELEFinishFusion($p,intval($spell->UniqueID),[FaBFindUID(intval($ice->UniqueID))['mzID']],['Ice']);$answer($p,FaBFindUID(FaBUPRHeroUID(1))['mzID']);$other=$n===4?3:1;$answer($p,FaBFindUID(FaBUPRHeroUID($other))['mzID']);$check(count(FaBMONArena(1,'frostbite'))===($n===4?4:7)&&count(FaBMONArena($other,'frostbite'))===($n===4?3:7),'Stacked Weathervanes lost separate amounts/targets.');
}
if($failures){fwrite(STDERR,implode(PHP_EOL,$failures).PHP_EOL);exit(1);}echo "UPR outcome checks passed in duels and UPF.\n";
