<?php

// ProcessKeywordsSWU.php
// Reads cardArrayCache.json, parses innate keywords from card text fields,
// and writes SWUSim/GeneratedCode/GeneratedKeywordCode.php.
//
// Run via web: Data/ProcessKeywordsSWU.php?rootName=SWUSim
// Run via CLI: php Data/ProcessKeywordsSWU.php
//
// Keyword detection rule: a keyword is innate if a line in the card's text
// starts with that keyword name. Granted keywords (via "gains X", "each unit
// gains X", etc.) do not start the line and are excluded automatically.
//
// Fields checked per card:
//   text       — all keywords
//   deployBox  — all keywords (deployed leader unit side)
//   epicAction — Piloting only

$cacheFile  = __DIR__ . "/../SWUSim/GeneratedCode/cardArrayCache.json";
$outputFile = __DIR__ . "/../SWUSim/GeneratedCode/GeneratedKeywordCode.php";

if (!file_exists($cacheFile)) {
    die("ERROR: Cache not found at $cacheFile\n");
}

$cacheData = json_decode(file_get_contents($cacheFile), true);
if (!isset($cacheData['cardArray'])) {
    die("ERROR: cardArray key missing in cache\n");
}
$cardArray = $cacheData['cardArray'];

// --- Keyword definitions ---

// Boolean keywords: HasKeyword_X($obj) → true/false
$booleanKeywords = [
    'Ambush', 'Grit', 'Overwhelm', 'Saboteur', 'Sentinel', 'Shielded',
    'Bounty', 'Smuggle', 'Coordinate', 'Piloting', 'Hidden', 'Plot',
    'Support',
];

// Value keywords: HasKeyword_X($obj) + GetKeyword_X_Value($obj) → int|null
$valueKeywords = ['Raid', 'Restore', 'Exploit'];

$allKeywords = array_merge($booleanKeywords, $valueKeywords);

// Which fields to scan per keyword group
// All keywords live in text/deployBox; Piloting lives only in epicAction
$fieldMap = [
    'text'      => $allKeywords,
    'deployBox' => $allKeywords,
    'epicAction'=> ['Piloting'],
];

// --- Parse ---

// $innate[$keyword][$cardID] = true (boolean) or int (value keyword)
$innate = [];
foreach ($allKeywords as $kw) {
    $innate[$kw] = [];
}

foreach ($cardArray as $card) {
    $cardID = $card['id'] ?? null;
    if (!$cardID) continue;

    foreach ($fieldMap as $field => $kwList) {
        $raw = $card[$field] ?? '';
        if (empty($raw)) continue;

        foreach (explode("\n", $raw) as $line) {
            $ls = trim($line);
            if ($ls === '') continue;

            // Split on commas to handle "Ambush, Overwhelm" style lines.
            // Each segment is checked independently.
            $segments = preg_split('/,\s*/', $ls);

            foreach ($segments as $idx => $seg) {
                $seg = trim($seg);
                // Strip leading reminder-text continuation that can appear after a comma
                // (e.g. "Ambush, Overwhelm (When attacking...)" — the paren belongs to Overwhelm)

                foreach ($kwList as $kw) {
                    // Keyword must be at the start of the segment.
                    // Valid continuations: space, digit, (, [, end-of-string, .
                    if (!preg_match('/^' . preg_quote($kw, '/') . '(\s|\d|\(|\[|\.|$)/i', $seg)) continue;

                    if (in_array($kw, $valueKeywords)) {
                        // Extract numeric value — required for Raid/Restore/Exploit
                        if (preg_match('/^' . preg_quote($kw, '/') . '\s+(\d+)/i', $seg, $m)) {
                            $val = intval($m[1]);
                            if (!isset($innate[$kw][$cardID]) || $val > $innate[$kw][$cardID]) {
                                $innate[$kw][$cardID] = $val;
                            }
                        }
                        // No numeric value on this line → not an innate value-keyword declaration
                    } else {
                        $innate[$kw][$cardID] = true;
                    }
                }
            }
        }
    }
}

// --- Generate PHP ---

$date = date('Y-m-d H:i:s');
$php  = <<<PHP
<?php
// Generated Keyword Code for SWUSim
// Generated by Data/ProcessKeywordsSWU.php on: $date
// DO NOT MANUALLY EDIT — re-run ProcessKeywordsSWU.php to regenerate.
//
// HasKeyword_X(\$obj) checks (in order):
//   1. Innate:              card ID is in the lookup array (printed on the card)
//   2. TurnEffect:          \$obj->TurnEffects contains the keyword string (runtime grant)
//   3. Persistent override: HasGrantedKeyword(\$obj, 'KEYWORD') (indefinite grant)
//   4. Conditional/passive: HasConditionalKeyword_X(\$obj) in KeywordEffects.php
//
// GetKeyword_X_Value(\$obj) (value keywords) additionally:
//   - Scans TurnEffects for "X_N" patterns
//   - Adds GetConditionalKeyword_X_Value(\$obj) from KeywordEffects.php
//   Returns null if keyword is not present at all.

PHP;

foreach ($allKeywords as $kw) {
    $cards  = $innate[$kw];
    $kwKey  = str_replace(' ', '', $kw);    // e.g. "FloatingMemory"
    $teKey  = strtoupper($kwKey);           // e.g. "FLOATINGMEMORY" → TurnEffect string
    $isVal  = in_array($kw, $valueKeywords);

    $php .= "\n// ===== $kw =====\n\n";
    $php .= "\${$kwKey}_Cards = " . formatArray($cards) . ";\n\n";

    if ($isVal) {
        // HasKeyword delegates to GetValue
        $php .= <<<PHP
function HasKeyword_{$kwKey}(\$obj) {
    return GetKeyword_{$kwKey}_Value(\$obj) !== null;
}

PHP;

        if ($kw === 'Exploit') {
            // Exploit stacks additively — CR rule 16.b: multiple Exploit instances add together.
            // Other value keywords (Raid, Restore) use max() and keep the shared template below.
            $php .= <<<PHP
function GetKeyword_{$kwKey}_Value(\$obj) {
    global \${$kwKey}_Cards;
    \$val = \${$kwKey}_Cards[\$obj->CardID] ?? 0;
    \$val += SWUTurnEffectKeywordValueSum(\$obj, '{$teKey}');   // TurnEffect grants, additive (CR 16.b)
    if (function_exists('HasGrantedKeyword') && HasGrantedKeyword(\$obj, '{$teKey}')) \$val += 1;
    \$val += GetConditionalKeyword_{$kwKey}_Value(\$obj);
    return \$val > 0 ? \$val : null;
}

PHP;
        } else {
            $php .= <<<PHP
function GetKeyword_{$kwKey}_Value(\$obj) {
    global \${$kwKey}_Cards;
    \$val = \${$kwKey}_Cards[\$obj->CardID] ?? 0;
    \$val = max(\$val, SWUTurnEffectKeywordValue(\$obj, '{$teKey}'));   // TurnEffect grants, highest instance
    if (HasGrantedKeyword(\$obj, '{$teKey}')) \$val = max(\$val, 1);
    \$val += GetConditionalKeyword_{$kwKey}_Value(\$obj);
    return \$val > 0 ? \$val : null;
}

PHP;
        }
    } else {
        $php .= <<<PHP
function HasKeyword_{$kwKey}(\$obj) {
    global \${$kwKey}_Cards;
    // Suppression ("this unit loses {$kw} for this phase"): checked first so it
    // overrides innate/granted/conditional. Source = the suppressor's CardID (see
    // \$keywordSuppressors in KeywordEffects.php). (SOR_140 SpecForce Soldier → Sentinel.)
    if (SWUKeywordSuppressed(\$obj, '{$teKey}')) return false;
    if (isset(\${$kwKey}_Cards[\$obj->CardID])) return true;
    if (SWUHasTurnEffectKeyword(\$obj, '{$teKey}')) return true;   // TurnEffect grant (bare or CardID token)
    if (HasGrantedKeyword(\$obj, '{$teKey}')) return true;
    return HasConditionalKeyword_{$kwKey}(\$obj);
}

PHP;
    }
}

file_put_contents($outputFile, $php);

// --- Report ---
echo "<h2>ProcessKeywordsSWU — Done</h2>\n";
echo "<p>Written to: <code>$outputFile</code></p>\n";
echo "<table border='1' cellpadding='4'><tr><th>Keyword</th><th>Type</th><th>Innate cards</th></tr>\n";
$total = 0;
foreach ($allKeywords as $kw) {
    $count  = count($innate[$kw]);
    $type   = in_array($kw, $valueKeywords) ? 'value' : 'boolean';
    $total += $count;
    echo "<tr><td>$kw</td><td>$type</td><td>$count</td></tr>\n";
}
echo "<tr><td><strong>TOTAL</strong></td><td></td><td><strong>$total</strong></td></tr>\n";
echo "</table>\n";

// Helper: compact PHP array literal for SET_NNN → true or int maps
function formatArray(array $arr): string {
    if (empty($arr)) return '[]';
    $lines = ['['];
    foreach ($arr as $k => $v) {
        $val    = is_bool($v) ? 'true' : intval($v);
        $lines[] = "    '$k' => $val,";
    }
    $lines[] = ']';
    return implode("\n", $lines);
}
