<?php
// Regenerates SWUSim/Custom/cards/_index.generated.php from the per-card file headers.
//
// Each split card file's header declares its CardID(s) on the first comment line:
//     // SOR_033  |  Reprints: SEC_030, SHD_030
// This scan maps every declared CardID (primary + reprints) to that file's relative path.
//
// The runtime loader (cards/_loader.php) globs cards/*/*.php and does NOT use this map —
// it is a convenience index only, for tooling that resolves a card by ID. Because a few
// load-order-coupled cards still live in the monoliths (no per-card file), any existing
// index entry whose target still resolves on disk is PRESERVED, not dropped.
//
// Usage (also called by DevTools/scaffold-cards.php as a library):
//   php SWUSim/DevTools/regen-card-index.php          # write the index
//   php SWUSim/DevTools/regen-card-index.php --dry     # report the diff, write nothing

// Scan actual file headers → CardID => relative path. Primary declaration (first CID
// token on the canonical header line) wins over reprint-mentions; TS26 IDs (digits in
// the set code) match; entries whose files still exist are preserved if unseen.
function SWUSimBuildCardIndex(string $cardsDir): array {
    // Set code may contain digits (e.g. TS26); card number is 2-3 digits or a T## token.
    $cidRe = '/\b([A-Z][A-Z0-9]{1,4}_(?:T\d\d|\d{2,3}))\b/';
    // Read CIDs from ONLY the canonical header line — the FIRST `//` comment line after
    // `<?php`. Reading past it is unsafe: later dev comments cross-reference OTHER cards.
    $headerCids = function ($f) use ($cidRe) {
        foreach (file($f, FILE_IGNORE_NEW_LINES) as $ln) {
            $t = ltrim($ln);
            if ($t === '' || strncmp($t, '<?php', 5) === 0) continue;
            if (strncmp($t, '//', 2) !== 0) return [];              // code before any header
            return preg_match_all($cidRe, $ln, $m) ? $m[1] : [];    // the canonical header line
        }
        return [];
    };

    $files = [];
    foreach (glob("$cardsDir/*/*.php") as $f) {
        if (basename($f)[0] === '_') continue;
        $files[substr($f, strlen($cardsDir) + 1)] = $headerCids($f);
    }
    // Two passes so a PRIMARY declaration (first token) always wins over a reprint-mention.
    $fromFiles = [];
    foreach ($files as $rel => $cids) { if ($cids && !isset($fromFiles[$cids[0]])) $fromFiles[$cids[0]] = $rel; }
    foreach ($files as $rel => $cids) { foreach (array_slice($cids, 1) as $cid) { if (!isset($fromFiles[$cid])) $fromFiles[$cid] = $rel; } }

    $indexPath = "$cardsDir/_index.generated.php";
    $existing = is_file($indexPath) ? (require $indexPath) : [];
    // Merge: header scan is authoritative; preserve any prior entry whose file still exists
    // (monolith-coupled, or a header we couldn't parse).
    $index = $fromFiles;
    foreach ($existing as $cid => $rel) {
        if (isset($index[$cid])) continue;
        if (is_file("$cardsDir/$rel")) $index[$cid] = $rel;
    }
    ksort($index);
    return $index;
}

function SWUSimWriteCardIndex(string $cardsDir, array $index): void {
    $out  = "<?php\n";
    $out .= "// GENERATED by DevTools/regen-card-index.php (also refreshed by scaffold-cards.php) —\n";
    $out .= "// CardID => cards/<set>/<file> relative path, rebuilt from each card file's header.\n";
    $out .= "// The runtime loader globs cards/*/*.php and does NOT depend on this map; convenience only.\n";
    $out .= "return [\n";
    foreach ($index as $cid => $rel) $out .= "    '" . addslashes($cid) . "' => '" . addslashes($rel) . "',\n";
    $out .= "];\n";
    file_put_contents("$cardsDir/_index.generated.php", $out);
}

// CLI wrapper: only runs when invoked directly, not on require.
if (PHP_SAPI === 'cli' && isset($argv[0]) && realpath($argv[0]) === realpath(__FILE__)) {
    $dry = in_array('--dry', $argv, true);
    $cardsDir = __DIR__ . '/../Custom/cards';
    $existing = is_file("$cardsDir/_index.generated.php") ? (require "$cardsDir/_index.generated.php") : [];
    $index = SWUSimBuildCardIndex($cardsDir);
    $added = array_diff_key($index, $existing);
    $removed = array_diff_key($existing, $index);
    $changed = [];
    foreach ($index as $cid => $rel) if (isset($existing[$cid]) && $existing[$cid] !== $rel) $changed[$cid] = "{$existing[$cid]} -> $rel";
    echo "existing: " . count($existing) . "  new: " . count($index) . "\n";
    echo "added: " . count($added) . "\n";     foreach ($added as $c => $r) echo "  + $c => $r\n";
    echo "removed: " . count($removed) . "\n"; foreach ($removed as $c => $r) echo "  - $c => $r\n";
    echo "changed: " . count($changed) . "\n"; foreach ($changed as $c => $r) echo "  ~ $c : $r\n";
    if ($dry) { echo "(dry run — nothing written)\n"; exit(0); }
    SWUSimWriteCardIndex($cardsDir, $index);
    echo "wrote " . count($index) . " entries\n";
}
