<?php
require __DIR__.'/relicanth-draw-tests.php';
foreach([1,2] as $seat){
    drawBoard($seat);$f=GetZoneObject(PokeFirstRef($seat,'Bench'));$f->EnteredTurn=1;
    drawCheck(PokeCardImplemented('me05-062')&&PokeCardImplemented('me01-125'),'Package cards implemented');
    drawCheck(PokeRareCandyEligible($seat,'me05-062',$f),'Bastiodon can skip Shieldon from Antique Armor');
    $f->EnteredTurn=GetTurnNumber();drawCheck(!PokeRareCandyEligible($seat,'me05-062',$f),'Candy disallows a fossil played this turn');$f->EnteredTurn=1;
    $f->EvolvedTurn=GetTurnNumber();drawCheck(!PokeRareCandyEligible($seat,'me05-062',$f),'Candy disallows a second evolution this turn');$f->EvolvedTurn=-1;
    $f->CardID='me05-073';drawCheck(!PokeRareCandyEligible($seat,'me05-062',$f),'Candy disallows wrong fossil');$f->CardID='me05-072';
    drawCheck(!PokeRareCandyEligible($seat,'me05-062',GetZoneObject(PokeFirstRef($seat,'Active'))),'Candy disallows unrelated Basic');
    $f->Energy=['mee-003'];$f->Tool='sv06-158';$f->Damage=20;
    PokeAdd($seat,'Hand','me05-062');drawPlay($seat,'me01-125');drawDrain();
    $f=GetZoneObject(PokeFirstRef($seat,'Bench'));
    drawCheck($f->CardID==='me05-062'&&$f->Evolutions===['me05-072']&&$f->Energy===['mee-003']&&$f->Tool==='sv06-158'&&$f->Damage===20,'Serialized Candy flow preserves evolution stack and attachments');
    $enemy=GetZoneObject(PokeFirstRef(3-$seat,'Active'));$active=GetZoneObject(PokeFirstRef($seat,'Active'));
    $enemy->Energy=['mee-005','mee-005'];PokeDealAttackDamage(3-$seat,PokeFirstRef(3-$seat,'Active'),30);
    drawCheck($active->Damage===0,'Two-Energy attacker is blocked on Active');
    PokeDealAttackDamage(3-$seat,PokeFirstRef(3-$seat,'Active'),30,false,PokeFirstRef($seat,'Bench'));
    drawCheck($f->Damage===20,'Bulwark also protects Bench');
    PokePlaceDamageCounters(PokeFirstRef(3-$seat,'Active'),PokeFirstRef($seat,'Active'),1);
    drawCheck($active->Damage===10,'Bulwark permits damage counters');
    $enemy->Energy[]='mee-005';PokeDealAttackDamage(3-$seat,PokeFirstRef(3-$seat,'Active'),10);
    drawCheck($active->Damage===20,'Three-Energy attacker bypasses Bulwark');
    $enemy->Energy=['mee-005'];$f->Counters['noAbilities']=true;PokeDealAttackDamage(3-$seat,PokeFirstRef(3-$seat,'Active'),10);
    drawCheck($active->Damage===30,'Disabled Bastiodon provides no protection');
    drawBoard($seat);GetZoneObject(PokeFirstRef($seat,'Active'))->CardID='me05-062';
    drawCheck(PokeAncientBulwark($seat,GetZoneObject(PokeFirstRef(3-$seat,'Active')))===0,'Active Bastiodon provides no protection');
    drawBoard($seat);$ctx=PokeBotContext(PokeObservation(3-$seat));$f=drawField($seat,'Bench','me05-062');
    PokeAdd(3-$seat,'Hand','mee-005');$ctx=PokeBotContext(PokeObservation(3-$seat));
    $a=['type'=>'attach','source'=>PokeFirstRef(3-$seat,'Hand'),'target'=>PokeFirstRef(3-$seat,'Active')];
    drawCheck(PokeBotActionScore($ctx,$a)===190.0,'Dhelmise builds extra Energy against visible Bulwark');
    drawCheck(PokeBotDamage($ctx,$ctx['own']['Active'][0],$ctx['enemy']['Active'][0])===0,'Dhelmise respects prevention in damage estimate');
    GetZoneObject(PokeFirstRef(3-$seat,'Active'))->CardID='me02-084';$ctx=PokeLopunnyContext(PokeObservation(3-$seat));
    drawCheck(PokeLopunnyActionScore($ctx,$a)===190.0,'Lopunny builds extra Energy against visible Bulwark');
    drawBoard($seat);GetZoneObject(PokeFirstRef(3-$seat,'Active'))->CardID='me02-084';PokeAdd($seat,'Hand','sv06-158');PokeAdd($seat,'Hand','sv10.5w-080');
    $ctx=PokeBotContext(PokeObservation($seat));$a=PokeBotChoose(PokeObservation($seat));
    drawCheck(($a['type']??'')==='trainer'&&GetZoneObject($a['source'])->CardID==='sv10.5w-080','Bangle wins the tool slot when both tools are held');
}
drawBoard();$GLOBALS['p1PlayerTurns']=[];AddPlayerTurns(1,1);$f=GetZoneObject('p1Bench-0');$f->EnteredTurn=0;
drawCheck(!PokeRareCandyEligible(1,'me05-062',$f),'Candy is illegal on first player turn');
drawBoard();drawField(2,'Bench','me05-062');$ctx=PokeBotContext(PokeObservation(1));$target=end($ctx['enemy']['Bench']);
drawCheck(PokeBotEnemyBulwark($ctx)&&!PokeBotEnemyBulwark(PokeBotGustContext($ctx,$target)),'Gusting a lone Bastiodon turns off protection');
drawField(2,'Bench','me05-062');$ctx=PokeBotContext(PokeObservation(1));$target=end($ctx['enemy']['Bench']);
drawCheck(PokeBotEnemyBulwark(PokeBotGustContext($ctx,$target)),'Gusting one of two Bastiodon retains protection');
drawBoard();GetZoneObject('p2Active-0')->CardID='me02-084';
for($i=0;$i<4;++$i)drawField(1,'Bench','me05-073');$ctx=PokeBotContext(PokeObservation(1));
drawCheck(PokeRelicanthDamage($ctx,$ctx['enemy']['Active'][0])===160,'Five Antiques yield 160 without a tool');
GetZoneObject('p1Active-0')->Tool='sv10.5w-080';$ctx=PokeBotContext(PokeObservation(1));
drawCheck(PokeRelicanthDamage($ctx,$ctx['enemy']['Active'][0])===190&&$ctx['enemy']['Active'][0]['hp']===330,'Bangle changes full-bench Lopunny from three hits to two');
GetZoneObject('p1Bench-0')->CardID='me05-062';$ctx=PokeBotContext(PokeObservation(1));
drawCheck(PokeRelicanthDamage($ctx,$ctx['enemy']['Active'][0])===160,'Bastiodon plus Bangle still needs three hits on fresh Lopunny');
PokeAdd(1,'Hand','me01-125');$ctx=PokeBotContext(PokeObservation(1));
drawCheck(PokeRelicanthDrawBulwarkTargetCount($ctx)===2,'Second Bulwark may protect against gust without adding a Lopunny hit');
GetZoneObject('p2Active-0')->Energy=['mee-003','mee-003','mee-003'];$ctx=PokeBotContext(PokeObservation(1));
drawCheck(!PokeRelicanthDrawWantsBulwark($ctx),'Three-Energy opposing Active prevents wasted Candy setup');
drawBoard();PokeAdd(1,'Hand','me01-125');drawField(1,'Bench','me05-073');$ctx=PokeBotContext(PokeObservation(1));
$d=['prompt'=>'Choose a new Active','type'=>'MZCHOOSE','choices'=>[
    ['card'=>'me05-072','value'=>'p1Bench-0'],['card'=>'me05-073','value'=>'p1Bench-1']]];
drawCheck(PokeRelicanthDrawDecision($ctx,$d)==='p1Bench-1','Promotion preserves Armor while pursuing Candy');
drawBoard();PokeAdd(1,'Hand','sv06-158');PokeAdd(1,'Hand','sv10.5w-080');$a=PokeBotChoose(PokeObservation(1));
drawCheck($a['type']==='trainer'&&GetZoneObject($a['source'])->CardID==='sv06-158','Helmet retains tool priority against a non-ex board');
$observed=0;$plain=PokeSimulateGame(32145,1,1500,'relicanth-v2-draw','dhelmise-v2');
$watched=PokeSimulateGame(32145,1,1500,'relicanth-v2-draw','dhelmise-v2',null,null,static function($a)use(&$observed){++$observed;});
drawCheck($plain===$watched&&$observed===$watched['actions'],'Read-only observer captures all accepted actions without changing the match');
echo "$checks total draw/package checks passed\n";
