<?php
// Card tags for the heuristic bot stack and the RL move keys (RL bots spec, Section 3). The tables are
// generated by SWUSim/DevTools/rl/tag_cards.php; this is only the accessor. A wrong tag only weakens
// cross-deck transfer — archetype layers correct it.
//
// THREE GENERATIONS, each frozen so its measurements stay reproducible (BotFeatures.php):
//   v1  the Phase 1a table            — read under '@no-tags2'
//   v2  the nine coarse tags          — read under '@no-tags3'
//   v3  face-scoped, kebab-case, keywords included (owner rulings 2026-09-28) — the default
require_once __DIR__ . '/CardTags.generated.php';      // v3 (face-scoped)
require_once __DIR__ . '/CardTags.v1.generated.php';
require_once __DIR__ . '/CardTags.v2.generated.php';

// The nine RL-key tags — see SWUBotCardTagsForRlKey(). 'damage' became 'damage-enemy-unit' on 2026-10-01 when `damage`
// was retired: the owner chose to BREAK the RL key space (every trained policy keyed on 'damage') rather than shim it.
// 'burn' became 'damage-enemy-base' the same day, the same way.
const SWU_BOT_TAGS_V2_SET = ['removal', 'damage-enemy-unit', 'draw', 'buff', 'bounce', 'exhaust', 'heal', 'wipe', 'damage-enemy-base'];

// Every tag on the card, both faces merged. This is the v2-compatible shape: a flat list of strings, so all
// the pre-v3 callers (BotFallback's weight sum, BotResourcing, BotGuides, BotFlavours, BotRules,
// BotDeckStyle, SwuValueFeatures) keep working untouched.
function SWUBotCardTags(string $cardID): array {
    if (function_exists('SWUBotFeatureOn')) {
        if (!SWUBotFeatureOn('tags2')) return ($GLOBALS['SWUBotCardTagTableV1'] ?? [])[$cardID] ?? [];
        if (!SWUBotFeatureOn('tags3')) return ($GLOBALS['SWUBotCardTagTableV2'] ?? [])[$cardID] ?? [];
    }
    $faces = ($GLOBALS['SWUBotCardTagTable'] ?? [])[$cardID] ?? null;
    if ($faces === null) return [];
    $out = [];
    foreach ($faces as $tags) foreach ($tags as $t) $out[$t] = true;
    return array_keys($out);
}

// ONE FACE of a leader (owner ruling 2026-09-28: "face-scoped"). $face is 'front' or 'deployed'.
// The two faces can want OPPOSITE decisions — LOF Kit Fisto's flip is pointless with no Jedi units on board,
// so the leader is worth more unflipped — and a deploy scorer cannot see that from the merged list.
// Returns [] under @no-tags2 / @no-tags3, whose frozen tables are not face-scoped: a caller that needs faces
// must treat "no faces" as "unknown", never as "this face does nothing".
function SWUBotCardTagsForFace(string $cardID, string $face): array {
    if (function_exists('SWUBotFeatureOn') && (!SWUBotFeatureOn('tags2') || !SWUBotFeatureOn('tags3'))) return [];
    return (($GLOBALS['SWUBotCardTagTable'] ?? [])[$cardID] ?? [])[$face] ?? [];
}

// Is this card's tag data face-scoped? False under the frozen v1/v2 tables, so a face-aware caller can tell
// "this face has no tags" from "this generation cannot answer".
function SWUBotCardTagsAreFaceScoped(): bool {
    return !function_exists('SWUBotFeatureOn') || (SWUBotFeatureOn('tags2') && SWUBotFeatureOn('tags3'));
}

// ⚠ RL MOVE KEYS ONLY. SwuKeys.php embeds the sorted tag list in "play:event:<cost>:<tagStr>" and
// "play:upgrade:<cost>:<tagStr>", so the v3 tags would multiply the key space and invalidate every trained
// policy and value table keyed on it. Pinning the key to the nine v2 names keeps that space stable; the
// stale-card CORRECTIONS still move the keys they should (a card that was wrongly untagged now keys right).
function SWUBotCardTagsForRlKey(string $cardID): array {
    return array_values(array_intersect(SWUBotCardTags($cardID), SWU_BOT_TAGS_V2_SET));
}
