<?php
// Coarse card tags for the heuristic bot stack and the RL move keys (RL bots spec, Section 3). The table is
// generated by SWUSim/DevTools/rl/tag_cards.php; this is only the accessor. A wrong tag only weakens
// cross-deck transfer — archetype layers correct it.
require_once __DIR__ . '/CardTags.generated.php';
require_once __DIR__ . '/CardTags.v1.generated.php';   // the frozen Phase 1a table, for the strength test's @no-tags2

function SWUBotCardTags(string $cardID): array {
    $v1 = function_exists('SWUBotFeatureOn') && !SWUBotFeatureOn('tags2');
    return ($v1 ? ($GLOBALS['SWUBotCardTagTableV1'] ?? []) : ($GLOBALS['SWUBotCardTagTable'] ?? []))[$cardID] ?? [];
}
